"""Evidence record specs Part E: D143-D157 (conditional memory, test-time compute, routing), D162 (X), D163-D165 (F1-F3)."""
PART_E = {
"D143": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Conditional memory vs conditional computation; O(1) N-gram lookup; U-shaped Sparsity Allocation; iso-param/iso-FLOP MoE wins.",
  entity=("engram-paper-2026", "Conditional Memory via Scalable Lookup / Engram (Cheng et al., 2026)", "PAPER", "DeepSeek-AI"),
  artifact="PAPER", lineage="CORE", branches=["conditional-memory", "conditional-compute-moe"], transitions=["compute-only-to-compute-plus-memory"],
  inherit=None, caveat="First-party (DeepSeek) paper for a DeepSeek-adopted module; iso-baseline comparisons are author-framed.",
  claims=[
    ("Engram modernizes N-gram embeddings as O(1) static lookup, proposing conditional memory as a sparsity axis complementary to MoE conditional computation.", "PRIMARY_FACT", "Headline mechanism; abstract consumed (2601.07372, pub 2026-01-12)."),
    ("The Sparsity Allocation analysis finds a U-shaped law trading neural computation (MoE) against static memory (Engram); a 27B Engram beats iso-parameter/iso-FLOP MoE baselines with larger gains in reasoning (BBH +5.0, ARC-C +3.7) than retrieval (MMLU +3.4).", "AUTHOR_CLAIM", "Author-framed comparisons; abstract-level figures.")],
  limits=["Full-body allocation-law derivations and benchmark tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2601.07372): O(1) lookup + U-shaped law + iso-win figures confirmed; full body outstanding.")}),
"D144": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Official demo + paper PDF + eval figures; implementation evidence for addressing/offload claims.",
  entity=("engram-repo", "deepseek-ai/Engram official implementation", "PRODUCT", "DeepSeek-AI"),
  artifact="FRAMEWORK", lineage="CORE", branches=["conditional-memory"], transitions=["paper-to-implementation"],
  inherit=None, caveat="Repo not fetched; implementation-existence facts at release level.",
  claims=[
    ("The official Engram repo publishes a demo, the paper PDF, and evaluation figures, constituting implementation evidence for the addressing/offload claims.", "PROJECT_CLAIM", "Release-level; corroborates D143."),
    ("Demo + figures give the host-offload and addressing behavior a runnable surface beyond the paper.", "INFERENCE", "Implementation significance.")],
  limits=["Repo code, demo, and figures not consumed."],
  ver={"@FULL": ("VERIFIED", "Implementation-evidence role recorded at release level; repo audit outstanding.")}),
"D145": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Qwen N-gram vs Engram lineage assessment: no derivation statement located; ancestry NOT inferred.",
  entity=("qwen-engram-lineage", "Qwen N-gram vs Engram lineage assessment (Qwen3.8-Flash-Next repo)", "PRODUCT", "Alibaba Qwen"),
  artifact="MODEL", lineage="PARALLEL", branches=["conditional-memory", "capstone-2026-qwen"], transitions=["independent-convergence"],
  inherit=None, caveat="Parallel-or-unresolved lineage: shared design pressure confirmed, derivation unproven; ancestry must not be inferred.",
  claims=[
    ("Qwen3.8-Flash-Next carries 51B of per-layer n-gram (PLE) tables with host-side hashing; no statement deriving them from Engram was located.", "PROJECT_CLAIM", "Configuration facts per D008/D165; derivation absence is a searched negative."),
    ("The correct lineage handling is PARALLEL_OR_UNRESOLVED: convergent response to memory-vs-compute pressure, not established derivation.", "INFERENCE", "Lineage-hygiene ruling.")],
  limits=["Exhaustive derivation-statement search not claimed; Qwen-side provenance docs may postdate this pass."],
  ver={"@FULL": ("VERIFIED", "PLE configuration corroborated via D008/D165; derivation absence recorded as searched negative.")}),
"D146": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="kNN-LM explicit-corpus retrieval precedent; boundary-sharpening only vs static lookup.",
  entity=("knn-lm-2019", "Generalization through Memorization: Nearest Neighbor Language Models (Khandelwal et al., 2019)", "PAPER", "NYU/Facebook"),
  artifact="PAPER", lineage="BRIDGE", branches=["conditional-memory"], transitions=["parametric-to-retrieval-interpolation"],
  inherit=None, caveat="Query-time ANN retrieval over explicit corpora differs categorically from O(1) static N-gram lookup; precedent role only.",
  claims=[
    ("kNN-LM interpolates a frozen LM with kNN over an explicit datastore, cutting Wikitext-103 perplexity to 15.79 (-2.9) with no training and enabling domain adaptation by datastore swap.", "PRIMARY_FACT", "Headline results; abstract consumed (1911.00172)."),
    ("Explicit-corpus query-time retrieval sharpens the boundary of Engram-style static lookup by contrast, and nothing more.", "INFERENCE", "Boundary role.")],
  limits=["Full-body interpolation analysis not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (1911.00172): kNN interpolation + perplexity confirmed; full body outstanding.")}),
"D147": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="RETRO chunked cross-attention precedent; closes the precedent sweep, boundary role only.",
  entity=("retro-2021", "Improving Language Models by Retrieving from Trillions of Tokens / RETRO (Borgeaud et al., 2021)", "PAPER", "DeepMind"),
  artifact="PAPER", lineage="BRIDGE", branches=["conditional-memory"], transitions=["parametric-to-retrieval-architecture"],
  inherit=None, caveat="Chunked cross-attention retrieval architecture differs from static lookup fusion; precedent role only.",
  claims=[
    ("RETRO conditions generation on chunks retrieved from a 2T-token database via chunked cross-attention, matching GPT-3/Jurassic-1 on the Pile with 25x fewer parameters.", "PRIMARY_FACT", "Headline results; abstract consumed (2112.04426)."),
    ("RETRO closes the retrieval-precedent sweep; its fusion mechanism contrasts with Engram static lookup.", "INFERENCE", "Sweep-closure statement.")],
  limits=["Full-body retrieval-encoder design not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2112.04426): chunked-retrieval + 25x-param result confirmed; full body outstanding.")}),
"D148": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Lane origin: test-time > parameter scaling for reasoning; verifier/search; difficulty dependence; FLOPs-matched allocation.",
  entity=("ttc-snell-2024", "Scaling LLM Test-Time Compute Optimally can be More Effective than Scaling Model Parameters (Snell et al., 2024)", "PAPER", "Berkeley/Google DeepMind"),
  artifact="PAPER", lineage="CORE", branches=["test-time-compute"], transitions=["pretrain-scale-to-test-time-scale"],
  inherit=None, caveat="Difficulty-dependent allocation findings are method- and benchmark-bound; not a universal scaling law.",
  claims=[
    ("Snell et al. show test-time compute scaling (verifier-guided search, revision) can beat parameter scaling for reasoning under FLOPs-matched comparisons, with optimal allocation varying by problem difficulty.", "PRIMARY_FACT", "Headline findings; abstract consumed (2408.03314)."),
    ("The paper founds the test-time-compute lane: compute allocation at inference as a first-class efficiency axis.", "INFERENCE", "Lane-origin significance.")],
  limits=["Full-body verifier/search comparisons not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2408.03314): TTC-vs-params finding confirmed; full body outstanding.")}),
"D149": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Budget forcing (truncate/Wait-extend); s1K SFT; sequential/parallel taxonomy; benchmark-specific claims.",
  entity=("s1-2025", "s1: Simple test-time scaling (Muennighoff et al., 2025)", "PAPER", "Stanford"),
  artifact="PAPER", lineage="CORE", branches=["test-time-compute"], transitions=["uncontrolled-to-budget-forced-reasoning"],
  inherit=None, caveat="s1K/SFT recipe and Wait-extension effects are Qwen2.5-32B-bound; transfer to other families unproven here.",
  claims=[
    ("s1 curates the 1K-example s1K set (difficulty/diversity/quality) and introduces budget forcing: truncating thought or extending it with 'Wait' to control test-time compute after SFT on Qwen2.5-32B-Instruct.", "PRIMARY_FACT", "Headline method; abstract consumed (2501.19393)."),
    ("Sequential/parallel TTC taxonomy plus explicit-budget control prefigures the V4.1/Qwen numeric reasoning-effort interfaces (D153).", "INFERENCE", "Lineage linkage.")],
  limits=["Full-body ablation tables and benchmark results not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2501.19393): s1K + budget-forcing confirmed; full body outstanding."),
        "claim scope": ("VERIFIED", "Qwen2.5-32B-bound scope recorded; transfer to other families unclaimed.")}),
"D150": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="ThinkPrune mechanism confirmed as learned RL pruning (not heuristic) with AIME24 numbers; full tradeoff tables outstanding.",
  entity=("thinkprune-2025", "ThinkPrune: Pruning Long Chain-of-Thought of LLMs via Reinforcement Learning (Hou et al., 2025)", "PAPER", "UCSB"),
  artifact="PAPER", lineage="CORE", branches=["test-time-compute"], transitions=["forced-exit-to-learned-pruning"],
  inherit=None, caveat="Abstract-level only; full token/quality tradeoff tables and training-cost accounting outstanding.",
  claims=[
    ("ThinkPrune trains long-thinking LLMs with RL under an added token limit (unfinished thought = zero reward), iteratively tightening the limit across rounds to consolidate rather than force-exit reasoning.", "AUTHOR_CLAIM", "Mechanism consumed via arXiv abstract (2504.01296, pub 2025-04-02): learned policy, not a heuristic cutoff."),
    ("Reported effect: DeepSeek-R1-Distill-Qwen-1.5B reasoning length halved on AIME24 with ~2% performance drop; pruned models skip unnecessary steps while keeping core reasoning complete; code released.", "AUTHOR_CLAIM", "Headline figures per abstract; benchmark- and student-model-bound."),
    ("ThinkPrune's learned-pruning-vs-heuristic distinction answers the screening question in favor of real weight: it is a trainable TTC method in the test-time-compute taxonomy.", "INFERENCE", "Taxonomic resolution of the INSPECT question.")],
  limits=["Full paper body (tradeoff curves, RL cost, generalization beyond R1-Distill-1.5B/AIME24) not consumed.", "Relation to budget-forcing (s1) and overthinking (D151) synthesis deferred to Selection/Architecture."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed in full: RL-with-token-limit mechanism, iterative pruning, AIME24 figures, code link extracted; full-body tables outstanding."),
        "confirm body weight or substitute": ("VERIFIED", "Weight confirmed: real method with reported numbers and released code; no substitute needed. Full tradeoff tables remain open as limitation.")}),
"D151": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="R1-32B vs s1-32B peak-then-decline ~10K; flip mechanism; 16x cost arithmetic; adaptive-stopping case.",
  entity=("overthinking-2026", "When More Thinking Hurts: Overthinking in LLM Test-Time Compute Scaling (2026)", "PAPER", "Independent"),
  artifact="PAPER", lineage="CORE", branches=["test-time-compute"], transitions=["more-compute-to-optimal-stopping"],
  inherit=None, caveat="Peak/decline budgets are model- and task-bound; 16x arithmetic is the paper's cost illustration, not a measured invoice.",
  claims=[
    ("Extended reasoning exhibits peak-then-decline accuracy (~10K-token region for R1-32B vs s1-32B) with a flip mechanism abandoning correct answers — 'overthinking'.", "AUTHOR_CLAIM", "Headline finding; abstract consumed (2604.10739, pub 2026-04-12)."),
    ("Cost-aware evaluation shows moderate-budget stopping preserves accuracy at large compute savings (16x cost arithmetic), the adaptive-stopping case.", "AUTHOR_CLAIM", "Cost framing per abstract."),
    ("Overthinking plus ThinkPrune plus budget-forcing jointly motivate explicit reasoning-effort controls (D153) as the production answer.", "INFERENCE", "Synthesis to effort-control binding.")],
  limits=["Full-body flip-mechanism analysis and cost framework not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2604.10739): overthinking + cost-aware stopping confirmed (model/task-bounded scope; 16x carried as paper arithmetic); full body outstanding.")}),
"D152": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="Reasoning-on-a-Budget survey: secondary-by-design taxonomy; candidate-finder only.",
  entity=("ttc-survey-2025", "Reasoning on a Budget: A Survey of Adaptive and Controllable Test-Time Compute in LLMs (2025)", "PAPER", "Independent"),
  artifact="PAPER", lineage="CONTEXT", branches=["test-time-compute"], transitions=["methods-to-taxonomy"],
  inherit=None, caveat="Secondary-by-design; taxonomy use only, no primary finding cited.",
  claims=[
    ("The survey taxonomizes adaptive/controllable TTC into L1-controllability (fixed-budget methods) vs L2-adaptiveness (difficulty/confidence-scaled methods) with proprietary-LLM benchmarks.", "AUTHOR_CLAIM", "Taxonomy facts; abstract consumed (2507.02076, pub 2025-07-02)."),
    ("The L1/L2 taxonomy is adopted as the Special's organizing frame for effort-control discussion; no survey benchmark number is cited.", "INFERENCE", "Taxonomy adoption with use boundary.")],
  limits=["Survey body and benchmark tables not consumed; candidate-finder role only."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2507.02076): L1/L2 taxonomy confirmed; survey body outstanding."),
        "primary candidates": ("UNRESOLVED", "Survey-referenced primary candidates not individually pursued; deferred to Sol gap-fill judgment.")}),
"D153": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Current-model effort-control binding: V4.1 effort 1-100 + penalty tables; Qwen enable_thinking/reasoning_effort; explicit-budget class (6).",
  entity=("effort-control-binding", "Current-model effort-control binding (V4.1 + Qwen)", "PRODUCT", "DeepSeek-AI/Alibaba Qwen"),
  artifact="PRODUCT", lineage="CORE", branches=["test-time-compute", "capstone-2026-v41"], transitions=["implicit-reasoning-to-explicit-budget"],
  inherit=None, caveat="Dual-locator record (V4.1 card + Qwen card readings group); effort semantics differ per vendor (1-100 numeric vs tiers).",
  claims=[
    ("V4.1 exposes numeric reasoning effort 1-100 with penalty tables; Qwen exposes enable_thinking/reasoning_effort tiers — explicit-budget class controls in production interfaces.", "PROJECT_CLAIM", "Interface facts; V4.1 numeric semantics corroborated by consumed D163 recipe (effort mapping, max-tokens interaction)."),
    ("Effort 60-80 recovers most of effort-100 accuracy at well under half the tokens per the V4.1 report lineage, the production form of the overthinking finding.", "AUTHOR_CLAIM", "Report-lineage figure via D163 recipe context; workload-bound.")],
  limits=["Card/interface pages not fetched separately; Qwen-side tier semantics at summary level."],
  ver={"@FULL": ("VERIFIED", "Effort-control role corroborated via consumed D163 (numeric effort, mapping tables, budget-room warnings); card bodies outstanding.")}),
"D154": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Cascade origin: scoring + router + stop judge; up to 98% saving; sequential-latency limitation; stale prices.",
  entity=("frugalgpt-2023", "FrugalGPT: How to Use Large Language Models While Reducing Cost and Improving Performance (Chen et al., 2023)", "PAPER", "Stanford"),
  artifact="PAPER", lineage="CORE", branches=["model-routing"], transitions=["single-model-to-cascade"],
  inherit=None, caveat="98% savings and price figures are 2023-API-bound; cascade latency (sequential calls) limits the headline.",
  claims=[
    ("FrugalGPT learns query-dependent LLM combinations (prompt adaptation, approximation, cascade with scoring/router/stop-judge), reporting up to 98% cost saving at matched accuracy on 2023 APIs.", "PRIMARY_FACT", "Headline method + figures; abstract consumed (2305.05176)."),
    ("Sequential cascade latency is the structural limitation motivating single-query routing (RouteLLM) as the alternative.", "INFERENCE", "Limitation-driven linkage to D155.")],
  limits=["Full-body cascade-optimization analysis not consumed; prices stale by construction."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2305.05176): cascade method + 98% figure confirmed; full body outstanding.")}),
"D155": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Single-query weak/strong routing; PGR/CPT; 2x+ savings; unseen-pair transfer; training-data staleness limit.",
  entity=("routellm-2024", "RouteLLM: Learning to Route LLMs with Preference Data (Ong et al., 2024)", "PAPER", "Berkeley/LMSYS"),
  artifact="PAPER", lineage="CORE", branches=["model-routing"], transitions=["cascade-to-single-query-routing"],
  inherit=None, caveat="Router-training data staleness bounds transfer claims; 2x+ savings are benchmark-bound.",
  claims=[
    ("RouteLLM trains efficient routers on preference data (PGR/CPT methods) to select per-query between strong and weak LLMs, reporting 2x+ cost savings without quality loss plus unseen-pair transfer.", "PRIMARY_FACT", "Headline method + figures; abstract consumed (2406.18665)."),
    ("Preference-data staleness is the router-generalization limit that the fragility analysis (D157) later systematizes.", "INFERENCE", "Limitation linkage.")],
  limits=["Full-body router-training and transfer tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2406.18665): preference-data routing + 2x figure confirmed; full body outstanding.")}),
"D156": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="2026 routing/cascading survey: secondary unifier; follow-up pool, not primary authority.",
  entity=("routing-survey-2026", "Dynamic Model Routing and Cascading for Efficient LLM Inference: A Survey (2026)", "PAPER", "Independent"),
  artifact="PAPER", lineage="CONTEXT", branches=["model-routing"], transitions=["methods-to-taxonomy"],
  inherit=None, caveat="Secondary-by-design; routing-vs-cascading-vs-cascade-routing taxonomy use only.",
  claims=[
    ("The survey unifies multi-LLM routing/cascading paradigms (query difficulty, preferences, clustering, uncertainty, RL) with quality estimation as the critical component.", "AUTHOR_CLAIM", "Taxonomy facts; abstract consumed (2603.04445, pub 2026-02-23)."),
    ("Survey-referenced primary follow-ups are pooled for Sol, not consumed as findings.", "INFERENCE", "Use boundary.")],
  limits=["Survey body not consumed; follow-up pool untouched."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2603.04445): routing/cascading taxonomy confirmed; survey body outstanding."),
        "primary follow-ups": ("UNRESOLVED", "Follow-up primaries not pursued; deferred to Sol gap-fill judgment.")}),
"D157": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Limitation evidence: preference routers fragile under shift; gains conditional on router-task alignment.",
  entity=("router-fragility-2026", "Router-LLM fragility analysis (EACL 2026 Findings)", "PAPER", "EACL 2026"),
  artifact="PAPER", lineage="COUNTEREXAMPLE", branches=["model-routing"], transitions=["routing-optimism-to-fragility"],
  inherit=None, caveat="Findings paper (non-arXiv locator); fragility conditions are setup-bound.",
  claims=[
    ("Preference-based routers prove fragile under distribution shift; routing gains hold only conditional on router-task alignment.", "AUTHOR_CLAIM", "Headline limitation finding; summary-level (ACL Findings venue)."),
    ("Fragility is the counterexample that keeps the routing lane honest: D154/D155 savings claims require alignment conditions attached.", "INFERENCE", "Counterexample role.")],
  limits=["Paper body not consumed; fragility conditions at summary level."],
  ver={"@FULL": ("VERIFIED", "Fragility finding recorded at summary level; paper body outstanding.")}),
"D162": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Accepted X r3 ledger: 27 direct observations as practitioner reception/deployment/friction signal; X_OBSERVATION boundary preserved.",
  entity=("x-reception-r3-ledger", "Accepted X reception ledger r3 (27 direct observations, 24 accounts, 20 independent)", "ORGANIZATION", "X community (Grok-curated, Sol-reviewed)"),
  artifact="OTHER", lineage="CONTEXT", branches=["local-inference", "inference-serving", "specialization-jeff", "capstone-2026-v41", "benchmark-methodology"], transitions=["lab-claim-to-field-reception"],
  inherit=None, caveat="X corpus supports reception/friction statements only; never architecture, scores, prices, licenses, or causal performance claims.",
  claims=[
    ("Practitioners report local deployment feasibility with offload/RAM/bandwidth as the practical bottlenecks; quantization choice and runtime maturity dominate usability reports.", "SOCIAL_OBSERVATION", "Reception-level synthesis of the 27-observation ledger; configuration-bound."),
    ("Early runtime support for 2026 capstones and early independent Jev experimentation are reported; Jev production-failure evidence remains LOW_SIGNAL.", "SOCIAL_OBSERVATION", "Reception facts with explicit low-signal qualifier."),
    ("Self-reported hardware measurements (e.g., 325 tok/s-class claims, 1.6-3.4x multipliers) are configuration-bound observations, not verified facts.", "SOCIAL_OBSERVATION", "Boundary restatement from screening package.")],
  limits=["Raw X corpus imported as ledger record; per-observation verification not performed and not claimed.", "No technical, economic, or license fact is sourced to this record."],
  ver={"@FULL": ("VERIFIED", "Ledger acceptance (Sol r3 PASS, 27/27/24/20 counts, SHA-verified raw bytes) confirmed; reception-role claims bound to the ledger."),
        "X boundary into Evidence": ("VERIFIED", "X_OBSERVATION boundary preserved into claims/limitations; prohibited fact classes excluded.")}),
"D163": dict(status="VERIFIED", mat="MATERIAL",
  mat_rationale="vLLM DeepSeek-V4.1-Flash recipe: runtime-maintainer authority fully consumed; version floor, DSpark/MTP distinction, hardware conditions verified.",
  entity=("vllm-v41-recipe", "vLLM DeepSeek-V4.1-Flash recipe (deployment authority)", "ORGANIZATION", "vLLM Project"),
  artifact="FRAMEWORK", lineage="CORE", branches=["decoding-acceleration", "inference-serving", "capstone-2026-v41"], transitions=["release-to-runnable-recipe"],
  inherit=None, caveat="Recipe-validated configurations only; scheduler limits workload-dependent; nightly-image drift bounds benchmark reuse.",
  claims=[
    ("Maintainer recipe authority: vLLM 0.30.0+ floor (Docker only, no pip wheel; main PR #56228, nightly from 2026-09-10); 552B backbone + 196.6B Engram; 8B-prefill/16B-decode CED; two-tier sparse attention (128-token SWA + indexer-selected 512, only layers 2/8/14/20 compress); MXFP4 experts / MXFP8 dense / BF16 embeddings.", "PROJECT_CLAIM", "Recipe page fully consumed this pass (recipes.vllm.ai, updated 2026-09-20)."),
    ("DSpark is the only speculative method (5-token blocks, Markov bias + confidence heads, ~14B drafter); V4.1 dropped the MTP module. On AMD, vLLM refuses adaptive verification (two failed checks: CPU-query-lens mismatch unsupported, ROCm backend UNIFORM_BATCH); the recipe pins enable_adaptive_verification:false with full-block verification.", "PROJECT_CLAIM", "DSpark/MTP distinction and AMD conditions per recipe; do not generalize to other stacks."),
    ("Reasoning effort is numeric 1-100 (low25/high50/xhigh75/max100 in vLLM mapping vs API 50/75/100); default-on at effort 50 with small max_tokens reads as breakage (empty content, finish_reason=length) — a deployment-behavior fact.", "PROJECT_CLAIM", "Effort semantics + failure-mode documentation per recipe."),
    ("Verified layouts: 1P1D disaggregation on GB200 NVL4 (TP4 pools, NIXL KV handoff, max-num-seqs 32); TP2+Engram-CPU-offload on Blackwell/H200/MI355X with per-SKU overrides; FlashInfer autotune/JIT/CuTeDSL and DeepGEMM warmup disabled; KV offload validated on 4xH200 (TieringOffloadingSpec, GSM8K 31/32 diagnostic, small-sample).", "PROJECT_CLAIM", "Layout facts with validation scope; benchmark config (InferenceX #3058, golden acceptance 3.51) is pinned-config evidence only.")],
  limits=["Recipe is living documentation (nightly drift); pinned-config validation does not transfer to other images or scheduler caps.", "Throughput-mode synthetic acceptance is measurement-only; EVAL_ONLY=true (real rejection) governs serving."],
  ver={"@FULL": ("VERIFIED", "Recipe page fully consumed: version floor, CED/attention/Engram/precision/effort/layout/offload sections extracted."),
        "recipe/version conditions": ("VERIFIED", "0.30.0+ floor, DSpark-only/MTP-dropped distinction, AMD refusal conditions, per-SKU overrides all confirmed from maintainer bytes.")}),
"D164": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Unsloth GLM-5.3-Flash packaging authority fully consumed; GGUF/memory-fit/runtime-path facts verified, speed multipliers quarantined.",
  entity=("unsloth-glm53-docs", "Unsloth GLM-5.3-Flash local quantization authority (GGUF table, memory-fit guidance)", "ORGANIZATION", "Unsloth"),
  artifact="PRODUCT", lineage="CORE", branches=["precision-quantization", "local-inference", "capstone-2026-v41"], transitions=["release-to-local-quant"],
  inherit=None, caveat="Packaging/runtime authority only; speed multipliers and benchmark tables are vendor-measured and quarantined.",
  claims=[
    ("GGUF availability confirmed: UD-IQ1_S 1-bit 93.09GB through BF16 ~642GB with per-quant top-1/KLD table (1-bit 70.89% top-1, 85% smaller; 3-bit 120GB/81.6%, 4-bit 200GB/92.2%); memory-fit guidance 1-bit ~100GB RAM, 3-bit 128-150GB; llama.cpp + Unsloth Desktop paths with UD-IQ3_XXS demo default.", "PROJECT_CLAIM", "Docs page fully consumed this pass (unsloth.ai/docs/models/glm-5.3-flash); 320B/18B ox-alpha identity, 30T tokens, 1M context, Low/High/Max thinking, temp 1.0/top-p 0.95."),
    ("MTP support implemented in the Unsloth llama.cpp fork (PR unslothai/llama.cpp#61 branch glm5next/upstream; distinct from ggml-org PR 27742 for Qwen); 3.3x-faster-inference claim is vendor-measured (B200 UD-IQ1_S tok/s table, n=2 MTP best) and requires independent confirmation.", "PROJECT_CLAIM", "Implementation existence confirmed; speedup figures quarantined."),
    ("Vendor benchmark table (Terminal-Bench 2.1 84.3, DeepSWE v1.1 63.4, Toolathlon 78.4 vs Opus 4.8/GPT-5.6 Terra/Gemini 3.7 Flash) is harness-bound vendor reporting, cited for no fact.", "VENDOR_CLAIM", "Table quarantined in full.")],
  limits=["GGUF quality figures (top-1/KLD) are Unsloth-measured; independent quantization-quality verification outstanding.", "llama.cpp fork PR contents not audited beyond the docs' description."],
  ver={"@FULL": ("VERIFIED", "Docs page fully consumed: GGUF table, memory-fit, runtime paths, MTP/fork, benchmarks extracted with boundaries."),
        "MTP claim independence": ("UNRESOLVED", "MTP speedup figures vendor-measured only; independent confirmation outstanding.")}),
"D165": dict(status="VERIFIED", mat="MATERIAL",
  mat_rationale="llama.cpp Qwen3.8-Flash-Next port (merged PR 27742): implementation authority fully consumed; QSA/PLE/host-memory/validation/gaps verified.",
  entity=("llamacpp-qwen38-pr", "llama.cpp Qwen3.8-Flash-Next implementation port (merged PR 27742)", "ORGANIZATION", "ggml-org/Unsloth"),
  artifact="FRAMEWORK", lineage="CORE", branches=["attention-kv", "local-inference", "capstone-2026-v41"], transitions=["reference-to-community-port"],
  inherit=None, caveat="Port-validation figures are fixture-bound (tiny fixtures, single-model comparisons); known gaps documented on-PR, not hidden.",
  claims=[
    ("Merged implementation authority: PR ggml-org/llama.cpp#27742 (Unsloth-authored danielhanchen, merged 2026-08-27 by ngxson, 65 commits) adds qwen4exp arch: converter, GDN text graph with low-rank hyper-connections, MoE 512-expert top-10, QSA sparse attention (budget 2048, ratio 4), host-side PLE n-gram hash (97.7GiB table, 128 shards, splitmix64 2^45 host hashing), stock Qwen3-VL ViT path.", "PROJECT_CLAIM", "PR page fully consumed this pass (conversation + commit messages)."),
    ("Validation method: wikitext-2 ppl 4.0068 vs 4.0126 reference, 98.0% top-1 prose agreement, QSA-vs-dense bit-identical below budget with 0.975 mean jaccard above, PLE row indices 1024/1024, chunked-prefill bit-identity, test-llama-archs 126 archs green.", "PROJECT_CLAIM", "PR-reported validation; fixture-bound as stated on-PR."),
    ("Known implementation gaps documented: PLE conv state across ubatches fixed in-PR with bit-identity proof; test-llama-archs qwen4exp skip resolved (saver uint64 path + key re-emission); quantized-model (UD-IQ1_S) logit delta 2.84e-03 non-identical; shared-file changes additive-only with A/B md5s.", "PROJECT_CLAIM", "Gap transparency per PR discussion; AI-usage disclosure (Claude + local models, manual verification) noted.")],
  limits=["Port correctness rests on PR-reported validation; no independent rebuild or measurement performed.", "Host-side PLE memory behavior (97.7GiB table, streaming converter, ~300GB RSS peak avoided) is implementation-described."],
  ver={"@FULL": ("VERIFIED", "PR page fully consumed: merged status, QSA/PLE support, host-side memory behavior, validation method, known gaps extracted.")}),
}
