"""Evidence record specs Part B: D033-D071 (decoding, quantization, local inference, serving systems, distillation, Jev core)."""
PART_B = {
"D033": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Speculative-decoding co-origin: draft/verify, lossless, no target retraining; acceptance-rate-governed speedup.",
  entity=("leviathan-spec-decoding-2023", "Fast Inference from Transformers via Speculative Decoding (Leviathan et al., 2023)", "PAPER", "Google"),
  artifact="PAPER", lineage="CORE", branches=["decoding-acceleration"], transitions=["autoregressive-to-draft-verify"],
  inherit=None, caveat="Joint invention with Chen et al. (D034); single-origin attribution prohibited.",
  claims=[
    ("Leviathan et al. define draft-then-verify speculative decoding that preserves the target distribution (lossless) without retraining the target model, with speedup governed by draft acceptance rate.", "PRIMARY_FACT", "Headline mechanism + guarantees; abstract-level."),
    ("Acceptance-rate dependence is the durable analytic frame for all later draft-head work (EAGLE, Medusa, MTP, DSpark).", "INFERENCE", "Taxonomic role.")],
  limits=["Full-body acceptance-criterion proofs and speedup tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2211.17192): lossless draft/verify mechanism confirmed; full body outstanding.")}),
"D034": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Co-origin with acceptance-criterion formalism; joint invention attribution.",
  entity=("chen-spec-sampling-2023", "Accelerating Large Language Model Decoding with Speculative Sampling (Chen et al., 2023)", "PAPER", "Google DeepMind"),
  artifact="PAPER", lineage="CORE", branches=["decoding-acceleration"], transitions=["autoregressive-to-draft-verify"],
  inherit=None, caveat="Joint invention with Leviathan et al. (D033); single-origin attribution prohibited.",
  claims=[
    ("Chen et al. formalize speculative sampling with the acceptance criterion guaranteeing target-distribution preservation, the joint co-origin of the field with D033.", "PRIMARY_FACT", "Formalism contribution; abstract-level."),
    ("The acceptance-criterion formalism is what later lets Medusa/EAGLE relax greediness in a controlled way.", "INFERENCE", "Lineage linkage to D035-D037.")],
  limits=["Full-body proofs and benchmark tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2302.01318): acceptance-criterion formalism confirmed; full body outstanding.")}),
"D035": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Multi-head drafts + tree verification on frozen backbone; non-greedy losslessness qualification.",
  entity=("medusa-2024", "Medusa: Simple LLM Inference Acceleration Framework with Multiple Decoding Heads (Cai et al., 2024)", "PAPER", "Princeton/UIUC"),
  artifact="PAPER", lineage="CORE", branches=["decoding-acceleration"], transitions=["draft-model-to-draft-head"],
  inherit=None, caveat="Losslessness holds for greedy decoding; non-greedy modes carry the paper's own qualification.",
  claims=[
    ("Medusa adds lightweight multi-head draft outputs plus tree-based verification to a frozen backbone, removing the separate draft model.", "PRIMARY_FACT", "Headline mechanism; abstract-level."),
    ("Greedy-mode losslessness is preserved; non-greedy generation quality follows the paper's qualified scope, not blanket losslessness.", "AUTHOR_CLAIM", "Scope qualification from the paper's framing.")],
  limits=["Full-body tree-construction and speedup tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2401.10774): multi-head draft + tree verification confirmed; full body outstanding."),
        "losslessness scope": ("VERIFIED", "Greedy vs non-greedy scope distinction recorded from the paper's framing.")}),
"D036": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Feature-level autoregressive drafts + tree attention; lossless; 2.7-3.5x at 70B; inspired V3 MTP use.",
  entity=("eagle-2024", "EAGLE: Speculative Sampling Requires Rethinking Feature Uncertainty (ICML'24)", "PAPER", "Independent/SJTU"),
  artifact="PAPER", lineage="CORE", branches=["decoding-acceleration"], transitions=["token-draft-to-feature-draft"],
  inherit=None, caveat="Speedup figures are setup-bound (70B, harness); the feature-uncertainty mechanism is the durable claim.",
  claims=[
    ("EAGLE drafts at the feature level autoregressively with tree attention, reporting 2.7-3.5x speedups at 70B scale while preserving the target distribution.", "PRIMARY_FACT", "Mechanism + headline numbers; abstract-level."),
    ("EAGLE's feature-draft design directly inspires the MTP-as-decoding reuse path taken up by the DeepSeek V-line.", "AUTHOR_CLAIM", "Influence claim; corroborated by V3 MTP adoption (D006).")],
  limits=["Full-body uncertainty analysis and benchmark setups not consumed; speedup numbers setup-bound."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2401.15077): feature-level draft + tree attention confirmed; full body outstanding.")}),
"D037": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Context-dependent acceptance to dynamic trees; 2.5-5x; acceptance-rate science.",
  entity=("eagle2-2024", "EAGLE-2: Faster Inference with Dynamic Draft Trees (2024)", "PAPER", "Independent/SJTU"),
  artifact="PAPER", lineage="CORE", branches=["decoding-acceleration"], transitions=["static-to-dynamic-trees"],
  inherit=None, caveat=None,
  claims=[
    ("EAGLE-2 makes draft trees dynamic via context-dependent acceptance modeling, reporting 2.5-5x speedups.", "PRIMARY_FACT", "Headline mechanism + numbers; abstract-level."),
    ("Dynamic-tree acceptance modeling is the acceptance-rate science that DSpark-style confidence verification later operationalizes per workload.", "INFERENCE", "Lineage linkage to D040/D163.")],
  limits=["Full-body acceptance-model details and tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2406.16858): dynamic draft trees confirmed; full body outstanding.")}),
"D038": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="MTP as training objective vs decoding use; mechanism reused by 2026 capstones.",
  entity=("mtp-gloeckle-2024", "Better & Faster Large Language Models via Multi-token Prediction (Gloeckle et al., 2024)", "PAPER", "Meta FAIR"),
  artifact="PAPER", lineage="CORE", branches=["decoding-acceleration", "scaling-training"], transitions=["next-token-to-multi-token"],
  inherit=None, caveat="Training-objective MTP and decoding-use MTP are distinct deployments of one mechanism; conflation prohibited.",
  claims=[
    ("Gloeckle et al. show multi-token prediction as an auxiliary training objective improving capability and enabling self-speculative decoding use.", "PRIMARY_FACT", "Dual-role finding; abstract-level."),
    ("The objective-vs-use distinction structures the Special's treatment: V3 trains MTP as objective, V4.1 drops the MTP module for DSpark, GLM retains MTP acceptance gains.", "INFERENCE", "Cross-capstone synthesis grounded in D006/D123/D129.")],
  limits=["Full-body objective-weighting ablations not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2404.19737): MTP objective + decoding-use duality confirmed; full body outstanding.")}),
"D039": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Target-native MTP needs no separate draft; GLM-5.3-Flash DeepSeek-style MTP deployment path.",
  entity=("vllm-mtp-docs", "vLLM speculative decoding with Multi-Token Prediction (documentation)", "ORGANIZATION", "vLLM Project"),
  artifact="FRAMEWORK", lineage="BRIDGE", branches=["decoding-acceleration", "inference-serving"], transitions=["paper-to-deployment"],
  inherit=None, caveat="Docs describe supported paths, not measured speedups; acceptance remains workload-dependent.",
  claims=[
    ("vLLM documents target-native MTP speculative decoding in which the model's own MTP layers draft, requiring no separate draft model.", "PROJECT_CLAIM", "Documentation-level; consistent with D129 GLM MTP deployment matrix."),
    ("The documented path is the deployment vehicle for GLM-5.3-Flash DeepSeek-style MTP serving.", "INFERENCE", "Linkage corroborated by D052/D129.")],
  limits=["Docs page body not fetched; claims scoped to Discovery summary with downstream corroboration."],
  ver={"@FULL": ("VERIFIED", "Documented-path role corroborated via D052/D129 deployment records; page body outstanding."),
        "runtime version binding": ("UNRESOLVED", "Exact doc revision / supported-version floor not pinned from this page.")}),
"D040": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Semi-autoregressive draft + confidence verification; in-checkpoint drafter; no standalone paper.",
  entity=("dspark-bundle", "DSpark evidence bundle (vLLM deepseek_v41 docs + Dynamo recipe)", "PRODUCT", "DeepSeek-AI/vLLM/NVIDIA"),
  artifact="FRAMEWORK", lineage="CORE", branches=["decoding-acceleration", "capstone-2026-v41"], transitions=["mtp-module-to-dspark"],
  inherit=None, caveat="No standalone DSpark paper exists; all claims rest on implementation + recipe documentation, fully consumed via D163.",
  claims=[
    ("DSpark drafts 5-token blocks semi-autoregressively (3 stages x 128 routed experts, Markov bias + confidence heads) with in-checkpoint drafter weights (~14B) and adaptive verification on NVIDIA.", "PROJECT_CLAIM", "Implementation facts fully consumed via the D163 recipe page."),
    ("V4.1 drops the V3/V4-trained MTP module; DSpark is the only speculative method for the checkpoint, a deliberate architecture substitution.", "PROJECT_CLAIM", "Substitution fact per D163; corroborated by D123 abstract's DSpark-era framing.")],
  limits=["No paper-grade ablations exist; acceptance numbers are workload-measured only (InferenceX golden 3.51 in benchmark config)."],
  ver={"@FULL": ("VERIFIED", "DSpark mechanism fully consumed via D163 recipe page (incl. NVIDIA adaptive-verification vs AMD refusal hardware conditions); no paper body outstanding because none exists.")}),
"D041": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Outlier-aware decomposition; 100B+ inference on constrained memory; outlier framing origin.",
  entity=("llm-int8-2022", "LLM.int8(): 8-bit Matrix Multiplication for Transformers at Scale (Dettmers et al., 2022)", "PAPER", "University of Washington"),
  artifact="PAPER", lineage="CORE", branches=["precision-quantization"], transitions=["fp16-to-int8-outlier-aware"],
  inherit=None, caveat=None,
  claims=[
    ("LLM.int8() separates emergent outlier feature dimensions into FP16 while computing the rest in INT8, enabling 100B+ inference on constrained memory.", "PRIMARY_FACT", "Headline mechanism + scale claim; abstract-level."),
    ("Outlier-aware decomposition founds the activation-outlier framing reused by SmoothQuant and AWQ.", "INFERENCE", "Lineage synthesis to D043/D044.")],
  limits=["Full-body outlier-emergence analysis and benchmark tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2208.07339): outlier-aware INT8 decomposition confirmed; full body outstanding.")}),
"D042": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="One-shot weight-only PTQ via second-order information; 3-4 bit with small perplexity cost.",
  entity=("gptq-2022", "GPTQ: Accurate Post-Training Quantization for Generative Pre-trained Transformers (Frantar et al., 2022)", "PAPER", "IST Austria"),
  artifact="PAPER", lineage="CORE", branches=["precision-quantization"], transitions=["retraining-to-one-shot-ptq"],
  inherit=None, caveat=None,
  claims=[
    ("GPTQ performs one-shot weight-only post-training quantization using approximate second-order (Hessian) information, reaching 3-4 bit weights at small perplexity cost.", "PRIMARY_FACT", "Headline mechanism + bit-width claim; abstract-level."),
    ("GPTQ defines the weight-only PTQ class separated from weight+activation (SmoothQuant) and QAT/native-low-bit classes in the Special's taxonomy.", "INFERENCE", "Taxonomic role.")],
  limits=["Full-body layer-wise error analysis not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2210.17323): one-shot second-order PTQ confirmed; full body outstanding.")}),
"D043": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Activation-to-weight difficulty migration enabling W8A8; weight+activation class.",
  entity=("smoothquant-2022", "SmoothQuant: Accurate and Efficient Post-Training Quantization for Large Language Models (Xiao et al., 2022)", "PAPER", "MIT/Hugging Face"),
  artifact="PAPER", lineage="CORE", branches=["precision-quantization"], transitions=["weight-only-to-w8a8"],
  inherit=None, caveat=None,
  claims=[
    ("SmoothQuant migrates activation quantization difficulty into weights via per-channel smoothing, enabling INT8 weight+activation quantization without retraining.", "PRIMARY_FACT", "Headline mechanism; abstract-level."),
    ("The migration idea is the canonical W8A8 path distinct from GPTQ/AWQ weight-only approaches.", "INFERENCE", "Taxonomic distinction.")],
  limits=["Full-body smoothing-factor derivations and tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2211.10438): difficulty-migration mechanism confirmed; full body outstanding.")}),
"D044": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Salient-weight protection; strong 4-bit weight-only with tiny calibration.",
  entity=("awq-2023", "AWQ: Activation-aware Weight Quantization for On-Device LLM Compression and Acceleration (Lin et al., 2023)", "PAPER", "MIT"),
  artifact="PAPER", lineage="CORE", branches=["precision-quantization"], transitions=["uniform-to-salience-aware-ptq"],
  inherit=None, caveat=None,
  claims=[
    ("AWQ protects salient weights identified via activation statistics, achieving strong 4-bit weight-only quantization from tiny calibration sets.", "PRIMARY_FACT", "Headline mechanism + data-efficiency claim; abstract-level."),
    ("Salience-aware protection is the PTQ branch most directly continued by importance-matrix/mixed-quantization practice in local inference (llama.cpp k-quants).", "INFERENCE", "Lineage linkage to D050.")],
  limits=["Full-body salience analysis and on-device tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2306.00978): activation-aware salient-weight mechanism confirmed; full body outstanding.")}),
"D045": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="4-bit frozen base + LoRA adapters; quantization/adaptation interaction.",
  entity=("qlora-2023", "QLoRA: Efficient Finetuning of Quantized LLMs (Dettmers et al., 2023)", "PAPER", "University of Washington"),
  artifact="PAPER", lineage="CORE", branches=["precision-quantization", "distillation-adaptation"], transitions=["full-finetune-to-quantized-adaptation"],
  inherit=None, caveat=None,
  claims=[
    ("QLoRA combines 4-bit NormalFloat quantization of a frozen base with low-rank adapters, making large-model fine-tuning accessible on single GPUs.", "PRIMARY_FACT", "Headline mechanism + accessibility claim; abstract-level."),
    ("QLoRA is the interaction point of the quantization and adaptation lanes: precision choice directly conditions fine-tuning efficiency.", "INFERENCE", "Cross-lane synthesis.")],
  limits=["Full-body optimizer/memory analysis not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2305.14314): 4-bit frozen base + adapters confirmed; full body outstanding.")}),
"D046": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="One-shot 50-60% pruning via OBS solver family; bounds the no-retraining half.",
  entity=("sparsegpt-2023", "SparseGPT: Massive Language Models Can Be Accurately Pruned in One-Shot (Frantar & Alistarh, 2023)", "PAPER", "IST Austria"),
  artifact="PAPER", lineage="CORE", branches=["precision-quantization", "distillation-adaptation"], transitions=["retrain-pruning-to-one-shot"],
  inherit=None, caveat="One-shot unstructured sparsity needs sparse-kernel/hardware support to convert to wall-clock gains; sparsity percentage alone is not speedup.",
  claims=[
    ("SparseGPT prunes LLMs to 50-60% unstructured sparsity in one shot without retraining via the Optimal Brain Surgeon solver family.", "PRIMARY_FACT", "Headline sparsity + no-retraining claims; abstract-level."),
    ("SparseGPT bounds the no-retraining half of the pruning story; the recovery-pipeline half (retraining after pruning) remains thin, which is why Wanda's metric-only role was dropped.", "INFERENCE", "Screening-rationale linkage (D161).")],
  limits=["Full-body OBS solver derivations and perplexity tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2301.00774): one-shot 50-60% pruning confirmed; full body outstanding.")}),
"D047": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Native 1-bit training direction; industrial adoption beyond MSR is gap-fill.",
  entity=("bitnet-2023", "BitNet: Scaling 1-bit Transformers for Large Language Models (Wang et al., 2023)", "PAPER", "Microsoft Research"),
  artifact="PAPER", lineage="CORE", branches=["precision-quantization"], transitions=["ptq-to-native-low-bit"],
  inherit=None, caveat="Native-training claims vs PTQ-fitted claims must keep distinct evidence classes (defined vs fitted).",
  claims=[
    ("BitNet trains 1-bit (binary) Transformers natively with scaling behavior competitive with full precision, opening the native-low-bit training direction.", "PRIMARY_FACT", "Headline direction + scaling claim; abstract-level."),
    ("Industrial deployment of native 1-bit beyond Microsoft remains open; the Special treats BitNet as direction evidence, not deployment evidence.", "INFERENCE", "Adoption-status boundary.")],
  limits=["Full-body training-stability analysis not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2310.11453): native 1-bit training direction confirmed; full body outstanding."),
        "adoption status": ("UNRESOLVED", "Non-MSR industrial adoption not confirmed this pass; recorded as open, not as negative.")}),
"D048": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Container format + tensor layout + metadata + mmap; NOT a quantization algorithm.",
  entity=("gguf-spec", "GGUF specification (ggml project)", "PRODUCT", "ggml/llama.cpp project"),
  artifact="FRAMEWORK", lineage="CORE", branches=["precision-quantization", "local-inference"], transitions=["ggml-to-gguf"],
  inherit=None, caveat="GGUF is a storage/runtime container; calling it a quantization algorithm is a category error the Special explicitly prohibits.",
  claims=[
    ("GGUF specifies the container format, tensor layout, metadata schema, and mmap-able loading used by the local-inference ecosystem.", "PROJECT_CLAIM", "Spec-role level; spec page not fetched line-level."),
    ("Quantization families stored in GGUF (k-quants, Unsloth dynamics) are algorithms applied to tensors, not properties of GGUF itself.", "INFERENCE", "Category boundary central to EFF-O06.")],
  limits=["Spec page not fetched; claims scoped to established role + D050/D164 corroboration."],
  ver={"@FULL": ("VERIFIED", "Container-vs-algorithm role corroborated via D050/D164 consumption; spec body outstanding.")}),
"D049": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="FP4 MXFP4 experts serving-critical in 2026, B200-conditional; expert_dtype dispatch.",
  entity=("mxfp4-deployment-evidence", "MXFP4/FP4-expert deployment evidence (V4 line + vLLM dispatch)", "PRODUCT", "DeepSeek-AI/vLLM"),
  artifact="FRAMEWORK", lineage="CORE", branches=["precision-quantization", "capstone-2026-v41"], transitions=["fp8-to-mxfp4"],
  inherit=None, caveat="FP4 expert paths are B200-class conditional; format authority is the OCP MX spec (D136), not this record.",
  claims=[
    ("MXFP4 (E2M1 microscaling, 4.25 bits with scale) experts are serving-critical in the 2026 V4-line, dispatched per-expert via expert_dtype paths.", "PROJECT_CLAIM", "Deployment facts fully corroborated by consumed D163 recipe (MXFP4 routed experts, UE8M0 scales, B200 paths)."),
    ("The MXFP4/MXFP8 checkpoint split (FP4 experts, MXFP8 dense, BF16 embeddings/head) is the concrete native-low-bit deployment instance.", "PROJECT_CLAIM", "Checkpoint composition per D163.")],
  limits=["vLLM dispatch code not audited; claims rest on recipe documentation."],
  ver={"@FULL": ("VERIFIED", "FP4-expert deployment facts consumed via D163 recipe page; dispatch code audit outstanding."),
        "hardware conditions": ("VERIFIED", "B200-class conditionality for FP4 expert paths confirmed via D163; no cross-hardware generalization.")}),
"D050": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Reference local-inference implementation for the D07 lane.",
  entity=("llama-cpp", "llama.cpp (GGML history, GGUF runtime, k-quants, CPU/GPU split)", "PRODUCT", "ggml-org community"),
  artifact="FRAMEWORK", lineage="CORE", branches=["local-inference", "precision-quantization"], transitions=["datacenter-to-local"],
  inherit=None, caveat="Codebase not audited; cited as reference implementation, not certified-correct oracle.",
  claims=[
    ("llama.cpp is the reference local-inference implementation carrying GGML history, the GGUF runtime, k-quant families, and CPU/GPU split execution.", "PROJECT_CLAIM", "Project-role level; corroborated by D164/D165 consumption of its PRs and docs."),
    ("Its Qwen3.8 port (PR 27742) and GLM fork PR demonstrate the project's role as day-zero local-deployment vehicle for 2026 MoE capstones.", "PROJECT_CLAIM", "Port facts per consumed D165 PR page and D164 docs.")],
  limits=["Codebase not cloned or audited; implementation-correctness claims rest on PR-page validation reports."],
  ver={"@FULL": ("VERIFIED", "Reference-implementation role corroborated via consumed D164/D165 pages; code audit outstanding."),
        "version/content binding at Evidence": ("UNRESOLVED", "No version pin extracted; project is continuously developed, binding deferred.")}),
"D051": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Expert-offload answer to weight-capacity vs active-compute question.",
  entity=("ktransformers", "KTransformers (heterogeneous CPU/GPU MoE execution)", "PRODUCT", "kvcache-ai community"),
  artifact="FRAMEWORK", lineage="BRIDGE", branches=["local-inference", "conditional-compute-moe"], transitions=["gpu-only-to-heterogeneous-moe"],
  inherit=None, caveat="Repo not audited; offload-mechanism claims at project-description level.",
  claims=[
    ("KTransformers executes MoE with heterogeneous CPU/GPU placement and expert offload, answering the huge-total/low-active weight-memory problem for local deployment.", "PROJECT_CLAIM", "Project-role level; consistent with Qwen/GLM deployment matrices (D127/D129)."),
    ("Heterogeneous execution separates weight-capacity from active-compute, the D07 thesis instance.", "INFERENCE", "Editorial synthesis.")],
  limits=["Repository not fetched; mechanism details at description level."],
  ver={"@FULL": ("VERIFIED", "Heterogeneous-offload role corroborated via capstone deployment matrices; repo body outstanding."),
        "version/content binding at Evidence": ("UNRESOLVED", "No version pin extracted.")}),
"D052": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="320B/18B quantized serving; MTP speculative config; tool/reasoning parsers.",
  entity=("vllm-ascend-glm53-tutorial", "vLLM Ascend GLM-5.3-Flash deployment tutorial", "ORGANIZATION", "vLLM Ascend project"),
  artifact="FRAMEWORK", lineage="CORE", branches=["local-inference", "inference-serving", "capstone-2026-glm"], transitions=["nvidia-only-to-ascend"],
  inherit=None, caveat="Ascend/NPU path conditions do not transfer to CUDA/ROCm stacks.",
  claims=[
    ("The Ascend tutorial documents quantized GLM-5.3-Flash (320B/18B) serving with MTP speculative configuration and tool/reasoning parsers.", "PROJECT_CLAIM", "Tutorial-role level; MTP/quantization corroborated by D129/D164."),
    ("NPU-backend coverage proves the GLM deployment matrix extends beyond CUDA, material to the serving-systems lane.", "INFERENCE", "Coverage significance.")],
  limits=["Tutorial page not fetched; claims scoped to Discovery summary with corroboration."],
  ver={"@FULL": ("VERIFIED", "Tutorial role and MTP/quantization facts corroborated via D129/D164; page body outstanding."),
        "tutorial/model-version binding": ("UNRESOLVED", "Exact tutorial-to-checkpoint version pin not extracted.")}),
"D053": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Paged KV blocks kill fragmentation; continuous batching; serving-system origin.",
  entity=("pagedattention-vllm-2023", "Efficient Memory Management for LLM Serving with PagedAttention (Kwon et al., SOSP'23)", "PAPER", "Berkeley/Sky Lab"),
  artifact="PAPER", lineage="CORE", branches=["inference-serving"], transitions=["contiguous-kv-to-paged-kv"],
  inherit=None, caveat=None,
  claims=[
    ("PagedAttention manages KV cache in non-contiguous blocks, eliminating fragmentation and enabling continuous batching at high throughput.", "PRIMARY_FACT", "Headline mechanism + effects; abstract-level."),
    ("Block-level KV management is the memory-management substrate on which prefix caching, disaggregation, and offload later build.", "INFERENCE", "Substrate significance for D113/D114/D059-D061.")],
  limits=["Full-body block-table design and throughput tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2309.06180): paged KV + continuous batching confirmed; full body outstanding.")}),
"D054": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Radix-tree prefix reuse; day-zero runtime for Qwen3.8-Flash-Next and V4.1 recipes.",
  entity=("sglang", "SGLang + RadixAttention (sgl-project)", "PRODUCT", "sgl-project community"),
  artifact="FRAMEWORK", lineage="CORE", branches=["inference-serving"], transitions=["paged-kv-to-radix-reuse"],
  inherit=None, caveat="Repo not audited; adoption facts rest on capstone recipe/repo records.",
  claims=[
    ("SGLang's RadixAttention organizes KV prefixes in a radix tree for cross-request reuse, extending paged management with prefix-aware sharing.", "PROJECT_CLAIM", "Project-role level; mechanism per D055 paper abstract."),
    ("SGLang serves as day-zero runtime for Qwen3.8-Flash-Next and V4.1 deployment paths per capstone records.", "PROJECT_CLAIM", "Adoption facts per D127/D129/D163.")],
  limits=["Repository not fetched; mechanism details rest on the paper record D055."],
  ver={"@FULL": ("VERIFIED", "Radix-reuse mechanism corroborated via D055 abstract; day-zero role via capstone records; repo audit outstanding."),
        "version binding at Evidence": ("UNRESOLVED", "No version pin extracted.")}),
"D055": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="RadixAttention + compressed FSM; multi-call agent serving waste.",
  entity=("sglang-paper-2023", "SGLang: Efficient Execution of Structured Language Model Programs (Zheng et al., 2023)", "PAPER", "Berkeley"),
  artifact="PAPER", lineage="CORE", branches=["inference-serving"], transitions=["single-call-to-program-serving"],
  inherit=None, caveat=None,
  claims=[
    ("SGLang introduces RadixAttention for prefix reuse across structured multi-call programs plus a compressed finite-state machine for constrained decoding.", "PRIMARY_FACT", "Headline mechanisms; abstract-level."),
    ("Program-level reuse directly addresses serving waste in agentic multi-call workloads, the Special's 'serving waste' thesis instance.", "INFERENCE", "Editorial significance.")],
  limits=["Full-body scheduler design and speedup tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2312.07104): RadixAttention + program execution confirmed; full body outstanding.")}),
"D056": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Kernel half of MLA efficiency story; sparse backend in vLLM V4.1.",
  entity=("flashmla", "FlashMLA (DeepSeek MLA decode kernel)", "PRODUCT", "DeepSeek-AI"),
  artifact="FRAMEWORK", lineage="CORE", branches=["inference-serving"], transitions=["flashattention-to-flashmla"],
  inherit=None, caveat="Repo not audited; kernel-role facts at release level.",
  claims=[
    ("FlashMLA is DeepSeek's MLA-optimized decode kernel, the kernel half of the MLA efficiency story complementing the architecture half (V2/V3).", "PROJECT_CLAIM", "Role level; corroborated by D078 vLLM sparse-backend record and D057 ETAP paper."),
    ("Its sparse backend variant serves V4.1-line decoding in vLLM.", "PROJECT_CLAIM", "Backend fact per D078/D163.")],
  limits=["Kernel code and benchmark tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Kernel role corroborated via D057 abstract and D078/D163 records; code audit outstanding.")}),
"D057": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="2.78x over FlashMLA on H20; stability-accounted reporting standard.",
  entity=("flashmla-etap-2025", "FlashMLA-ETAP: MLA inference on H20 (2025)", "PAPER", "Community/DeepSeek-ecosystem"),
  artifact="PAPER", lineage="BRIDGE", branches=["inference-serving"], transitions=["kernel-iteration"],
  inherit=None, caveat="2.78x is H20- and workload-bound; cited as reporting-standard example, not portable speedup.",
  claims=[
    ("FlashMLA-ETAP reports 2.78x over FlashMLA for MLA inference on H20 hardware.", "AUTHOR_CLAIM", "Headline number; abstract-level, hardware-bound."),
    ("The paper's stability-accounted reporting is cited as the standard vendor-adjacent numbers must meet before promotion.", "INFERENCE", "Methodological role in the Special.")],
  limits=["Full-body measurement methodology not consumed; number not independently verified."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2506.01969): 2.78x-on-H20 figure confirmed at headline level; methodology body outstanding."),
        "stability accounting": ("VERIFIED", "Stability-accounted reporting role recorded from the paper's framing.")}),
"D058": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Day-zero Qwen3.8-Flash-Next support; NVIDIA production kernel stack.",
  entity=("tensorrt-llm", "TensorRT-LLM (NVIDIA production kernel stack)", "PRODUCT", "NVIDIA"),
  artifact="FRAMEWORK", lineage="BRIDGE", branches=["inference-serving"], transitions=["research-kernel-to-production-stack"],
  inherit=None, caveat="Repo not audited; support facts at release level.",
  claims=[
    ("TensorRT-LLM provides day-zero Qwen3.8-Flash-Next support as NVIDIA's production kernel stack.", "PROJECT_CLAIM", "Support fact; consistent with D080 GB300 coverage."),
    ("Production-stack support is the deployability leg for the Qwen capstone alongside vLLM/SGLang paths.", "INFERENCE", "Coverage significance.")],
  limits=["Repository not fetched; supported-version details outstanding."],
  ver={"@FULL": ("VERIFIED", "Day-zero support role corroborated via D080 NVIDIA blog record; repo audit outstanding."),
        "version/precision binding": ("UNRESOLVED", "Exact supported-version/precision matrix not pinned.")}),
"D059": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Phase-split origin; KV-transfer-for-specialization tradeoff.",
  entity=("splitwise-2023", "Splitwise: Efficient Generative LLM Inference Using Phase Splitting (Patel et al., 2023)", "PAPER", "Microsoft Research"),
  artifact="PAPER", lineage="CORE", branches=["inference-serving"], transitions=["monolithic-to-disaggregated-serving"],
  inherit=None, caveat=None,
  claims=[
    ("Splitwise splits prefill and decode phases across heterogeneous machine pools, matching each phase's compute/memory character to hardware.", "PRIMARY_FACT", "Headline mechanism; abstract-level."),
    ("Phase splitting introduces the KV-transfer-for-specialization tradeoff that disaggregation designs (DistServe, Mooncake, 1P1D layouts) must all pay.", "INFERENCE", "Tradeoff significance.")],
  limits=["Full-body placement analysis and cost tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2311.18677): phase-splitting mechanism confirmed; full body outstanding.")}),
"D060": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Disaggregated prefill/decode with SLO-aware placement authority.",
  entity=("distserve-2024", "DistServe: Disaggregating Prefill and Decoding for Goodput-optimized LLM Serving (Zhong et al., 2024)", "PAPER", "Chicago/Michigan"),
  artifact="PAPER", lineage="CORE", branches=["inference-serving"], transitions=["splitwise-to-goodput-placement"],
  inherit=None, caveat=None,
  claims=[
    ("DistServe disaggregates prefill and decoding with SLO-aware placement optimizing goodput rather than raw throughput.", "PRIMARY_FACT", "Headline mechanism + metric; abstract-level."),
    ("Goodput/SLO framing is the scheduler/SLO-tradeoff authority for evaluating 1P1D-style verified layouts (D163).", "INFERENCE", "Methodological linkage.")],
  limits=["Full-body placement algorithms and goodput tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2401.09670): disaggregation + goodput optimization confirmed; full body outstanding.")}),
"D061": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Pooled KV store over CPU/DRAM/SSD + RDMA; context for V4.1 SSD-cache economics despite locator defect.",
  entity=("mooncake-2024", "Mooncake: A KVCache-centric Disaggregated Architecture for LLM Serving (Qin et al., 2024)", "PAPER", "Moonshot AI-affiliated"),
  artifact="PAPER", lineage="CORE", branches=["inference-serving"], transitions=["replicated-kv-to-pooled-kv"],
  inherit=None, caveat="Bound locator is a wrong-identity arXiv ID (see verification); claims rest on the true paper's established content.",
  claims=[
    ("Mooncake disaggregates the KV cache into a pooled store over CPU/DRAM/SSD with RDMA transfer, treating KV as a first-class distributed resource.", "AUTHOR_CLAIM", "Established content of the true paper (2407.00079); bound locator does not resolve to it."),
    ("Pooled-KV economics are the context for V4.1's SWA bounded-replay persistent tier (1/8 SSD/host) in the capstone case study.", "INFERENCE", "Cross-record synthesis; V4.1 figures per D123."),
    ("Bound Discovery locator https://arxiv.org/abs/2411.01181 resolves to an unrelated dynamical-systems paper.", "INFERENCE", "Verified via arXiv API title check; true identity 2407.00079 confirmed by title search.")],
  limits=["True-paper body not consumed beyond identity confirmation.", "Bound locator must be amended to 2407.00079 before locator-cited use."],
  ver={"@FULL": ("UNRESOLVED", "Locator-identity defect: bound 2411.01181 is not Mooncake. Gap-fill trigger G-EV-03: true identity arXiv 2407.00079 confirmed; amendment deferred to Sol.")}),
"D062": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Scheduler refinement between Orca and disaggregation; open-world addition despite locator defect.",
  entity=("sarathi-2023", "SARATHI: Efficient LLM Inference by Piggybacking Decodes with Chunked Prefills (Agrawal et al., 2023)", "PAPER", "Microsoft Research"),
  artifact="PAPER", lineage="CORE", branches=["inference-serving"], transitions=["orca-to-chunked-prefill"],
  inherit=None, caveat="Bound locator is a wrong-identity arXiv ID (see verification); claims rest on the true paper's established content.",
  claims=[
    ("SARATHI piggybacks decode steps with chunked prefills, filling the pipeline bubbles that stall decode throughput without letting prefill creep into decode latency.", "AUTHOR_CLAIM", "Established content of the true paper (2308.16369); bound locator does not resolve to it."),
    ("Chunked prefill is the scheduler refinement between Orca-style iteration batching and full disaggregation.", "INFERENCE", "Taxonomic placement."),
    ("Bound Discovery locator https://arxiv.org/abs/2308.16315 resolves to an unrelated quantum-dots paper (digit transposition of the true 2308.16369).", "INFERENCE", "Verified via arXiv API; true identity confirmed by title search.")],
  limits=["True-paper body not consumed beyond identity confirmation.", "Bound locator must be amended to 2308.16369 before locator-cited use."],
  ver={"@FULL": ("UNRESOLVED", "Locator-identity defect: bound 2308.16315 is not SARATHI. Gap-fill trigger G-EV-04: true identity arXiv 2308.16369 confirmed; amendment deferred to Sol.")}),
"D063": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Aggregated-vs-disaggregated experiment on one model binding D04/D05/D06/D08.",
  entity=("dynamo-v41-serving-lens", "NVIDIA Dynamo V4.1-Flash recipe (serving-lens reading)", "PRODUCT", "NVIDIA"),
  artifact="FRAMEWORK", lineage="CORE", branches=["inference-serving", "attention-kv", "decoding-acceleration", "precision-quantization", "capstone-2026-v41"], transitions=["single-axis-to-joint-experiment"],
  inherit=None, caveat="Same-locator distinct analytical role from D004 (duplicate group dynamo-v41-recipe-readings, not merged); configuration-bound.",
  claims=[
    ("Read through the serving lens, the Dynamo recipe is an aggregated-vs-disaggregated experiment on a single model, jointly exercising attention, decoding, precision, and serving choices.", "PROJECT_CLAIM", "Analytical-role claim; recipe facts corroborated via D163."),
    ("Joint-experiment structure is what lets the Special attribute effects to architecture vs runtime/system rather than to isolated components.", "INFERENCE", "Methodological significance.")],
  limits=["Recipe page body not consumed line-level; joint reading scoped to D163 corroboration."],
  ver={"@FULL": ("VERIFIED", "Serving-lens role corroborated via consumed D163 recipe; page body outstanding."),
        "experiment conditions": ("UNRESOLVED", "Exact per-condition measurement matrix not extracted from this page.")}),
"D064": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="MoE dispatch/combine at scale; communication half of D03 story.",
  entity=("deepep", "DeepEP (DeepSeek expert-parallel communication library)", "PRODUCT", "DeepSeek-AI"),
  artifact="FRAMEWORK", lineage="CORE", branches=["inference-serving", "conditional-compute-moe"], transitions=["megablocks-compute-to-deepep-communication"],
  inherit=None, caveat="Repo not audited; library-role facts at release level.",
  claims=[
    ("DeepEP provides high-throughput expert-parallel dispatch/combine communication for MoE training and inference at DeepSeek scale.", "PROJECT_CLAIM", "Library-role level; consistent with V3/V4 FP8-MoE training claims."),
    ("DeepEP is the communication twin to MegaBlocks' compute twin in the MoE systems story.", "INFERENCE", "Twin framing with D134.")],
  limits=["Library code and benchmark numbers not consumed."],
  ver={"@FULL": ("VERIFIED", "Communication-library role corroborated via V-line training records; code audit outstanding."),
        "version binding at Evidence": ("UNRESOLVED", "No version pin extracted.")}),
"D065": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Fine-grained FP8 matmul; kernel half of FP8 training/inference.",
  entity=("deepgemm", "DeepGEMM (DeepSeek FP8 GEMM library)", "PRODUCT", "DeepSeek-AI"),
  artifact="FRAMEWORK", lineage="CORE", branches=["inference-serving", "scaling-training", "precision-quantization"], transitions=["cublas-to-fp8-gemm"],
  inherit=None, caveat="Repo not audited; kernel-role facts at release level.",
  claims=[
    ("DeepGEMM implements fine-grained FP8 general matrix multiplication, the kernel half of the V3 FP8-training story.", "PROJECT_CLAIM", "Library-role level; consistent with D006 FP8-training claims."),
    ("Fine-grained (block-wise) FP8 scaling is what makes large-scale FP8 training numerically viable, linking D005 formats to D006 deployment.", "INFERENCE", "Mechanism linkage.")],
  limits=["Kernel code and numerics analysis not consumed."],
  ver={"@FULL": ("VERIFIED", "FP8-GEMM role corroborated via D006 training record; code audit outstanding.")}),
"D066": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Shared kernel substrate for paged/MLA/sparse/speculative serving paths.",
  entity=("flashinfer", "FlashInfer (AI kernels for LLM serving)", "PRODUCT", "flashinfer-ai community"),
  artifact="FRAMEWORK", lineage="BRIDGE", branches=["inference-serving"], transitions=["single-kernel-to-substrate"],
  inherit=None, caveat="Repo not audited; substrate-role facts at release level.",
  claims=[
    ("FlashInfer provides a shared kernel substrate covering paged, MLA, sparse, and speculative serving paths.", "PROJECT_CLAIM", "Project-role level."),
    ("Shared substrates explain how multiple serving techniques compose in one stack (e.g., vLLM Blackwell paths in D163).", "INFERENCE", "Composition significance.")],
  limits=["Kernel code and coverage matrix not consumed."],
  ver={"@FULL": ("VERIFIED", "Substrate role recorded at project level; composition corroborated via D163 Blackwell config; code audit outstanding."),
        "version binding at Evidence": ("UNRESOLVED", "No version pin extracted.")}),
"D067": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Soft-target distillation origin; quality/capacity tradeoff frame.",
  entity=("hinton-distillation-2015", "Distilling the Knowledge in a Neural Network (Hinton et al., 2015)", "PAPER", "Google"),
  artifact="PAPER", lineage="CORE", branches=["distillation-adaptation"], transitions=["ensemble-to-soft-targets"],
  inherit=None, caveat="Pre-LLM origin; temperature/soft-target mechanics transfer, scale conclusions do not.",
  claims=[
    ("Hinton et al. introduce knowledge distillation via softened teacher targets, framing the quality/capacity tradeoff that governs all later distillation work.", "PRIMARY_FACT", "Foundational mechanism + framing; abstract-level."),
    ("Soft-target distillation is the origin retained after the D159/D160 drops for the reader-facing decoder/reasoning history.", "INFERENCE", "Screening-rationale linkage.")],
  limits=["Full-body temperature experiments not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (1503.02531): soft-target distillation confirmed; full body outstanding.")}),
"D068": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Frozen-base + low-rank adapter fine-tuning efficiency anchor.",
  entity=("lora-2021", "LoRA: Low-Rank Adaptation of Large Language Models (Hu et al., 2021)", "PAPER", "Microsoft Research"),
  artifact="PAPER", lineage="CORE", branches=["distillation-adaptation"], transitions=["full-finetune-to-low-rank"],
  inherit=None, caveat=None,
  claims=[
    ("LoRA freezes pretrained weights and injects trainable low-rank decomposition matrices, cutting fine-tuning memory and storage by orders of magnitude.", "PRIMARY_FACT", "Headline mechanism + efficiency claim; abstract-level."),
    ("LoRA defines fine-tuning efficiency as distinct from pretraining and inference efficiency in the Special's cost taxonomy.", "INFERENCE", "Taxonomic placement.")],
  limits=["Full-body rank-sweep tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2106.09685): low-rank adaptation confirmed; full body outstanding.")}),
"D069": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="RL-incentivized reasoning + distillation into dense students; post-training efficiency lever.",
  entity=("deepseek-r1-2025", "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning (2025)", "PAPER", "DeepSeek-AI"),
  artifact="PAPER", lineage="CORE", branches=["distillation-adaptation", "capstone-2026-v41"], transitions=["sft-to-rl-reasoning"],
  inherit=None, caveat="Reasoning-distillation quality claims are benchmark-bound; student-vs-teacher gaps vary by task.",
  claims=[
    ("DeepSeek-R1 incentivizes reasoning capability via large-scale reinforcement learning and distills the resulting reasoning patterns into dense student models (R1-Distill family).", "PRIMARY_FACT", "Headline pipeline; abstract-level."),
    ("R1-style reasoning distillation is the current-usage anchor that lets the Special drop encoder-era bridges (D159/D160) without losing the distillation history.", "INFERENCE", "Screening-rationale linkage.")],
  limits=["Full-body RL pipeline and distillation evaluation tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2501.12948): RL-incentivized reasoning + distillation confirmed; full body outstanding.")}),
"D070": dict(status="VERIFIED", mat="MATERIAL",
  mat_rationale="TypeSafe launch: new architecture + parallel sampler + RLCD; typed outputs; 70-500ms; race claims quarantined as vendor claims.",
  entity=("typesafe-jev-launch", "Introducing System One Models & Jev (TypeSafe launch, 2026-09-15)", "PRODUCT", "TypeSafe AI"),
  artifact="PRODUCT", lineage="CORE", branches=["specialization-jeff"], transitions=["generation-to-decision-models"],
  inherit=None, caveat="All comparative speed/cost/intelligence figures are vendor-evaluated; independent evaluation status thin (see D073).",
  claims=[
    ("TypeSafe announces System One Models with Jev in early access: a new model architecture with parallel sampler and RLCD training, emitting typed probabilistic outputs instead of generated strings.", "VENDOR_CLAIM", "Launch page fully consumed this pass (published 2026-09-15, founder Diogo Almeida, ex-OpenAI/ChatGPT research)."),
    ("The launch claims ~70-500ms end-to-end (40-200x faster), $0.042/MTok input with free outputs, no-type-error guarantees by construction, and Pareto-frontier workflow evals vs GPT-6 Astra/Fable 5.1 average as reference (193.6x faster / 444.6x cheaper at the high end).", "VENDOR_CLAIM", "Vendor-evaluated; page's own nuance sections disclose laptop-based evals, workflow-authorship bias, and reference-answer bias toward OpenAI/Anthropic."),
    ("The launch discloses evaluation limits directly: speed/cost measured from West-Coast laptops, workflows built by its own capabilities team, LLM baselines run through its System One adapter wrapper, hallucination numbers for LLMs sourced from OpenRouter routing.", "VENDOR_CLAIM", "First-party nuance admissions; material to the Jev limitations case.")],
  limits=["Independent reproduction of latency/price/accuracy claims outstanding (D073 community leads only).", "RLCD algorithm internals not disclosed on this page; architecture detail limited to sampler/output semantics."],
  ver={"@FULL": ("VERIFIED", "Launch page fully consumed: architecture/sampler/RLCD/price/latency/eval-design/nuance claims extracted with vendor boundaries."),
        "race/accuracy claims quarantine": ("VERIFIED", "All comparative figures recorded strictly as vendor claims with the page's own bias disclosures attached; none promoted to independent fact.")}),
"D071": dict(status="VERIFIED", mat="MATERIAL",
  mat_rationale="TypeSafe docs: Choice/Score/Noul primitives, parallel isolation, group-level calibration; text-only + atomic-question limits.",
  entity=("typesafe-system-one-concepts", "TypeSafe docs: System One concepts + Introduction", "PRODUCT", "TypeSafe AI"),
  artifact="PRODUCT", lineage="CORE", branches=["specialization-jeff"], transitions=["llm-api-to-decision-api"],
  inherit=None, caveat="Documentation describes intended semantics; behavioral compliance (calibration quality) is independently unverified.",
  claims=[
    ("System One models evaluate a state and return typed answers via Choice/Score/Noul primitives with per-output confidence, all questions in parallel.", "PROJECT_CLAIM", "Concepts page fully consumed this pass."),
    ("Calibration is measured across groups of predictions and does not guarantee any individual answer; Jev is text-only, English-primary, with 255-cardinality handling via two-stage score-then-choose.", "PROJECT_CLAIM", "Documented limits; calibration-group caveat is first-party."),
    ("Decomposition guidance (atomic questions, code-side combination, confidence-gated escalation) defines suitable task classes: classify/route/score/extract/branch inside deterministic workflows.", "PROJECT_CLAIM", "Usage semantics per docs; suitability boundary for the Jev case study.")],
  limits=["Behavioral calibration quality and non-English accuracy untested independently.", "API-reference contract details belong to D142, not this page."],
  ver={"@FULL": ("VERIFIED", "Concepts page fully consumed: primitives, calibration semantics, limits, workflow role extracted.")}),
}
