"""Evidence record specs Part C: D072-D100 (Jev secondary, capstone watch/secondary, benchmark methodology core)."""
PART_C = {
"D072": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="Jev wiki dated fact snapshot; explicitly not specification authority — corroboration only.",
  entity=("jev-wiki-snapshot", "Jev wiki: Jev 1.13 model-card facts (jevai.wiki)", "ORGANIZATION", "Community wiki"),
  artifact="PRODUCT", lineage="CONTEXT", branches=["specialization-jeff"], transitions=["spec-to-snapshot"],
  inherit=None, caveat="Dated snapshot may lag the versioned docs; conflicts resolve in favor of D141.",
  claims=[
    ("The wiki snapshot records Jev 1.13 facts (64k context, $0.042/MTok, 70-500ms class) consistent with first-party docs at snapshot date.", "SOCIAL_OBSERVATION", "Corroboration only; values match D141 where overlapping."),
    ("The snapshot is not specification authority and must not be cited for version, price, or limit facts.", "INFERENCE", "Authority boundary per screening decision.")],
  limits=["Snapshot date and edit provenance not established; wiki content mutable."],
  ver={"@FULL": ("VERIFIED", "Corroboration role confirmed against consumed D141; snapshot body not independently audited."),
        "fact snapshot vs official docs": ("VERIFIED", "Values consistent with official docs; precedence rule (docs over wiki) recorded.")}),
"D073": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="Community reproduction hub: OpenJev/Jevlike/Qwen-RLCD leads; community-grade only, no peer-reviewed reproduction this pass.",
  entity=("awesome-jev", "awesome-jev community reproduction hub (OmniJev)", "ORGANIZATION", "Community (OmniJev)"),
  artifact="PRODUCT", lineage="CONTEXT", branches=["specialization-jeff"], transitions=["vendor-claim-to-community-probe"],
  inherit=None, caveat="Community leads are not peer-reviewed reproduction; absence of reproduction is a finding, not a verdict on the claims.",
  claims=[
    ("The hub collects community reproduction leads (OpenJev, Jevlike, Qwen-RLCD experiments) around Jev's claimed mechanisms.", "SOCIAL_OBSERVATION", "Existence-level; lead quality unassessed."),
    ("No peer-reviewed independent reproduction of Jev's architecture, RLCD, or Pareto claims was located this pass.", "INFERENCE", "Negative finding from search scope; central to the Jev limitations case.")],
  limits=["Hub contents not audited lead-by-lead; independent evaluation status remains LOW_SIGNAL per X corpus (D162)."],
  ver={"@FULL": ("VERIFIED", "Hub role as lead-collector confirmed at existence level; reproduction audit outstanding."),
        "lead verification; no peer-reviewed reproduction this pass": ("VERIFIED", "No peer-reviewed reproduction located; finding recorded as limitation, not refutation.")}),
"D074": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="DataCamp Jev explainer; secondary corroboration of access/pricing only.",
  entity=("datacamp-jev-explainer", "Jev explainer with access/pricing facts (DataCamp)", "ORGANIZATION", "DataCamp"),
  artifact="PRODUCT", lineage="CONTEXT", branches=["specialization-jeff"], transitions=["spec-to-explainer"],
  inherit=None, caveat="Secondary explainer; technical claims resolve to D070/D071/D141.",
  claims=[
    ("The explainer corroborates Jev early-access availability, endpoint shape, and pricing facts at secondary level.", "SOCIAL_OBSERVATION", "Corroboration only."),
    ("No independent technical measurement is sourced to this page.", "INFERENCE", "Authority boundary.")],
  limits=["Page body not fetched; corroboration scoped to Discovery summary."],
  ver={"@FULL": ("VERIFIED", "Corroboration role confirmed; explainer body outstanding."),
        "vs official docs": ("VERIFIED", "No conflict with consumed official docs asserted; precedence to D070/D141 recorded.")}),
"D075": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="Lambda provider page: specs + provider-measured throughput; secondary, rebind at Evidence.",
  entity=("lambda-v4-flash-page", "DeepSeek-V4-Flash provider page (Lambda)", "ORGANIZATION", "Lambda"),
  artifact="PRODUCT", lineage="CONTEXT", branches=["capstone-2026-v41", "conditional-compute-moe", "inference-serving"], transitions=["first-party-to-provider-mirror"],
  inherit=None, caveat="Provider-measured throughput is harness- and derivation-bound; provider spec strings may lag first-party.",
  claims=[
    ("The Lambda page mirrors V4-Flash spec facts (284B/13B, mHC, Muon 32T, FP4+FP8) with provider-measured throughput figures.", "SOCIAL_OBSERVATION", "Mirror-level; spec facts consistent with D017/D124."),
    ("Provider throughput numbers are configuration-bound observations, not architecture facts.", "INFERENCE", "Boundary statement.")],
  limits=["Page not fetched; provider figures not extracted or compared."],
  ver={"@FULL": ("VERIFIED", "Mirror role confirmed; spec consistency with first-party records noted."),
        "provider measurement conditions": ("UNRESOLVED", "Measurement conditions not extracted; figures excluded from fact claims.")}),
"D076": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="DeepInfra price sample for API-economics lane; not official DeepSeek pricing.",
  entity=("deepinfra-v4-pricing", "DeepInfra V4 Flash API pricing snapshot", "ORGANIZATION", "DeepInfra"),
  artifact="API", lineage="CONTEXT", branches=["capstone-2026-v41"], transitions=["list-price-to-transaction-price"],
  inherit=None, caveat="Provider sample only; official DeepSeek peak/off-peak schedule (D031) is the pricing authority.",
  claims=[
    ("DeepInfra publishes a V4-Flash API price sample usable as one transaction-price datapoint in the economics lane.", "SOCIAL_OBSERVATION", "Sample-level; not official pricing."),
    ("API economics require model/version binding plus date binding; undated samples are not comparable across time.", "INFERENCE", "Methodological boundary.")],
  limits=["Page not fetched; price figures not extracted."],
  ver={"@FULL": ("VERIFIED", "Sample role confirmed; economics-lane boundary recorded."),
        "official pricing": ("UNRESOLVED", "Official-vs-provider reconciliation not performed; D031 schedule takes precedence.")}),
"D077": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="AI-drafted UNEDITED V4.1 parameter study; derivations traceable to tensor/config authority but page remains a lead, not authority.",
  entity=("ezyang-dsv41-study", "Infra-oriented V4.1-Flash architecture study (parameter accounting)", "ORGANIZATION", "Independent study (E. Zheng)"),
  artifact="PAPER", lineage="CONTEXT", branches=["capstone-2026-v41", "attention-kv"], transitions=["report-to-tensor-audit"],
  inherit=None, caveat="AI-drafted and unedited by the author's own disclosure; use as a lead with disclosed method, never as standalone authority.",
  claims=[
    ("The study derives 551,566,180,464 backbone parameters (advertised 552B) and 196,928,504,320 Engram parameters (advertised 196B) from safetensors headers of all 48 shards, cross-checked against config.json and inference/model.py, with per-token 16.13B decode / 7.90B prefill under DeepSeek's counting convention.", "AUTHOR_CLAIM", "Study page fully consumed this pass (https://deepseek-v3.ezyang.com/studies/dsv41-flash.html); figures are the study's, cross-checked as described on-page."),
    ("The 890 bytes/token global-KV headline falls out of the study's CSA2 accounting: 2.5 entries/token x (288B main FP4 + 68B indexer key); SWA caches are bounded and never persisted.", "AUTHOR_CLAIM", "Derivation-level; method disclosed on-page (Full/Reindex/Reuse roles, FP4 E2M1 + E4M3/E8M0 scales)."),
    ("The page explicitly discloses AI-drafted, human-unedited status and names its primaries (V4.1 tech-report PDF, checkpoint config.json, reference model.py, safetensors headers).", "AUTHOR_CLAIM", "First-party disclosure on-page; governs the lead-not-authority handling.")],
  limits=["Tensor-level derivations not re-verified independently (no checkpoint inspection this pass).", "Vision tower (485M) and DSpark drafter (14.2B) excluded from backbone counts per stated convention."],
  ver={"@FULL": ("VERIFIED", "Study page fully consumed: disclosure, derivation method, parameter/KV figures extracted; independent tensor re-verification outstanding."),
        "verify derivations against report/card": ("VERIFIED", "Cross-check chain (report PDF + config + model.py + headers) confirmed as stated on-page; figures match advertised 552B/196B/16B/8B/890B; lead-not-authority handling applied per disclosure.")}),
"D078": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="vLLM deepseek_v41 model code docs: FlashMLA sparse backend, expert FP8 dispatch, DSpark class; deployment evidence.",
  entity=("vllm-deepseek-v41-docs", "vLLM deepseek_v41 model code docs", "ORGANIZATION", "vLLM Project"),
  artifact="FRAMEWORK", lineage="CORE", branches=["capstone-2026-v41", "inference-serving"], transitions=["recipe-to-code-docs"],
  inherit=None, caveat="Code docs describe the implementation surface; measured behavior belongs to benchmarks, not docs.",
  claims=[
    ("The vLLM deepseek_v41 docs specify the FlashMLA sparse backend, expert FP8 dispatch paths, and the DSpark speculative class for V4.1-line serving.", "PROJECT_CLAIM", "Documentation-level; consistent with fully-consumed D163 recipe."),
    ("Code-docs plus recipe jointly constitute the vLLM-side deployment evidence for the V4.1 capstone.", "INFERENCE", "Evidence-composition statement.")],
  limits=["Docs page not fetched separately; claims rest on D163 consumption and Discovery summary."],
  ver={"@FULL": ("VERIFIED", "Deployment-evidence role corroborated via D163; page body outstanding."),
        "version binding": ("UNRESOLVED", "Doc-to-release version pin not extracted.")}),
"D079": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="llm-stats Qwen launch analysis; weights-vs-API split useful but vendor comparisons need quarantine.",
  entity=("llmstats-qwen38-analysis", "Qwen3.8-Flash-Next launch analysis (llm-stats)", "ORGANIZATION", "llm-stats"),
  artifact="PRODUCT", lineage="CONTEXT", branches=["capstone-2026-v41", "benchmark-methodology"], transitions=["launch-to-third-party-analysis"],
  inherit=None, caveat="Third-party analysis mixing vendor figures with own measurements; each number needs source binding before use.",
  claims=[
    ("The analysis separates weights-vs-API availability for Qwen3.8-Flash-Next, a material deployment distinction.", "SOCIAL_OBSERVATION", "Structural observation; availability split corroborated by D127."),
    ("Self-reported DeepSWE 58.7 / SWE-Pro 62.5 figures and the OSWorld coin-flip caveat are carried strictly as quarantined vendor-via-secondary numbers.", "SOCIAL_OBSERVATION", "Quarantine boundary; harness binding outstanding.")],
  limits=["Page not fetched; figures not extracted or harness-bound."],
  ver={"@FULL": ("VERIFIED", "Analysis role confirmed at structural level; figure extraction outstanding."),
        "vendor comparison quarantine": ("VERIFIED", "Vendor-comparison figures excluded from fact claims pending harness binding.")}),
"D080": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="NVIDIA blog Qwen-on-GB300 numbers; condition-bound (prefix-hit) vendor-adjacent benchmark.",
  entity=("nvidia-qwen-gb300-blog", "NVIDIA blog: Qwen3.8-Flash-Next on GB300 NVL72", "ORGANIZATION", "NVIDIA"),
  artifact="PRODUCT", lineage="CONTEXT", branches=["capstone-2026-v41", "attention-kv", "inference-serving"], transitions=["report-to-vendor-benchmark"],
  inherit=None, caveat="QSA 7.6x/4.9x and 8.6x-vs-Qwen3.7-Plus figures are prefix-hit-conditioned vendor-adjacent measurements, not architecture constants.",
  claims=[
    ("The blog reports QSA 7.6x prefill / 4.9x decode gains and 8.6x vs Qwen3.7-Plus at 90% prefix hit on GB300 NVL72.", "VENDOR_CLAIM", "Headline figures; conditions attached as stated in summary."),
    ("Prefix-hit conditioning makes the figures a cache-locality measurement as much as an attention measurement.", "INFERENCE", "Methodological reading central to EFF-O12.")],
  limits=["Blog page not fetched; figures not independently verified or harness-decomposed."],
  ver={"@FULL": ("VERIFIED", "Condition-bound figures recorded with prefix-hit/hardware bounds; page body outstanding."),
        "harness/prefix-hit conditions": ("VERIFIED", "90%-prefix-hit condition attached to all cited figures; no unconditioned speedup claim made.")}),
"D081": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Qwen3.8-Flash-Next official blog: four-aspect upgrade; micro-block QSA; Muon assignment; scaling-law refit.",
  entity=("qwen38-flash-next-blog", "Qwen3.8-Flash-Next official blog (Qwen)", "PRODUCT", "Alibaba Qwen"),
  artifact="PRODUCT", lineage="CORE", branches=["capstone-2026-v41"], transitions=["report-to-launch"],
  inherit=None, caveat="Vendor launch framing; technical substance resolves to D008/D029.",
  claims=[
    ("The official blog frames the launch as a four-aspect upgrade with micro-block QSA, Muon optimizer assignment, and a scaling-law refit.", "VENDOR_CLAIM", "Announcement-level; substance corroborated by D008 abstract."),
    ("Upgrade-vs-predecessor language is vendor framing and is not cited as measured fact.", "INFERENCE", "Boundary statement.")],
  limits=["Blog page not fetched; substance rests on D008 corroboration."],
  ver={"@FULL": ("VERIFIED", "Launch-framing role corroborated against D008; page body outstanding."),
        "upgrade claims quarantine": ("VERIFIED", "Comparative upgrade language excluded from fact claims.")}),
"D082": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="llm-stats GLM launch analysis; promo-vs-list pricing and vendor comparisons need quarantine.",
  entity=("llmstats-glm53-analysis", "GLM-5.3-Flash launch analysis (llm-stats)", "ORGANIZATION", "llm-stats"),
  artifact="PRODUCT", lineage="CONTEXT", branches=["capstone-2026-v41", "benchmark-methodology"], transitions=["launch-to-third-party-analysis"],
  inherit=None, caveat="Promo-vs-list pricing ambiguity; vendor comparison tables quarantined.",
  claims=[
    ("The analysis records GLM-5.3-Flash launch facts (320B/18B multimodal MIT, ox-alpha stealth identity) consistent with first-party records.", "SOCIAL_OBSERVATION", "Identity-level; corroborated by D130/D164."),
    ("Pricing (promo vs list) and vendor benchmark comparisons are carried strictly as quarantined secondary figures.", "SOCIAL_OBSERVATION", "Quarantine boundary.")],
  limits=["Page not fetched; figures not extracted or reconciled."],
  ver={"@FULL": ("VERIFIED", "Analysis role and identity facts corroborated; figure extraction outstanding."),
        "pricing/comparison quarantine": ("VERIFIED", "Pricing/comparison figures excluded from fact claims.")}),
"D083": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="HF transformers GLM5-next doc: hybrid sparse+linear, mHC, 30T; vendor ratios; transformers impl excludes MTP layer.",
  entity=("hf-transformers-glm5-next", "HF transformers GLM5-next doc (hybrid sparse+linear, mHC, 30T)", "ORGANIZATION", "Hugging Face"),
  artifact="FRAMEWORK", lineage="CORE", branches=["capstone-2026-v41", "attention-kv"], transitions=["model-to-framework-port"],
  inherit=None, caveat="3.0x-attention/4.4x-KV ratios are vendor-relative (vs GLM-5.3); framework port coverage (MTP excluded) conditions reuse claims.",
  claims=[
    ("The transformers doc specifies the GLM5-next hybrid sparse+linear attention with mHC trained on 30T tokens.", "PROJECT_CLAIM", "Documentation-level; consistent with GLM-5 DSA-adoption line (D128)."),
    ("The transformers implementation excludes the MTP layer, so MTP acceptance gains (D129) do not transfer to this port.", "PROJECT_CLAIM", "Coverage limitation with direct serving implications.")],
  limits=["Doc page not fetched; coverage facts scoped to Discovery summary."],
  ver={"@FULL": ("VERIFIED", "Port role and MTP-exclusion fact recorded; doc body outstanding."),
        "MTP exclusion; vendor ratios": ("VERIFIED", "MTP exclusion recorded as coverage fact; 3.0x/4.4x ratios carried as vendor-relative only.")}),
"D084": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="LM Studio GLM page: IndexPool gloss, forced thinking, vendor benchmark table with harness warning.",
  entity=("lmstudio-glm53-page", "GLM-5.3-Flash LM Studio page (IndexPool, benchmarks)", "ORGANIZATION", "LM Studio"),
  artifact="PRODUCT", lineage="CONTEXT", branches=["capstone-2026-v41", "benchmark-methodology"], transitions=["first-party-to-client-page"],
  inherit=None, caveat="Client-page gloss; vendor benchmark table unusable without harness binding.",
  claims=[
    ("The page glosses IndexPool, forced-thinking behavior, and local-runner availability for GLM-5.3-Flash.", "SOCIAL_OBSERVATION", "Gloss-level; IndexPool itself unresolved per D129."),
    ("Its vendor benchmark table is carried with an explicit harness warning and cited for no fact.", "SOCIAL_OBSERVATION", "Quarantine boundary.")],
  limits=["Page not fetched; IndexPool identity still unresolved."],
  ver={"@FULL": ("VERIFIED", "Gloss role confirmed; benchmark table quarantined."),
        "harness binding": ("UNRESOLVED", "No harness binding extracted; table unusable as evidence.")}),
"D085": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="NVIDIA NIM GLM card: hybrid claims plus KDA-label collision with Kimi KDA to resolve.",
  entity=("nim-glm53-card", "NVIDIA NIM GLM-5.3-Flash card", "ORGANIZATION", "NVIDIA"),
  artifact="PRODUCT", lineage="CONTEXT", branches=["capstone-2026-v41"], transitions=["first-party-to-nim-card"],
  inherit=None, caveat="KDA label on this card must not be read as Kimi Delta Attention; collision unresolved from this page alone.",
  claims=[
    ("The NIM card describes hybrid KDA+sparse-MLA + FP8 deployment facts for GLM-5.3-Flash.", "SOCIAL_OBSERVATION", "Card-level; hybrid direction consistent with D128/D129."),
    ("The card's KDA label collides with Kimi Delta Attention naming and is explicitly left unresolved here.", "INFERENCE", "Collision boundary; disambiguation deferred.")],
  limits=["Page not fetched; KDA expansion unverified."],
  ver={"@FULL": ("VERIFIED", "Card role confirmed; collision flagged, not resolved."),
        "KDA disambiguation": ("UNRESOLVED", "Whether the card's KDA denotes a distinct mechanism is open; no conflation made.")}),
"D086": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="MiniMax-M2.x materiality watch: no distinct efficiency mechanism confirmed; pursue/park is Sol materiality judgment.",
  entity=("minimax-m2x-watch", "MiniMax-M2.x materiality watch", "PRODUCT", "MiniMax"),
  artifact="PRODUCT", lineage="CONTEXT", branches=["capstone-2026-v41"], transitions=["watch-to-judgment"],
  inherit=None, caveat="Locator-only; no mechanism claim made or implied.",
  claims=[
    ("No distinct efficiency mechanism for MiniMax-M2.x was confirmed this pass; the record exists solely to force an explicit pursue/park judgment.", "INFERENCE", "Watch-status finding from locator-only state."),
    ("Pursue/park is a Sol materiality judgment, not decided by this Evidence record.", "INFERENCE", "Governance boundary.")],
  limits=["No MiniMax first-party body consumed; mechanism contribution entirely unverified."],
  ver={"@FULL": ("UNRESOLVED", "Locator-only; no consumable body for mechanism assessment."),
        "mechanism confirmation": ("UNRESOLVED", "Distinct-mechanism contribution unconfirmed; Sol pursue/park judgment pending.")}),
"D087": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="gpt-oss materiality watch: distinct-mechanism contribution vs MoE/quant/serving lanes unverified.",
  entity=("gpt-oss-watch", "gpt-oss open-weight models (OpenAI announcement)", "PRODUCT", "OpenAI"),
  artifact="PRODUCT", lineage="CONTEXT", branches=["capstone-2026-v41"], transitions=["watch-to-judgment"],
  inherit=None, caveat="Announcement-level only; no lane contribution asserted.",
  claims=[
    ("OpenAI's gpt-oss announcement establishes open-weight availability; its distinct-mechanism contribution to MoE/quant/serving lanes is unverified.", "VENDOR_CLAIM", "Availability-level only."),
    ("Pursue/park is a Sol materiality judgment.", "INFERENCE", "Governance boundary.")],
  limits=["Announcement body not consumed beyond availability; no technical assessment made."],
  ver={"@FULL": ("UNRESOLVED", "Locator-only; technical body outstanding."),
        "mechanism contribution": ("UNRESOLVED", "Lane contribution unassessed; Sol judgment pending.")}),
"D088": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Reasoning-focused broad-knowledge seed benchmark; version pin at Evidence.",
  entity=("mmlu-pro", "MMLU-Pro (Wang et al., 2024)", "PAPER", "Independent"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["mmlu-to-mmlu-pro"],
  inherit=None, caveat="MMLU-Pro scores are version- and harness-bound; cross-paper comparisons without pins are invalid.",
  claims=[
    ("MMLU-Pro revises MMLU toward reasoning-focused questions with expanded choices, serving as the broad-knowledge seed benchmark.", "PRIMARY_FACT", "Design facts; abstract-level (2406.01574)."),
    ("Any capstone citation of MMLU-Pro-class numbers requires version, harness, and reasoning-budget binding.", "INFERENCE", "Methodological rule.")],
  limits=["Full-body construction details and option-count tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2406.01574): reasoning-focused revision confirmed; full body outstanding."),
        "version pin": ("UNRESOLVED", "No single version pinned for capstone citations; binding rule recorded instead.")}),
"D089": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Expert science seed; split/harness binding required for capstone citations.",
  entity=("gpqa-diamond", "GPQA: A Graduate-Level Google-Proof Q&A Benchmark (Rein et al., 2023)", "PAPER", "NYU/Anthropic"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["broad-to-expert-science"],
  inherit=None, caveat="Diamond/Main/Extended splits are different benchmarks in practice; split must be named.",
  claims=[
    ("GPQA is an expert-authored science benchmark with Diamond/Main/Extended splits of increasing curation rigor.", "PRIMARY_FACT", "Design facts; abstract-level (2311.12022)."),
    ("Capstone citations must name the split and harness; bare 'GPQA' scores are not comparable.", "INFERENCE", "Methodological rule.")],
  limits=["Full-body curation protocol not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2311.12022): expert-science design confirmed; full body outstanding."),
        "split/harness binding": ("UNRESOLVED", "Split/harness pins enforced as rule; no citation audited this pass.")}),
"D090": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Saturation-response set with public/private design; no capstone HLE number this pass.",
  entity=("hle-2025", "Humanity's Last Exam (Phan et al., 2025)", "PAPER", "CAIS/Scale AI"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["saturated-to-frontier-exam"],
  inherit=None, caveat="Public/private split design means public-set numbers understate held-out difficulty; no capstone HLE figure cited.",
  claims=[
    ("HLE is a frontier exam designed as the saturation response to exhausted benchmarks, with public/private test construction.", "PRIMARY_FACT", "Design facts; abstract-level (2501.14249)."),
    ("No capstone HLE number is cited this pass; the record's role is taxonomy and validity framing.", "INFERENCE", "Scope statement.")],
  limits=["Full-body question-collection protocol not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2501.14249): saturation-response design confirmed; full body outstanding.")}),
"D091": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Time-windowed anti-contamination code set; version pin mandatory.",
  entity=("livecodebench-2024", "LiveCodeBench: Holistic and Contamination Free Evaluation of LLMs for Code (Jain et al., 2024)", "PAPER", "Berkeley/MIT"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["static-code-to-live-code"],
  inherit=None, caveat="Time windows make versions non-comparable across cutoffs; cutoff must be stated.",
  claims=[
    ("LiveCodeBench continuously sources problems with time-windowed releases to resist contamination, covering code generation, repair, and execution.", "PRIMARY_FACT", "Design facts; abstract-level (2403.07974)."),
    ("Version (time-window) pinning is mandatory for any cited figure.", "INFERENCE", "Methodological rule.")],
  limits=["Full-body release protocol not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2403.07974): time-windowed anti-contamination design confirmed; full body outstanding."),
        "version pin": ("UNRESOLVED", "Window pins enforced as rule; no citation audited.")}),
"D092": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Real-issue repo tasks; base for Verified/Pro validity thread.",
  entity=("swe-bench-2023", "SWE-bench: Can Language Models Resolve Real-World GitHub Issues? (Jimenez et al., 2023)", "PAPER", "Princeton"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["function-to-repo-tasks"],
  inherit=None, caveat="Base SWE-bench contains broken tasks; validity claims require the Verified/Pro thread (D093 + follow-up).",
  claims=[
    ("SWE-bench tasks models with resolving real GitHub issues in Python repositories with test-based verification.", "PRIMARY_FACT", "Design facts; abstract-level (2310.06770)."),
    ("Base-set validity limits (broken tasks, underspecification) motivate the Verified curation and the Pro redesign as first-class validity evidence.", "INFERENCE", "Validity-thread framing.")],
  limits=["Full-body task-collection protocol not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2310.06770): real-issue repo-task design confirmed; full body outstanding.")}),
"D093": dict(status="PARTIAL", mat="HOLD",
  mat_rationale="SWE-bench-Pro identity resolved via gap-fill (true: 2509.16941) but bound locator is wrong-identity; held for Sol locator/binding judgment.",
  entity=("swe-bench-pro", "SWE-bench-Pro (validity-evolution example)", "PAPER", "Scale AI et al."),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["verified-to-pro"],
  inherit=None, caveat="Bound locator is a wrong-identity arXiv ID; all Pro substance below comes from gap-fill, not bound bytes.",
  claims=[
    ("Bound Discovery locator https://arxiv.org/abs/2503.01324 resolves to an unrelated federated-learning paper (MAB channel scheduling), not any SWE benchmark.", "INFERENCE", "Verified via arXiv API title check this pass."),
    ("The true SWE-bench-Pro identity is arXiv 2509.16941 (Deng et al.): 1,865 problems across 41 repos with public/commercial/held-out splits, contamination-resistant collection, human-verified augmentation; frontier models score <45% Pass@1 (GPT-5 ~23% public) vs >70% on SWE-bench Verified.", "AUTHOR_CLAIM", "Gap-fill via web search this pass (abstract + results excerpts); paper body not consumed."),
    ("A follow-up, SWE-Bench Pro Verified (arXiv 2609.08149), adds anti-hacking controls and LLM-assisted filtering over 731 instances.", "AUTHOR_CLAIM", "Gap-fill identity only; body not consumed."),
    ("The Verified-to-Pro relationship (Verified: human-curated subset fixing broken tasks; Pro: harder, larger, contamination-resistant redesign with private splits) is the mandatory benchmark-validity example.", "INFERENCE", "Validity-thread synthesis.")],
  limits=["True-paper bodies not consumed; Pro figures rest on search excerpts.", "Bound locator must be amended to 2509.16941 before locator-cited use.", "Public vs commercial vs held-out comparisons must never be mixed."],
  ver={"@FULL": ("UNRESOLVED", "Bound locator binds the wrong paper; no Pro body consumed at bound bytes."),
        "isolate exact Pro variant + body": ("UNRESOLVED", "True identity isolated (2509.16941 + 2609.08149 follow-up) via gap-fill trigger G-EV-05; body consumption and binding deferred to Sol.")}),
"D094": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Containerized terminal tasks; version suffix proves name-is-not-contract despite locator defect.",
  entity=("terminal-bench", "Terminal-Bench (containerized terminal tasks)", "PAPER", "Stanford/Harbor"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["static-bench-to-terminal-agents"],
  inherit=None, caveat="Bound locator is a wrong-identity arXiv ID; version-suffix rule rests on family knowledge plus verified 2.0 identity.",
  claims=[
    ("Terminal-Bench evaluates agents on realistic terminal tasks in containerized environments with outcome-driven tests on final container state.", "AUTHOR_CLAIM", "Family design facts; verified 2.0 paper (2601.11868, ICLR 2026: 89 tasks, frontier <65%) via web search this pass."),
    ("The version suffix (1.x vs 2.0) proves the name-is-not-contract rule: same name with different task sets is a different benchmark.", "INFERENCE", "Validity-rule statement; 2.0 figures per search excerpts."),
    ("Bound Discovery locator https://arxiv.org/abs/2406.06750 resolves to an unrelated optics paper.", "INFERENCE", "Verified via arXiv API title check.")],
  limits=["True-paper bodies not consumed; v1 original arXiv ID unpinned (2.0 verified as 2601.11868).", "Bound locator must be amended before locator-cited use."],
  ver={"@FULL": ("UNRESOLVED", "Locator-identity defect: bound 2406.06750 is not Terminal-Bench. Gap-fill trigger G-EV-06: family identity verified via 2.0 (2601.11868); v1 ID + body outstanding."),
        "version suffix": ("VERIFIED", "Name-is-not-contract rule established via 1.x-vs-2.0 version distinction.")}),
"D095": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Tool-call harness; parser-dependence scaffold risk; paper counterpart at Evidence.",
  entity=("bfcl-gorilla", "BFCL / Berkeley Function-Calling Leaderboard (Gorilla repo)", "PRODUCT", "Berkeley"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["accuracy-to-harness-aware-eval"],
  inherit=None, caveat="Repo not fetched; leaderboard numbers are harness-bound (parser dependence) and cited for no fact.",
  claims=[
    ("BFCL evaluates tool/function-calling with a live leaderboard; parser dependence makes the harness part of the measured quantity.", "PROJECT_CLAIM", "Harness-role level; scaffold-risk framing per screening."),
    ("Paper counterpart linkage is required before citing any BFCL figure in the Special.", "INFERENCE", "Boundary rule.")],
  limits=["Repo and paper not consumed; no figure cited."],
  ver={"@FULL": ("VERIFIED", "Harness-role and scaffold-risk framing recorded; repo/paper bodies outstanding."),
        "paper counterpart; parser dependence": ("UNRESOLVED", "Paper counterpart not linked; parser-dependence audit outstanding.")}),
"D096": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Tool-interaction with pass^k consistency semantics binding.",
  entity=("tau-bench-2024", "tau-bench: A Benchmark for Tool-Agent-User Interaction (Yao et al., 2024)", "PAPER", "Sierra/Stanford"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["single-turn-to-interactive-tools"],
  inherit=None, caveat="Pass^k semantics must be stated with k; bare pass rates are not comparable.",
  claims=[
    ("tau-bench measures tool-agent-user interaction with pass^k consistency semantics over repeated trials.", "PRIMARY_FACT", "Design facts; abstract-level (2406.12045)."),
    ("Consistency-semantics binding (k, trials, user simulator) is required for any cited figure.", "INFERENCE", "Methodological rule.")],
  limits=["Full-body simulator and task design not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2406.12045): interactive tool benchmark with consistency semantics confirmed; full body outstanding.")}),
"D097": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="BrowseComp announcement-grade record; hard browsing benchmark but version/harness outstanding.",
  entity=("browsecomp", "BrowseComp (web-research agents, OpenAI announcement)", "PRODUCT", "OpenAI"),
  artifact="BENCHMARK", lineage="CONTEXT", branches=["benchmark-methodology"], transitions=["qa-to-browsing-agents"],
  inherit=None, caveat="Announcement-level only; version/harness outstanding.",
  claims=[
    ("BrowseComp is announced as a hard web-browsing research benchmark for agents.", "VENDOR_CLAIM", "Announcement-level only."),
    ("No version, harness, or score is cited from this record.", "INFERENCE", "Boundary statement.")],
  limits=["Announcement body not consumed; technical assessment outstanding."],
  ver={"@FULL": ("UNRESOLVED", "Locator-only announcement; technical body outstanding."),
        "version/harness": ("UNRESOLVED", "Version/harness unassessed.")}),
"D098": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Graded long-context suite; rare joint capability+efficiency datapoint class despite locator defect.",
  entity=("ruler-2024", "RULER: What's the Real Context Size of Your Long-Context Language Models? (Hsieh et al., 2024)", "PAPER", "NVIDIA/UIUC"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["claimed-context-to-effective-context"],
  inherit=None, caveat="Bound locator is a wrong-identity arXiv ID; claims rest on the true paper's established content.",
  claims=[
    ("RULER grades retrieval, multi-hop, aggregation, and QA behavior across escalating context lengths, distinguishing claimed from effective context size.", "AUTHOR_CLAIM", "Established content of the true paper (2404.06654); bound locator does not resolve to it."),
    ("Effective-context grading is the joint capability+efficiency datapoint class the Special needs for 1M-context capstone claims.", "INFERENCE", "Taxonomic significance."),
    ("Bound Discovery locator https://arxiv.org/abs/2404.18532 resolves to MileBench (MLLM long-context), not RULER.", "INFERENCE", "Verified via arXiv API; true identity 2404.06654 confirmed by title search.")],
  limits=["True-paper body not consumed beyond identity confirmation.", "Bound locator must be amended to 2404.06654 before locator-cited use."],
  ver={"@FULL": ("UNRESOLVED", "Locator-identity defect: bound 2404.18532 is MileBench. Gap-fill trigger G-EV-07: true identity arXiv 2404.06654 confirmed; amendment deferred to Sol.")}),
"D099": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="AIME/MAA competition authority; generation/year/CI conditions outstanding.",
  entity=("aime-maa", "AIME / MAA competition authority", "ORGANIZATION", "Mathematical Association of America"),
  artifact="BENCHMARK", lineage="CONTEXT", branches=["benchmark-methodology"], transitions=["contest-to-benchmark"],
  inherit=None, caveat="Competition problems are not an LLM benchmark per se; generation/year/conditions bind any citation.",
  claims=[
    ("The MAA owns the AIME competition problem stream reused across math reasoning evaluations (AIME24 and year variants).", "PROJECT_CLAIM", "Ownership-level; corroborated by D150's AIME24 evaluation."),
    ("Generation, year, and contamination-interval conditions must bind any AIME-derived figure.", "INFERENCE", "Methodological rule.")],
  limits=["Authority page not consumed; year/CI conditions outstanding."],
  ver={"@FULL": ("UNRESOLVED", "Locator-only; authority page outstanding."),
        "generation/year conditions": ("UNRESOLVED", "Year/CI pins enforced as rule; no citation audited.")}),
"D100": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="DeepSWE best-of-two-harness reporting note; cautionary validity exhibit, standalone primary outstanding.",
  entity=("deepswe-methodology-note", "DeepSWE-1.1 methodology note (harness dependence)", "PRODUCT", "Qwen"),
  artifact="BENCHMARK", lineage="CONTEXT", branches=["benchmark-methodology"], transitions=["single-harness-to-harness-aware"],
  inherit=None, caveat="Note-level record; standalone DeepSWE primary outstanding.",
  claims=[
    ("The note documents best-of-two-harness reporting for DeepSWE, making it a cautionary validity exhibit for harness-dependent figures.", "AUTHOR_CLAIM", "Note-level; consistent with D079's DeepSWE figures."),
    ("Harness-choice sensitivity of code-agent scores is the durable methodological point, not any DeepSWE number.", "INFERENCE", "Validity significance.")],
  limits=["Standalone DeepSWE primary not located; note body scoped to summary."],
  ver={"@FULL": ("VERIFIED", "Cautionary-exhibit role recorded; harness-sensitivity point established."),
        "standalone DeepSWE primary": ("UNRESOLVED", "Standalone primary outstanding; figures quarantined.")}),
}
