"""Evidence record specs Part A: D001-D032 (foundations, scaling, MoE origins, attention origins, early capstones)."""
PART_A = {
"D001": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Dense-scaling-era anchor for the D01 bottleneck model; revised but required origin for loss-scaling claims.",
  entity=("kaplan-scaling-laws-2020", "Scaling Laws for Neural Language Models (Kaplan et al., 2020)", "PAPER", "OpenAI/Johns Hopkins"),
  artifact="PAPER", lineage="BRIDGE", branches=["efficiency-fundamentals", "scaling-training"], transitions=["dense-scaling-to-chinchilla"],
  inherit=None, caveat="Power-law coefficients are era- and setup-specific; do not quote as current compute-optimal rule.",
  claims=[
    ("Kaplan et al. establish power-law scaling of LM loss in model size, data, and compute, the dense-scaling baseline the Special revises via Chinchilla and later refits.", "PRIMARY_FACT", "Abstract-level; loss-scaling form only, not coefficient values."),
    ("The paper's framing motivates the Special's D01 bottleneck separation: scale alone does not resolve inference-bound costs.", "INFERENCE", "Editorial bridge to EFF-O01; not a claim of the paper itself.")],
  limits=["Full-body coefficient tables and experimental setup not consumed; claims scoped to abstract-level scaling form."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed via arXiv API (id 2001.08361, pub 2020-01-23): power-law loss scaling confirmed; full-body coefficient tables outstanding.")}),
"D002": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Compute-optimal revision of dense scaling (~20 tok/param); motivates the training-token-reduction thread.",
  entity=("chinchilla-2022", "Training Compute-Optimal Large Language Models / Chinchilla (Hoffmann et al., 2022)", "PAPER", "DeepMind"),
  artifact="PAPER", lineage="CORE", branches=["scaling-training", "efficiency-fundamentals"], transitions=["dense-scaling-to-chinchilla"],
  inherit=None, caveat=None,
  claims=[
    ("Chinchilla finds prior large models undertrained and prescribes roughly equal scaling of model size and training tokens (~20 tokens/param), shifting the efficiency question toward data allocation.", "PRIMARY_FACT", "Abstract-level headline result."),
    ("The result underwrites the Special's training-token-reduction thread (dedup, DoReMi) and the Qwen/DeepSeek scaling-law refits.", "INFERENCE", "Editorial linkage; refit claims belong to D008/D124.")],
  limits=["Full-body isoFLOP curves and ablation tables not consumed; ratio quoted as the paper's headline prescription, not a universal constant."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2203.15556, pub 2022-03-12): equal model/data scaling and undertrained-prior finding confirmed; isoFLOP body outstanding.")}),
"D003": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Iteration-level scheduling origin; prefill/decode split anchors D01 and D08 serving lanes.",
  entity=("orca-osdi22", "Orca: A Distributed Serving System for Transformer Generative Models (OSDI'22)", "PAPER", "Microsoft Research"),
  artifact="PAPER", lineage="CORE", branches=["inference-serving", "efficiency-fundamentals"], transitions=["batching-to-continuous-batching"],
  inherit=None, caveat=None,
  claims=[
    ("Orca introduces iteration-level (continuous) scheduling for generative Transformers, replacing run-to-completion batching and separating prefill-phase from decode-phase scheduling.", "PRIMARY_FACT", "Well-established systems result; abstract-level."),
    ("Selective batching and distributed iteration scheduling in Orca are the direct ancestors of vLLM/SGLang scheduler design.", "AUTHOR_CLAIM", "Lineage claim; downstream adoption covered by D053-D055.")],
  limits=["Full-body scheduling algorithm details and throughput numbers not consumed; no numeric speedup quoted."],
  ver={"@FULL": ("VERIFIED", "Locator binds the USENIX OSDI'22 presentation page for the Orca paper; abstract-level mechanism confirmed; full paper body outstanding.")}),
"D004": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="2026 instance binding D01 distinctions to one deployment: FP8/FP4/FP8-KV, aggregated vs disaggregated topologies, DSpark topology-conditionality.",
  entity=("dynamo-v41-flash-recipe", "NVIDIA Dynamo DeepSeek-V4.1-Flash deployment recipe", "PRODUCT", "NVIDIA"),
  artifact="FRAMEWORK", lineage="CORE", branches=["capstone-2026-v41", "inference-serving"], transitions=["recipe-as-evidence"],
  inherit=None, caveat="Recipe numbers are configuration-bound (topology, precision, backend); do not generalize across stacks.",
  claims=[
    ("The Dynamo recipe documents FP8/FP4 compute with FP8 KV-cache deployment paths for DeepSeek-V4.1-Flash in aggregated and disaggregated topologies.", "PROJECT_CLAIM", "Scoped to the recipe's tested configurations."),
    ("DSpark speculative behavior in the recipe is topology-conditional, instantiating the Special's architecture-vs-runtime separation.", "INFERENCE", "Editorial synthesis from recipe structure.")],
  limits=["Recipe page body not consumed line-level this pass; claims scoped to Discovery summary plus D163 recipe consumption."],
  ver={"@FULL": ("VERIFIED", "Locator-bound recipe role confirmed; sibling vLLM recipe page (D163) fully consumed and corroborates FP8/FP4, DSpark-only, disaggregation claims."),
        "topology/precision binding at Evidence": ("UNRESOLVED", "Exact per-topology precision matrix from this specific Dynamo page not extracted; carried as limitation for Sol gap-fill judgment.")}),
"D005": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="FP8 format/algorithm origin for training and inference mixed precision; O02/O06 joint anchor despite locator defect.",
  entity=("fp8-formats-2022", "FP8 Formats for Deep Learning (Micikevicius et al., 2022)", "PAPER", "NVIDIA/ARM/Intel"),
  artifact="PAPER", lineage="CORE", branches=["precision-quantization", "scaling-training"], transitions=["fp32-to-fp8"],
  inherit=None, caveat="Bound locator is a wrong-identity arXiv ID (see verification); claims rest on the true paper's established content, not the bound bytes.",
  claims=[
    ("The FP8 paper defines the E4M3/E5M2 FP8 format pair and the mixed-precision training/inference methodology adopted by the DeepSeek V-line and MXFP4/MXFP8 serving paths.", "AUTHOR_CLAIM", "Community-established content of the true paper (2209.05433); bound locator does not resolve to it."),
    ("Bound Discovery locator https://arxiv.org/abs/2206.06277 resolves to an unrelated pipeline gas-flow paper, not the FP8 paper.", "INFERENCE", "Verified via arXiv API title check this pass; true identity 2209.05433 confirmed by direct ID fetch.")],
  limits=["True-paper body not consumed beyond identity confirmation; format details (exponent/mantissa split, scaling) stated at established-knowledge level.", "Bound locator must be amended to 2209.05433 before any locator-cited publication use."],
  ver={"@FULL": ("UNRESOLVED", "Locator-identity defect: bound 2206.06277 is not the FP8 paper. Gap-fill trigger G-EV-01: true identity arXiv 2209.05433 confirmed; Discovery locator amendment deferred to Sol.")}),
"D006": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="671B MoE FP8 training at scale; MTP pretraining objective later reused for speculative decoding.",
  entity=("deepseek-v3-report", "DeepSeek-V3 Technical Report (2024)", "PAPER", "DeepSeek-AI"),
  artifact="PAPER", lineage="CORE", branches=["scaling-training", "decoding-acceleration"], transitions=["mtp-objective-to-decoding"],
  inherit=None, caveat="V3 capability numbers are training-system claims; inference economics belong to the serving lane.",
  claims=[
    ("DeepSeek-V3 trains a 671B-parameter MoE with FP8 mixed precision at scale, demonstrating production FP8 training via fine-grained quantization and the DeepGEMM/DeepEP stack.", "PRIMARY_FACT", "Abstract-level; headline architecture and precision facts."),
    ("V3 introduces Multi-Token Prediction as a pretraining objective, the mechanism later reused for target-native speculative decoding in 2026 capstones.", "PRIMARY_FACT", "MTP objective origin within the DeepSeek line.")],
  limits=["Full 2412.19437 body (training infra, evaluation tables) not consumed; no benchmark numbers quoted."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2412.19437): 671B MoE, FP8 training, MTP objective confirmed at headline level; full-body tables outstanding.")}),
"D007": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Orthogonalized-gradient optimizer adopted by Qwen3.8-Flash-Next and reported for V4-Flash pretraining.",
  entity=("muon-optimizer", "Muon optimizer reference implementation (Keller Jordan)", "FRAMEWORK", "Community (Keller Jordan)"),
  artifact="FRAMEWORK", lineage="BRIDGE", branches=["scaling-training"], transitions=["adamw-to-muon"],
  inherit=None, caveat="Repository code not audited; adoption claims rest on capstone first-party reports, not this repo's bytes.",
  claims=[
    ("Muon applies Newton-Schulz orthogonalization to gradient updates, reported by Qwen3.8-Flash-Next and DeepSeek-V4-line reports as improving training stability and permitting higher learning rates.", "AUTHOR_CLAIM", "Adoption facts per D008/D124 abstracts; optimizer theory at established-knowledge level."),
    ("The bound locator is the community reference implementation, not a paper; no convergence theorem is sourced to it.", "INFERENCE", "Source-class boundary statement.")],
  limits=["Repository code and experiment logs not audited; optimizer mathematics stated from community-established descriptions."],
  ver={"@FULL": ("VERIFIED", "Locator role confirmed (reference implementation); adoption corroborated by two first-party abstracts (2608.30320, 2606.19348)."),
        "adoption claims in capstone reports": ("VERIFIED", "Qwen3.8-Next abstract: Muon shifts optimal LR/batch upward, removes warmup need. V4 abstract: Muon listed as key upgrade.")}),
"D008": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Qwen3.8-Flash-Next architecture report: 125B/6B + 51B host n-gram, GDN/QSA, Muon, scaling-law refit; vendor ratios quarantined.",
  entity=("qwen38-next-arch", "On the Design of Qwen3.8-Next Architecture (Qwen Team, 2026)", "PAPER", "Alibaba Qwen"),
  artifact="PAPER", lineage="CORE", branches=["capstone-2026-qwen", "conditional-compute", "attention-kv"], transitions=["qwen-lineage-to-flash-next"],
  inherit=None, caveat="1/3-tokens/1/9-FLOPs ratios are vendor self-comparisons vs the 397B-A17B predecessor under the report's harness; not independent facts.",
  claims=[
    ("Qwen3.8-Flash-Next is a 125B-parameter sparse MoE (6B active/token) with 51B of n-gram embedding tables held off-accelerator, mixing Gated DeltaNet and global attention 3:1 with QSA sparse attention at continued-pretraining time.", "AUTHOR_CLAIM", "First-party report abstract, consumed via arXiv API (2608.30320, pub 2026-08-31)."),
    ("The report claims 1/3 the activated parameters, 1/3 the training tokens and ~1/9 the training FLOPs vs its 397B-A17B predecessor at competitive accuracy (8/14 pretraining benchmarks led, rest within 2.6 pts).", "VENDOR_CLAIM", "Self-reported; harness and benchmark list bind the comparison."),
    ("Architecture and Muon together shift optimal LR/batch upward, remove batch warmup, and improve stress-test stability; loss and downstream accuracy do not always move together (n-gram vocab lowers loss monotonically while accuracy saturates).", "AUTHOR_CLAIM", "Stability-accounting findings from the abstract; material to the training-efficiency lane.")],
  limits=["Full-body ablations, benchmark tables, and harness appendices not consumed; vendor ratios quarantined pending independent reproduction.", "Host-offload bandwidth/latency costs of the 51B n-gram tables not quantified from the abstract."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed in full: architecture, ratios, stability findings extracted; full-body ablations outstanding."),
        "vendor-claimed 1/3 tokens / 1/9 FLOPs quarantine": ("VERIFIED", "Ratios recorded strictly as vendor self-comparison with predecessor/scope bounds; not promoted to independent fact.")}),
"D009": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Qwen3-Next announcement: 3:1 GDN:attention hybrid claim; ancestor statement for the Qwen3.5-3.8 lineage.",
  entity=("qwen3-next-blog", "Qwen3-Next: Towards Ultimate Training & Inference Efficiency (Qwen blog)", "PRODUCT", "Alibaba Qwen"),
  artifact="PRODUCT", lineage="BRIDGE", branches=["capstone-2026-qwen"], transitions=["qwen-lineage-to-flash-next"],
  inherit=None, caveat="Vendor announcement; lineage claims checked against the later technical report, not taken alone.",
  claims=[
    ("The Qwen3-Next announcement states a 3:1 Gated-DeltaNet-to-attention hybrid direction pursued for joint training/inference efficiency.", "VENDOR_CLAIM", "Announcement-level; superseded in detail by D008."),
    ("The post serves as the dated ancestor statement for the Qwen3.5-3.8 lineage continued by the Qwen3.8-Flash-Next report.", "INFERENCE", "Lineage linkage corroborated by D008's architecture continuity.")],
  limits=["Announcement page body not fetched; claims scoped to Discovery summary with D008 corroboration."],
  ver={"@FULL": ("VERIFIED", "Announcement role and hybrid-ratio claim corroborated against the later first-party report D008."),
        "lineage claims vs report": ("VERIFIED", "Lineage continuity (GDN hybrid, Muon, efficiency thesis) confirmed in D008 abstract; no contradiction found.")}),
"D010": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="MoE origin: learned sparse top-k gating, load-balance loss, capacity/compute separation.",
  entity=("shazeer-sparse-moe-2017", "Outrageously Large Neural Networks: The Sparsely-Gated Mixture-of-Experts Layer (Shazeer et al., 2017)", "PAPER", "Google"),
  artifact="PAPER", lineage="CORE", branches=["conditional-compute-moe"], transitions=["dense-to-sparse-gating"],
  inherit=None, caveat="LSTM-era origin; routing mechanics persist but scale/context conclusions do not transfer directly to LLM MoE.",
  claims=[
    ("Shazeer et al. introduce learned sparse top-1/top-k gating with an auxiliary load-balancing loss, separating parameter capacity from per-token compute.", "PRIMARY_FACT", "Textbook-level established result; abstract-level."),
    ("The gating + load-balance formulation is the mechanism ancestor of GShard, Switch, and all later top-k routing variants in this Special.", "INFERENCE", "Lineage synthesis across D011-D015.")],
  limits=["Full-body gating equations and LSTM experimental tables not consumed; mechanism stated at survey level."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (1701.06538): sparsely-gated MoE layer, load balancing confirmed; full body outstanding.")}),
"D011": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Production MoE: expert parallelism, sharded dispatch, capacity-factor mechanics.",
  entity=("gshard-2020", "GShard: Scaling Giant Models with Conditional Computation and Automatic Sharding (Lepikhin et al., 2020)", "PAPER", "Google"),
  artifact="PAPER", lineage="CORE", branches=["conditional-compute-moe"], transitions=["moe-to-production"],
  inherit=None, caveat=None,
  claims=[
    ("GShard scales MoE beyond single-device memory via expert parallelism with sharded dispatch, introducing capacity-factor mechanics for token overflow handling.", "PRIMARY_FACT", "Established systems result; abstract-level."),
    ("Automatic sharding makes sparse scaling compiler-manageable, a precondition for later trillion-parameter MoE training systems.", "AUTHOR_CLAIM", "Interpretive significance claim at survey level.")],
  limits=["Full-body sharding annotations and translation-benchmark tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2006.16668): conditional computation + automatic sharding confirmed; full body outstanding.")}),
"D012": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Top-1 routing simplification; routing-strategy quality/communication tradeoff reference.",
  entity=("switch-transformer-2021", "Switch Transformers: Scaling to Trillion Parameter Models (Fedus et al., 2021)", "PAPER", "Google"),
  artifact="PAPER", lineage="CORE", branches=["conditional-compute-moe"], transitions=["topk-to-top1"],
  inherit=None, caveat=None,
  claims=[
    ("Switch simplifies MoE routing to top-1 expert selection with load-balancing loss, trading routing expressivity for reduced communication and simpler dispatch.", "PRIMARY_FACT", "Headline result; abstract-level."),
    ("Top-1 vs top-k is the canonical routing-strategy tradeoff referenced when evaluating fine-grained and shared-expert variants (DeepSeekMoE, Qwen).", "INFERENCE", "Taxonomic linkage to D014/D015.")],
  limits=["Full-body scaling curves and multilingual tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2101.03961): top-1 routing simplification confirmed; full body outstanding.")}),
"D013": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="8x7B open-weight MoE; sparse activation adoption outside Chinese labs.",
  entity=("mixtral-2024", "Mixtral of Experts (Jiang et al., 2024)", "PAPER", "Mistral AI"),
  artifact="PAPER", lineage="CORE", branches=["conditional-compute-moe"], transitions=["moe-to-open-weights"],
  inherit=None, caveat=None,
  claims=[
    ("Mixtral is an 8x7B open-weight MoE activating ~13B parameters per token via top-2 routing, demonstrating competitive sparse-activation quality outside large closed labs.", "PRIMARY_FACT", "Widely reported headline facts; abstract-level."),
    ("Its release marks the open-weights inflection for MoE serving concerns (expert residency, offload, routing overhead) in the community lane.", "INFERENCE", "Editorial significance for the D07 local-inference thread.")],
  limits=["Full-body routing analyses and benchmark tables not consumed; active-param figure stated at established level."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2401.04088): 8x7B MoE identity confirmed; full body outstanding.")}),
"D014": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Fine-grained + shared experts, device-limited routing; DeepSeek branch mechanism authority.",
  entity=("deepseekmoe-2024", "DeepSeekMoE: Towards the Ultimate Specialist Lexicon (DeepSeek-AI, 2024)", "PAPER", "DeepSeek-AI"),
  artifact="PAPER", lineage="CORE", branches=["conditional-compute-moe"], transitions=["coarse-to-fine-grained-experts"],
  inherit=None, caveat=None,
  claims=[
    ("DeepSeekMoE segments experts into fine-grained specialists plus shared experts that capture common knowledge, with device-limited routing constraining communication.", "PRIMARY_FACT", "Abstract-level mechanism facts."),
    ("Fine-grained/shared-expert design is the routing mechanism inherited by DeepSeek-V2/V3 and the 2026 V4-line capstones.", "INFERENCE", "Lineage claim corroborated by V4/V4.1 architecture continuity.")],
  limits=["Full-body ablation tables (expert granularity sweeps) not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2401.06066): fine-grained + shared expert mechanism confirmed; full body outstanding.")}),
"D015": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="236B/21B MLA + DeepSeekMoE; efficiency as first-class architectural claim.",
  entity=("deepseek-v2-2024", "DeepSeek-V2: A Strong, Economical, and Efficient Mixture-of-Experts Language Model (2024)", "PAPER", "DeepSeek-AI"),
  artifact="PAPER", lineage="CORE", branches=["conditional-compute-moe", "attention-kv"], transitions=["mha-to-mla"],
  inherit=None, caveat=None,
  claims=[
    ("DeepSeek-V2 combines DeepSeekMoE with Multi-Head Latent Attention (MLA) at 236B total / 21B active parameters, making KV-compression and sparse-compute joint first-class claims.", "PRIMARY_FACT", "Headline architecture facts; abstract-level."),
    ("V2 is the branch point where MLA enters the DeepSeek line, conditioning DSA/CSA/CSA2 and the V4-line KV story.", "INFERENCE", "Lineage synthesis across D025/D123-D125.")],
  limits=["Full-body MLA formulation and benchmark tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2405.04434): 236B/21B MoE + MLA identity confirmed; full body outstanding.")}),
"D016": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Qwen dense/MoE breadth preceding efficiency generations; lineage adoption evidence.",
  entity=("qwen3-report-2025", "Qwen3 Technical Report (Qwen Team, 2025)", "PAPER", "Alibaba Qwen"),
  artifact="PAPER", lineage="BRIDGE", branches=["conditional-compute-moe"], transitions=["qwen-lineage-to-flash-next"],
  inherit=None, caveat="Family-breadth anchor; efficiency-specific claims belong to D008/D009, not this report.",
  claims=[
    ("The Qwen3 report documents the dense-and-MoE family breadth (0.6B-235B classes) that precedes the efficiency-focused Qwen3-Next/3.8 generations.", "PRIMARY_FACT", "Family-scope fact; abstract-level."),
    ("Lineage continuity (Qwen3 MoE variants into Qwen3-Next hybrids) supports the adoption reading of GDN/QSA mechanisms.", "INFERENCE", "Lineage linkage, corroborated by D008.")],
  limits=["Full-body family benchmark tables not consumed; no per-model numbers quoted."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2505.09388): Qwen3 family report identity confirmed; full body outstanding.")}),
"D017": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="DeepSeek-V4-Flash card: 284B/13B, CSA+HCA, mHC, FP4+FP8; B200-conditional facts.",
  entity=("deepseek-v4-flash-card", "DeepSeek-V4-Flash model card (Hugging Face)", "PRODUCT", "DeepSeek-AI"),
  artifact="MODEL", lineage="CORE", branches=["capstone-2026-v41"], transitions=["v4-to-v41"],
  inherit=None, caveat="Card figures (license strings, precision variants) are distribution metadata; architecture ground truth is the V4 report D124.",
  claims=[
    ("The V4-Flash card identifies a 284B/13B MoE checkpoint with CSA+HCA hybrid attention, manifold-constrained hyper-connections, and FP4-expert/FP8 mixed precision.", "PROJECT_CLAIM", "Card metadata; architecture corroborated by D124 abstract (1.6T/49B Pro + 284B/13B Flash, CSA+HCA, mHC, Muon)."),
    ("Deployment-relevant card facts (precision variants, license strings per mirror) require version binding at Evidence and are not quoted as settled.", "INFERENCE", "Boundary statement; mirrors may diverge.")],
  limits=["Card page body not fetched; figures corroborated only via the V4 report abstract."],
  ver={"@FULL": ("VERIFIED", "Card role and architecture facts corroborated against first-party report D124; card body outstanding."),
        "license/precision variant binding": ("UNRESOLVED", "Per-mirror license/precision strings not pinned; retained as limitation, not cited.")}),
"D018": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Single shared KV head; KV-footprint reduction thread origin.",
  entity=("mqa-2019", "Fast Transformer Decoding: One Write-Head Is All You Need / MQA (Shazeer, 2019)", "PAPER", "Google"),
  artifact="PAPER", lineage="CORE", branches=["attention-kv"], transitions=["mha-to-mqa"],
  inherit=None, caveat=None,
  claims=[
    ("MQA shares a single key/value head across all query heads, cutting KV-cache footprint by roughly the head-count factor at some quality cost.", "PRIMARY_FACT", "Established mechanism; abstract-level."),
    ("MQA opens the KV-sharing lineage continued by GQA and MLA in this Special.", "INFERENCE", "Lineage synthesis to D019/D015.")],
  limits=["Full-body quality-degradation tables not consumed; no numeric tradeoff quoted."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (1911.02150): single-write-head mechanism confirmed; full body outstanding.")}),
"D019": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Grouped KV heads via uptraining; pre-MLA industry-default KV saver.",
  entity=("gqa-2023", "GQA: Training Generalized Multi-Query Transformers from Multi-Head Checkpoints (Ainslie et al., 2023)", "PAPER", "Google"),
  artifact="PAPER", lineage="CORE", branches=["attention-kv"], transitions=["mqa-to-gqa"],
  inherit=None, caveat=None,
  claims=[
    ("GQA groups query heads over shared KV heads and can be reached by uptraining from MHA checkpoints, making it the industry-default KV saver before MLA.", "PRIMARY_FACT", "Headline mechanism + uptraining facts; abstract-level."),
    ("Uptraining convertibility is what made GQA deployable without full retraining, the property later demanded of sparse-attention retrofits.", "AUTHOR_CLAIM", "Interpretive significance at survey level.")],
  limits=["Full-body uptraining cost tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2305.13245): grouped-query + uptraining mechanism confirmed; full body outstanding.")}),
"D020": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="IO-aware EXACT attention; tiling + online softmax; implementation efficiency, not approximation.",
  entity=("flashattention-2022", "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness (Dao et al., 2022)", "PAPER", "Stanford"),
  artifact="PAPER", lineage="CORE", branches=["attention-kv"], transitions=["naive-to-io-aware-attention"],
  inherit=None, caveat="Speedups are hardware- and shape-conditional; exactness claim is the durable part, not any single speedup factor.",
  claims=[
    ("FlashAttention computes exact attention with tiling and online softmax to minimize HBM reads/writes, yielding large wall-clock speedups without approximation.", "PRIMARY_FACT", "Core exactness + IO-awareness claims; abstract-level."),
    ("Its exactness distinguishes IO-efficiency work from compute/storage-changing architectures (sparse, linear, SSM) throughout the Special's taxonomy.", "INFERENCE", "Taxonomic distinction central to EFF-O04.")],
  limits=["Full-body IO-complexity proofs and benchmark tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2205.14135): IO-aware exact attention confirmed; full body outstanding.")}),
"D021": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Parallelism/partitioning rework, ~2x over FA1; still exact, KV asymptotics unchanged.",
  entity=("flashattention2-2023", "FlashAttention-2: Faster Attention with Better Parallelism and Work Partitioning (Dao, 2023)", "PAPER", "Princeton"),
  artifact="PAPER", lineage="CORE", branches=["attention-kv"], transitions=["fa1-to-fa2"],
  inherit=None, caveat=None,
  claims=[
    ("FlashAttention-2 reworks parallelism and work partitioning for roughly 2x speedup over FA1 while remaining exactly equivalent attention.", "PRIMARY_FACT", "Headline speedup + exactness; abstract-level."),
    ("KV-cache asymptotics are unchanged by FA2; memory-capacity relief comes from MQA/GQA/MLA/sparse lines, not FlashAttention.", "INFERENCE", "Boundary statement for the taxonomy.")],
  limits=["Full-body partitioning details and A100/H100 tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2307.08691): parallelism rework + ~2x confirmed; full body outstanding.")}),
"D022": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Hopper asynchrony/FP8; hardware-conditional gains instance.",
  entity=("flashattention3-2024", "FlashAttention-3: Fast and Accurate Attention with Asynchrony and Low-precision (Shah et al., 2024)", "PAPER", "Princeton/Columbia/NVIDIA"),
  artifact="PAPER", lineage="CORE", branches=["attention-kv"], transitions=["fa2-to-fa3"],
  inherit=None, caveat="Gains are Hopper-specific (WGMMA asynchrony, FP8); not portable speedup claims.",
  claims=[
    ("FlashAttention-3 exploits Hopper asynchrony and low-precision (FP8) paths for further attention speedups at preserved accuracy.", "PRIMARY_FACT", "Headline mechanism; abstract-level."),
    ("FA3 is the Special's canonical instance of hardware-conditional gains: same mathematics, different realized efficiency per accelerator generation.", "INFERENCE", "Editorial framing for D01 hardware binding.")],
  limits=["Full-body async-pipeline details and Hopper benchmark tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2407.08608): asynchrony + low-precision mechanism confirmed; full-body tables outstanding."),
        "hardware conditions": ("VERIFIED", "Hopper-conditionality recorded from the paper's own framing; no cross-hardware generalization made.")}),
"D023": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Selective SSM alternative; lineage anchor for GDN/KDA responses.",
  entity=("mamba-2023", "Mamba: Linear-Time Sequence Modeling with Selective State Spaces (Gu & Dao, 2023)", "PAPER", "CMU/Princeton"),
  artifact="PAPER", lineage="CORE", branches=["attention-kv"], transitions=["attention-to-selective-ssm"],
  inherit=None, caveat=None,
  claims=[
    ("Mamba introduces input-dependent selectivity into state-space models with a hardware-aware parallel scan, achieving linear-time sequence mixing competitive with Transformers at scale.", "PRIMARY_FACT", "Headline mechanism + scaling claim; abstract-level."),
    ("Selective-SSM pressure is the lineage context for Gated DeltaNet and Kimi Delta Attention as recurrent-side answers.", "INFERENCE", "Lineage synthesis to D024/D027.")],
  limits=["Full-body scan formulation and scaling tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2312.00752): selective SSM + linear-time claims confirmed; full body outstanding.")}),
"D024": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Scalar-gated delta rule; direct parent of KDA and recurrent half of 2026 hybrids.",
  entity=("gated-deltanet-2024", "Gated DeltaNet (Yang et al., 2024)", "PAPER", "Microsoft Research"),
  artifact="PAPER", lineage="CORE", branches=["attention-kv"], transitions=["mamba2-to-gated-deltanet"],
  inherit=None, caveat=None,
  claims=[
    ("Gated DeltaNet adds scalar gating to the delta update rule, improving on Mamba2-style recurrence with delta-rule memory control.", "PRIMARY_FACT", "Headline mechanism; abstract-level."),
    ("GDN is the direct recurrent parent of Kimi Delta Attention and the recurrent half of Qwen3.8-Flash-Next's 3:1 hybrid.", "INFERENCE", "Lineage claims corroborated by D027/D008 abstracts.")],
  limits=["Full-body gating ablations not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2412.06464): gated delta rule mechanism confirmed; full body outstanding.")}),
"D025": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="SWA + GQA local-attention baseline for sparse/retrieval comparisons.",
  entity=("mistral-7b-2023", "Mistral 7B (Jiang et al., 2023)", "PAPER", "Mistral AI"),
  artifact="PAPER", lineage="BRIDGE", branches=["attention-kv"], transitions=["full-to-sliding-window"],
  inherit=None, caveat="SWA window size and reported quality are model-specific; cited as baseline pattern, not a portable constant.",
  claims=[
    ("The Mistral 7B report establishes sliding-window attention combined with GQA as a production local-attention baseline.", "PRIMARY_FACT", "Architecture facts; abstract-level."),
    ("SWA is the reference local-attention pattern against which NSA/DSA/CSA sparse-global designs and SWA-replay schemes are compared.", "INFERENCE", "Taxonomic role in the Special.")],
  limits=["Full-body SWA ablation tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2310.06825): SWA + GQA baseline identity confirmed; full body outstanding.")}),
"D026": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Hierarchical compress-select-slide trained end-to-end; disambiguate vs DSA/CSA/QSA.",
  entity=("nsa-2025", "Native Sparse Attention: Hardware-Aligned and Natively Trainable Sparse Attention (Yuan et al., 2025)", "PAPER", "DeepSeek-AI/Univ. of Washington"),
  artifact="PAPER", lineage="CORE", branches=["attention-kv"], transitions=["sparse-attention-family"],
  inherit=None, caveat="NSA is distinct from DeepSeek's DSA and Qwen's QSA despite shared vocabulary (indexer, selection); conflation prohibited.",
  claims=[
    ("NSA trains a hierarchical compress-select-slide sparse attention end-to-end with hardware-aligned kernels, separating it from inference-only sparsification retrofits.", "PRIMARY_FACT", "Headline mechanism; abstract-level."),
    ("NSA vs DSA vs CSA vs QSA disambiguation is load-bearing for the Special: different indexers, different sharing, different training regimes.", "INFERENCE", "Taxonomic boundary statement.")],
  limits=["Full-body kernel details and speedup tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2502.11089): hierarchical natively-trainable sparse attention confirmed; full body outstanding."),
        "disambiguation vs DSA/CSA/QSA": ("VERIFIED", "NSA identity separated from DSA (D125), CSA/CSA2 (D124/D123), QSA (D008) at mechanism level.")}),
"D027": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="KDA + 3:1 MLA hybrid, NoPE; 48B/3B; claimed fair-comparison win; KV -75%, 6x decode at 1M.",
  entity=("kimi-linear-2025", "Kimi Linear: An Expressive, Efficient Attention Architecture (Moonshot AI, 2025)", "PAPER", "Moonshot AI"),
  artifact="PAPER", lineage="CORE", branches=["capstone-2026-kimi", "attention-kv"], transitions=["gdn-to-kda"],
  inherit=None, caveat="Fair-comparison wins and 6x-decode figures are first-party measurements under the report's recipe; independent reproduction via D028 pending.",
  claims=[
    ("Kimi Linear centers on Kimi Delta Attention, extending Gated DeltaNet with finer-grained gating for limited finite-state RNN memory, in a layerwise KDA/MLA hybrid (NoPE).", "AUTHOR_CLAIM", "Report abstract consumed (2510.26692, pub 2025-10-30)."),
    ("The report claims identical-recipe wins over full MLA across short/long-context and RL-scaling regimes, with up to 75% KV-cache reduction and 6x decode throughput at 1M context for a 48B/3B model.", "VENDOR_CLAIM", "Self-reported; recipe- and context-bound."),
    ("KDA kernel plus vLLM implementation and 5.7T-token checkpoints are open-sourced, giving deployment-grade corroboration surface.", "PROJECT_CLAIM", "Release facts per abstract; implementation evidence in D028/D132.")],
  limits=["Full-body fair-comparison protocols and throughput measurement setups not consumed; vendor numbers quarantined."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed in full: KDA mechanism, hybrid, NoPE, 48B/3B, KV/throughput claims extracted; full-body protocols outstanding."),
        "fair-comparison and KV/decode claims": ("VERIFIED", "Claims recorded strictly as first-party with recipe/context bounds; independent reproduction status open (see D028).")}),
"D028": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Deployment authority: open KDA kernel + vLLM implementation + 5.7T checkpoints.",
  entity=("kimi-linear-repo", "MoonshotAI/Kimi-Linear (GitHub)", "PRODUCT", "Moonshot AI"),
  artifact="MODEL", lineage="CORE", branches=["capstone-2026-kimi", "inference-serving"], transitions=["paper-to-deployment"],
  inherit=None, caveat="Repository not audited line-level; release-existence facts only, not kernel-correctness certification.",
  claims=[
    ("The Kimi-Linear repository publishes the KDA kernel, vLLM integration path, and model checkpoints, constituting deployment authority beyond the paper.", "PROJECT_CLAIM", "Release-existence level; code unaudited."),
    ("Open checkpoints enable third-party fair-comparison reproduction of D027's claims, which is currently the missing independent leg.", "INFERENCE", "Reproduction-pathway statement.")],
  limits=["Codebase not cloned or audited; no independent reproduction executed this pass."],
  ver={"@FULL": ("VERIFIED", "Repository role as deployment authority confirmed at release-existence level; code audit outstanding."),
        "kernel/runtime version binding": ("UNRESOLVED", "Exact kernel/runtime commit pins not extracted; deferred to Sol gap-fill judgment.")}),
"D029": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Qwen3.8-Flash-Next README: 125B/6B + 51B n-gram host-offload; 12x(3xGDN->1xQSA); MTP 1 layer; self-reported scores.",
  entity=("qwen38-flash-next-card", "Qwen/Qwen3.8-Flash-Next README (Hugging Face)", "PRODUCT", "Alibaba Qwen"),
  artifact="MODEL", lineage="CORE", branches=["capstone-2026-qwen"], transitions=["report-to-checkpoint"],
  inherit=None, caveat="README benchmark scores are self-reported under vendor harness; QSA/PLE config facts are the durable content.",
  claims=[
    ("The README pins the 125B/6B + 51B host-offloaded n-gram configuration, the 3xGDN-to-1xQSA layer pattern, and a single MTP layer.", "PROJECT_CLAIM", "Configuration facts; architecture corroborated by D008."),
    ("Self-reported benchmark scores on the card are quarantined as vendor claims pending harness-bound verification.", "INFERENCE", "Boundary statement.")],
  limits=["Card page body not fetched; config facts corroborated via D008/D127 only."],
  ver={"@FULL": ("VERIFIED", "Configuration facts corroborated against D008 report abstract and D127 repo role; card body outstanding."),
        "self-reported scores quarantine": ("VERIFIED", "Scores excluded from fact claims; quarantine boundary recorded.")}),
"D030": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="DeepSeek-V4.1-Flash card: 552B + 196B Engram; 8B-prefill/16B-decode CED; CSA2; FP4 KV 890B/tok; SWA replay; DSpark.",
  entity=("deepseek-v41-flash-card", "deepseek-ai/DeepSeek-V4.1-Flash model card (Hugging Face)", "PRODUCT", "DeepSeek-AI"),
  artifact="MODEL", lineage="CORE", branches=["capstone-2026-v41"], transitions=["v4-to-v41"],
  inherit=None, caveat="Card spec figures inherit the tech report's authority; card-only strings (license, file layout) are distribution metadata.",
  claims=[
    ("The card identifies the 552B-backbone + 196B-Engram checkpoint with CED (8B prefill / 16B decode active), CSA2 sparse attention, FP4 KV at 890 bytes/token, SWA bounded replay, and DSpark drafting.", "PROJECT_CLAIM", "Spec facts corroborated by D123 report abstract and D163 recipe consumption."),
    ("Precision/format bindings (MXFP4 experts, MXFP8, FP4 KV) determine serving requirements and are backend-conditional (B200-class for FP4 paths).", "INFERENCE", "Deployment reading corroborated by D163.")],
  limits=["Card page body not fetched; spec figures rest on report + recipe corroboration."],
  ver={"@FULL": ("VERIFIED", "Spec facts corroborated against D123 abstract and fully-consumed D163 recipe; card body outstanding."),
        "spec/precision binding": ("VERIFIED", "MXFP4/MXFP8/FP4-KV bindings confirmed via D163; B200-conditionality recorded.")}),
"D031": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Official V4.1-Flash launch: 552B MoE; KV 1/4 HBM 1/8 SSD; API live; peak/off-peak pricing.",
  entity=("deepseek-v41-launch", "Introducing DeepSeek-V4.1-Flash (DeepSeek official launch)", "PRODUCT", "DeepSeek-AI"),
  artifact="PRODUCT", lineage="CORE", branches=["capstone-2026-v41"], transitions=["report-to-launch"],
  inherit=None, caveat="Launch-page ratios and prices are vendor statements dated to launch; paper URL outstanding per summary.",
  claims=[
    ("The launch page announces the 552B MoE with 1/4 HBM and 1/8 SSD KV-cache reductions, live API, and peak/off-peak pricing.", "VENDOR_CLAIM", "Announcement-level; ratios corroborated by D123 abstract (890B/tok global, SWA replay persistent)."),
    ("The launch is the dated efficiency-to-price transmission event for the V4.1 capstone case study.", "INFERENCE", "Editorial role assignment.")],
  limits=["Launch page body not fetched; technical-report URL outstanding at announcement level."],
  ver={"@FULL": ("VERIFIED", "Announcement role and KV-ratio claims corroborated against D123 abstract; page body outstanding."),
        "paper/benchmark identity": ("UNRESOLVED", "Launch-bound paper/benchmark URLs not pinned from this page; D123 report covers the technical leg.")}),
"D032": dict(status="PARTIAL", mat="HOLD",
  mat_rationale="DSA trace held: homepage-only bound locator carries no technical authority; dedicated first-party URLs isolated this pass but not yet bound.",
  entity=("deepseek-v32exp-dsa-trace", "DeepSeek V3.2-Exp / DeepSeek Sparse Attention trace", "PRODUCT", "DeepSeek-AI"),
  artifact="PRODUCT", lineage="CORE", branches=["capstone-2026-v41", "attention-kv"], transitions=["mla-to-dsa"],
  inherit=None, caveat="No technical claim may be sourced to the generic homepage; DSA substance lives in D125/D126 and the isolated URLs below.",
  claims=[
    ("The bound locator (https://www.deepseek.com/) is the generic DeepSeek homepage and carries no DSA technical authority.", "INFERENCE", "Boundary finding from locator inspection."),
    ("Dedicated first-party DSA authorities exist: the V3.2-Exp launch page (https://www.deepseek.com/en/news/v3-2-exp/, debuts DSA, 50%+ API price cut, HF weights + GitHub tech report + TileLang/CUDA kernels) and the V3.2 page (https://www.deepseek.com/en/news/deepseek-v3-2/).", "INFERENCE", "Gap-fill isolation via web search this pass; pages summarized from search excerpts, bodies not fully consumed.")],
  limits=["Homepage binds no technical body; isolated dedicated pages not consumed in full and not bound as sources.", "DSA technical substance for the Special rests on D125 (report) and D126 (launch + docs), not on D032."],
  ver={"@FULL": ("UNRESOLVED", "Bound locator has no consumable technical body; record retained as trace only."),
        "isolate dedicated DSA primary URL": ("VERIFIED", "Two dedicated first-party URLs isolated (v3-2-exp launch, deepseek-v3-2 page) plus API-docs mirror; gap-fill trigger G-EV-02 recorded, binding deferred to Sol.")}),
}
