"""Evidence record specs Part D: D101-D142 (training systems, KV-cache management, conditional depth, methodology anchors, 2026 capstones, Jev docs)."""
PART_D = {
"D101": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Intra-layer tensor splitting; SCALE/PLACE, not arithmetic reduction.",
  entity=("megatron-lm-2019", "Megatron-LM: Training Multi-Billion Parameter Language Models Using Model Parallelism (Shoeybi et al., 2019)", "PAPER", "NVIDIA"),
  artifact="PAPER", lineage="CORE", branches=["scaling-training"], transitions=["single-device-to-tensor-parallel"],
  inherit=None, caveat="Placement technique: enables scale, does not reduce arithmetic; direction must be recorded explicitly.",
  claims=[
    ("Megatron-LM introduces intra-layer tensor (model) parallelism with minimal communication ops, training 8.3B-parameter Transformers at 15.1 PetaFLOPs with 76% scaling efficiency on 512 GPUs.", "PRIMARY_FACT", "Headline scale + efficiency figures; abstract consumed (1909.08053)."),
    ("Tensor parallelism is classified SCALE/PLACE in the Special's direction taxonomy: it fits larger models, it does not reduce FLOPs.", "INFERENCE", "Taxonomic classification.")],
  limits=["Full-body communication-op design not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (1909.08053): intra-layer parallelism + scale figures confirmed; full body outstanding.")}),
"D102": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Micro-batch pipeline + recompute; bubble/memory tradeoff origin.",
  entity=("gpipe-2018", "GPipe: Efficient Training of Giant Neural Networks using Pipeline Parallelism (Huang et al., 2018)", "PAPER", "Google"),
  artifact="PAPER", lineage="CORE", branches=["scaling-training"], transitions=["single-device-to-pipeline-parallel"],
  inherit=None, caveat=None,
  claims=[
    ("GPipe pipelines layer subsequences across accelerators with micro-batch splitting, achieving near-linear speedups plus activation recomputation for memory.", "PRIMARY_FACT", "Headline mechanism + effects; abstract consumed (1811.06965)."),
    ("Pipeline bubbles vs memory savings is the origin tradeoff for all later pipeline schedules.", "INFERENCE", "Tradeoff significance.")],
  limits=["Full-body partitioning algorithm not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (1811.06965): pipeline + micro-batch mechanism confirmed; full body outstanding.")}),
"D103": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Sharded optimizer/gradient/parameter states; FIT (memory), not FLOPs.",
  entity=("zero-2019", "ZeRO: Memory Optimizations Toward Training Trillion Parameter Models (Rajbhandari et al., 2019)", "PAPER", "Microsoft Research"),
  artifact="PAPER", lineage="CORE", branches=["scaling-training"], transitions=["replicated-to-sharded-states"],
  inherit=None, caveat="FIT direction: ZeRO saves memory at communication cost; it does not reduce training FLOPs.",
  claims=[
    ("ZeRO eliminates memory redundancy in data/model-parallel training by sharding optimizer states, gradients, and parameters, scaling trainable size with device count.", "PRIMARY_FACT", "Headline mechanism; abstract consumed (1910.02054)."),
    ("ZeRO is classified FIT in the direction taxonomy; FSDP (D106) is its PyTorch-native ZeRO-3-class continuation.", "INFERENCE", "Taxonomic + lineage linkage.")],
  limits=["Full-body communication-volume analysis not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (1910.02054): sharded-states mechanism confirmed; full body outstanding.")}),
"D104": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="CPU/NVMe offload with bandwidth-aware scheduling; ancestor of host-offload inference thinking.",
  entity=("zero-offload-2021", "ZeRO-Offload: Democratizing Billion-Scale Model Training (Ren et al., 2021)", "PAPER", "Microsoft Research"),
  artifact="PAPER", lineage="CORE", branches=["scaling-training"], transitions=["gpu-only-to-heterogeneous-training"],
  inherit=None, caveat=None,
  claims=[
    ("ZeRO-Offload trains 13B+ models on a single GPU by offloading data and compute to CPU with minimized data movement, reaching 40 TFLOPs/GPU on V100 for 10B models.", "PRIMARY_FACT", "Headline scale + throughput figures; abstract consumed (2101.06840)."),
    ("Bandwidth-aware heterogeneous offload is the conceptual ancestor of host-offload inference (Qwen PLE tables, V4.1 Engram CPU offload).", "INFERENCE", "Lineage synthesis to D008/D163.")],
  limits=["Full-body scheduling design not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2101.06840): heterogeneous offload + 40-TFLOPs figure confirmed; full body outstanding.")}),
"D105": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Recompute-for-memory EXCHANGE: spends arithmetic to save footprint; record direction explicitly.",
  entity=("sublinear-memory-2016", "Training Deep Nets with Sublinear Memory Cost (Chen et al., 2016)", "PAPER", "Cornell/IBM"),
  artifact="PAPER", lineage="CORE", branches=["scaling-training"], transitions=["store-all-to-checkpointing"],
  inherit=None, caveat="EXCHANGE direction: activation checkpointing spends an extra forward pass to save memory — the inverse of the usual efficiency arrow.",
  claims=[
    ("Sublinear-memory training stores O(sqrt(n)) activations for n layers via graph analysis with in-place sharing, paying one extra forward pass per batch.", "PRIMARY_FACT", "Headline complexity + cost facts; abstract consumed (1604.06174)."),
    ("The compute-for-memory exchange direction must be recorded explicitly wherever checkpointing is invoked, lest it read as pure savings.", "INFERENCE", "Direction-recording rule.")],
  limits=["Full-body graph-analysis algorithm not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (1604.06174): O(sqrt(n)) memory + extra-forward-pass cost confirmed; full body outstanding.")}),
"D106": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="PyTorch-native ZeRO-3-class sharding; current-stack FIT/SCALE lineage.",
  entity=("fsdp-2023", "PyTorch FSDP: Experiences on Scaling Fully Sharded Data Parallel (Zhao et al., 2023)", "PAPER", "Meta"),
  artifact="PAPER", lineage="CORE", branches=["scaling-training"], transitions=["zero-to-fsdp"],
  inherit=None, caveat=None,
  claims=[
    ("PyTorch FSDP productizes fully-sharded data parallelism co-designed with the dispatcher and CUDA caching allocator for non-intrusive large-model training.", "PRIMARY_FACT", "Headline contribution; abstract consumed (2304.11277)."),
    ("FSDP is the current-stack FIT/SCALE lineage carrier of ZeRO-3-class sharding.", "INFERENCE", "Lineage placement.")],
  limits=["Full-body co-design details not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2304.11277): FSDP sharding productization confirmed; full body outstanding.")}),
"D107": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="All-to-all head partitioning for long sequences; training-side context parallelism.",
  entity=("ulysses-2023", "DeepSpeed-Ulysses: System Optimizations for Enabling Training of Extreme Long Sequence Transformer Models (Jacobs et al., 2023)", "PAPER", "Microsoft Research"),
  artifact="PAPER", lineage="CORE", branches=["scaling-training"], transitions=["batch-parallel-to-sequence-parallel"],
  inherit=None, caveat=None,
  claims=[
    ("DeepSpeed-Ulysses partitions along the sequence dimension with all-to-all head exchange, enabling extreme-long-sequence training where batch/tensor/pipeline parallelism do not reach.", "PRIMARY_FACT", "Headline mechanism; abstract consumed (2309.14509)."),
    ("Sequence parallelism is the training-side complement to inference-side context extension (YaRN, ring attention).", "INFERENCE", "Complementarity framing with D108.")],
  limits=["Full-body communication-efficiency analysis not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2309.14509): sequence-parallel mechanism confirmed; full body outstanding.")}),
"D108": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Blockwise attention + ring KV exchange; closes r1 G08 absentee; SCALE, arithmetic unchanged.",
  entity=("ring-attention-2023", "Ring Attention with Blockwise Transformers for Near-Infinite Context (Liu et al., 2023)", "PAPER", "UC Berkeley/Google"),
  artifact="PAPER", lineage="CORE", branches=["scaling-training"], transitions=["single-device-context-to-ring-context"],
  inherit=None, caveat="SCALE direction: context length multiplies with device count; per-token arithmetic unchanged.",
  claims=[
    ("Ring Attention distributes blockwise attention/feedforward over devices in a ring with overlapped KV-block communication, extending trainable context by the device-count factor.", "PRIMARY_FACT", "Headline mechanism + scaling; abstract consumed (2310.01889)."),
    ("The record closes the r1 G08 sequence-parallelism gap in Discovery.", "INFERENCE", "Coverage statement.")],
  limits=["Full-body overlap analysis not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2310.01889): ring blockwise mechanism confirmed; full body outstanding.")}),
"D109": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Score-driven eviction (heavy-hitter + recent); category (3) eviction.",
  entity=("h2o-2023", "H2O: Heavy-Hitter Oracle for Efficient Generative Inference of Large Language Models (Zhang et al., 2023)", "PAPER", "Princeton"),
  artifact="PAPER", lineage="CORE", branches=["attention-kv", "inference-serving"], transitions=["full-cache-to-eviction"],
  inherit=None, caveat="Eviction is lossy by construction; StreamingLLM sink constraints (D110) bound all eviction claims.",
  claims=[
    ("H2O keeps heavy-hitter tokens plus recent tokens as the KV cache, observing that small token subsets dominate attention value.", "PRIMARY_FACT", "Headline mechanism + observation; abstract consumed (2306.14048)."),
    ("H2O is KV-category (3) eviction in the Special's cache taxonomy, distinct from selection (NSA/DSA), placement (paged/radix), and offload.", "INFERENCE", "Taxonomic classification.")],
  limits=["Full-body heavy-hitter analysis and benchmark tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2306.14048): heavy-hitter + recent eviction confirmed; full body outstanding.")}),
"D110": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Sink + window positional policy; constrains all eviction claims.",
  entity=("streamingllm-2023", "Efficient Streaming Language Models with Attention Sinks (Xiao et al., 2023)", "PAPER", "MIT/Harvard"),
  artifact="PAPER", lineage="CORE", branches=["attention-kv", "inference-serving"], transitions=["window-to-sink-window"],
  inherit=None, caveat=None,
  claims=[
    ("StreamingLLM shows that retaining initial-token 'attention sink' KV plus a sliding window recovers window-attention performance for streaming generation.", "PRIMARY_FACT", "Headline phenomenon + policy; abstract consumed (2309.17453)."),
    ("The sink phenomenon constrains every eviction policy: any eviction scheme must account for sink tokens or regress.", "INFERENCE", "Constraint significance.")],
  limits=["Full-body sink-emergence analysis not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2309.17453): attention-sink + window policy confirmed; full body outstanding.")}),
"D111": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Prompt observation-window voting then compressed decode; prompt-aware category (3).",
  entity=("snapkv-2024", "SnapKV: LLM Knows What You Are Looking for Before Generation (Li et al., 2024)", "PAPER", "Microsoft Research"),
  artifact="PAPER", lineage="CORE", branches=["attention-kv", "inference-serving"], transitions=["static-eviction-to-prompt-aware"],
  inherit=None, caveat=None,
  claims=[
    ("SnapKV selects per-head important KV positions from a prompt-end observation window, then decodes against the compressed cache without fine-tuning.", "PRIMARY_FACT", "Headline mechanism; abstract consumed (2404.14469)."),
    ("Prompt-aware selection makes SnapKV the observation-window member of eviction category (3).", "INFERENCE", "Taxonomic classification.")],
  limits=["Full-body voting-cluster analysis and LongBench tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2404.14469): observation-window compression confirmed; full body outstanding.")}),
"D112": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Layer-wise pyramidal budgets; layer-heterogeneity relevant to CSA2 sharing despite locator defect.",
  entity=("pyramidkv-2024", "PyramidKV: Dynamic KV Cache Compression based on Pyramidal Information Funneling (Cai et al., 2024)", "PAPER", "Independent"),
  artifact="PAPER", lineage="CORE", branches=["attention-kv", "inference-serving"], transitions=["uniform-budget-to-pyramidal"],
  inherit=None, caveat="Bound locator is a wrong-identity arXiv ID; claims rest on the true paper's established content.",
  claims=[
    ("PyramidKV allocates KV-cache budgets pyramidally across layers (more in lower layers, less above), exploiting layer-wise attention heterogeneity.", "AUTHOR_CLAIM", "Established content of the true paper (2406.02069); bound locator does not resolve to it."),
    ("Layer-heterogeneous budgeting is directly relevant to CSA2's cross-layer sharing analysis in the V4.1 capstone.", "INFERENCE", "Cross-record relevance."),
    ("Bound Discovery locator https://arxiv.org/abs/2406.02032 resolves to an unrelated audio-representation paper (M2D-CLAP).", "INFERENCE", "Verified via arXiv API; true identity 2406.02069 confirmed by title search.")],
  limits=["True-paper body not consumed beyond identity confirmation.", "Bound locator must be amended to 2406.02069 before locator-cited use."],
  ver={"@FULL": ("UNRESOLVED", "Locator-identity defect: bound 2406.02032 is M2D-CLAP. Gap-fill trigger G-EV-08: true identity arXiv 2406.02069 confirmed; amendment deferred to Sol.")}),
"D113": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Block-hash prefix reuse; category (4); granularity contrast vs SGLang radix tree.",
  entity=("vllm-apc-docs", "vLLM Automatic Prefix Caching (documentation)", "ORGANIZATION", "vLLM Project"),
  artifact="FRAMEWORK", lineage="CORE", branches=["inference-serving"], transitions=["no-reuse-to-prefix-reuse"],
  inherit=None, caveat="Docs describe mechanism, not measured hit-rate gains; granularity contrast is structural.",
  claims=[
    ("vLLM Automatic Prefix Caching reuses KV blocks across requests via block hashing, the block-granularity member of reuse category (4).", "PROJECT_CLAIM", "Documentation-level."),
    ("Block-hash granularity contrasts structurally with SGLang's radix-tree prefix management; neither subsumes the other.", "INFERENCE", "Granularity comparison.")],
  limits=["Docs page not fetched; mechanism scoped to established role."],
  ver={"@FULL": ("VERIFIED", "Prefix-reuse role recorded at documentation level; page body outstanding."),
        "version binding": ("UNRESOLVED", "No version pin extracted.")}),
"D114": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Engine-independent reuse/offload/disaggregation; Mooncake as backend; categories (4)+(5).",
  entity=("lmcache", "LMCache (external KV-cache layer)", "PRODUCT", "LMCache community"),
  artifact="FRAMEWORK", lineage="BRIDGE", branches=["inference-serving", "attention-kv"], transitions=["engine-internal-to-external-kv"],
  inherit=None, caveat="Repo not fetched; backend/configuration facts at project level.",
  claims=[
    ("LMCache externalizes KV-cache reuse, offload, and disaggregation from any single engine, with Mooncake-class backends.", "PROJECT_CLAIM", "Project-role level."),
    ("Engine independence spans reuse category (4) and offload category (5), the composability instance for the serving lane.", "INFERENCE", "Taxonomic significance.")],
  limits=["Repository not fetched; API/backend matrix outstanding."],
  ver={"@FULL": ("VERIFIED", "External-KV-layer role recorded at project level; repo audit outstanding."),
        "version binding": ("UNRESOLVED", "No version pin extracted.")}),
"D115": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Per-token depth routing; NOT MoE (depth vs expert routing object differs).",
  entity=("mixture-of-depths-2024", "Mixture-of-Depths: Dynamically allocating compute in transformer-based language models (Raposo et al., 2024)", "PAPER", "Google DeepMind"),
  artifact="PAPER", lineage="CORE", branches=["conditional-compute-moe"], transitions=["expert-routing-to-depth-routing"],
  inherit=None, caveat="Depth routing routes tokens to layers, not to experts; MoD-vs-MoE conflation prohibited.",
  claims=[
    ("Mixture-of-Depths caps per-layer participating tokens with top-k routing, allocating FLOPs non-uniformly across sequence and depth under a static compute graph.", "PRIMARY_FACT", "Headline mechanism; abstract consumed (2404.02258)."),
    ("The routing object (depth participation) differs categorically from MoE expert routing; the shared name is a known confusion source.", "INFERENCE", "Disambiguation boundary.")],
  limits=["Full-body capacity/allocation analysis not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2404.02258): depth-routing mechanism confirmed; full body outstanding.")}),
"D116": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Same-model draft + verify; bridges conditional depth and decoding; no draft model.",
  entity=("layerskip-2024", "LayerSkip: Enabling Early Exit Inference and Self-Speculative Decoding (Elhoushi et al., 2024)", "PAPER", "Apple/Meta"),
  artifact="PAPER", lineage="CORE", branches=["conditional-compute-moe", "decoding-acceleration"], transitions=["external-draft-to-self-draft"],
  inherit=None, caveat=None,
  claims=[
    ("LayerSkip trains with layer dropout plus early-exit loss so early layers exit accurately, then self-speculates: early-layer drafts verified by remaining layers with shared compute and activations.", "PRIMARY_FACT", "Headline mechanism; abstract consumed (2404.16710)."),
    ("Self-speculation bridges conditional-depth and decoding lanes with no separate draft model and smaller memory footprint.", "INFERENCE", "Bridge significance.")],
  limits=["Full-body dropout-schedule and speedup tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2404.16710): layer-dropout + self-speculative mechanism confirmed; full body outstanding.")}),
"D117": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="DeeBERT minimal early-exit precedent; no LLM-scale claim — bounding only, with locator defect.",
  entity=("deebert-2020", "DeeBERT: Dynamic Early Exiting for Accelerating BERT Inference (Xin et al., 2020)", "PAPER", "Dartmouth"),
  artifact="PAPER", lineage="BRIDGE", branches=["conditional-compute-moe"], transitions=["bert-to-early-exit"],
  inherit=None, caveat="Bound locator is a wrong-identity arXiv ID (single-digit typo); BERT-era precedent only, no LLM-scale claim.",
  claims=[
    ("DeeBERT adds internal classifiers to BERT with entropy-based dynamic early exiting, the minimal precedent bounding adaptive-computation history.", "AUTHOR_CLAIM", "Established content of the true paper (2004.12993); bound locator does not resolve to it."),
    ("Bound Discovery locator https://arxiv.org/abs/2004.12918 resolves to an unrelated game-theory paper (digit transposition of true 2004.12993).", "INFERENCE", "Verified via arXiv API; true identity confirmed by title search.")],
  limits=["True-paper body not consumed beyond identity confirmation.", "Bound locator must be amended to 2004.12993 before locator-cited use."],
  ver={"@FULL": ("UNRESOLVED", "Locator-identity defect: bound 2004.12918 is not DeeBERT. Gap-fill trigger G-EV-09: true identity arXiv 2004.12993 confirmed; amendment deferred to Sol.")}),
"D118": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Scenario-bound comparability proof (arrival, latency bounds, SLO, identity, audit).",
  entity=("mlperf-inference", "MLPerf Inference (MLCommons LLM methodology)", "ORGANIZATION", "MLCommons"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["ad-hoc-bench-to-audited-scenario"],
  inherit=None, caveat="Spec page not fetched; scenario-structure facts at established level.",
  claims=[
    ("MLPerf Inference defines audited scenarios (server/single-stream/multistream/offline) with arrival processes, latency bounds, and system-identity rules, the comparability proof for system efficiency claims.", "PROJECT_CLAIM", "Methodology-role level."),
    ("Scenario binding (not just model binding) is what makes two inference numbers comparable; the Special adopts this as a rule.", "INFERENCE", "Methodological adoption.")],
  limits=["Spec pages not fetched; scenario details at established level."],
  ver={"@FULL": ("VERIFIED", "Scenario-bound comparability role recorded; spec body outstanding.")}),
"D119": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="Rate-controlled TTFT/ITL/throughput decomposition confirmed via NVIDIA docs; standalone AIPerf product page unconsumed.",
  entity=("genai-perf", "GenAI-Perf (NVIDIA perf_analyzer LLM benchmarking)", "PRODUCT", "NVIDIA"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["perf-analyzer-to-genai-perf"],
  inherit=None, caveat="AIPerf successor named in current docs but its standalone product surface not consumed; no AIPerf product claim made.",
  claims=[
    ("GenAI-Perf lives in the triton-inference-server/perf_analyzer repository (genai-perf/) exactly as the bound locator states, measuring output-token throughput, time to first token, inter-token latency, and request throughput under specified concurrency/rate load with CSV/JSON logging.", "PROJECT_CLAIM", "Tooling authority consumed via NVIDIA Triton docs this pass (install, quickstart, metrics table)."),
    ("Current NVIDIA docs state GenAI-Perf is being phased out in favor of AIPerf for new benchmarking needs; no standalone AIPerf product page was located or consumed this pass.", "PROJECT_CLAIM", "Successor naming per current docs; product-surface gap preserved, not closed by assertion.")],
  limits=["perf_analyzer repo itself not cloned; metric definitions rest on docs.", "AIPerf product identity beyond the successor pointer remains open."],
  ver={"@FULL": ("VERIFIED", "GenAI-Perf tooling authority consumed via official docs: location, metrics, load model, logging confirmed."),
        "locate/confirm AIPerf product identity": ("UNRESOLVED", "AIPerf named only as GenAI-Perf successor in docs; standalone product surface not located. Gap-fill trigger G-EV-10 recorded; NOT_FOUND upgraded to SUCCESSOR_NAMED_PRODUCT_UNCONSUMED.")}),
"D120": dict(status="PARTIAL", mat="CONTEXT",
  mat_rationale="LLMPerf included for its caveats; teaches incomparability, not ground truth.",
  entity=("llmperf-ray", "LLMPerf (Ray; caveated throughput harness)", "PRODUCT", "Ray project"),
  artifact="BENCHMARK", lineage="CONTEXT", branches=["benchmark-methodology"], transitions=["throughput-number-to-caveat-exhibit"],
  inherit=None, caveat="Included as a caveat exhibit; no throughput figure from LLMPerf is cited as fact.",
  claims=[
    ("LLMPerf's documented caveats (client-side limits, tokenizer and sampling confounds) make it the Special's incomparability teacher rather than a measurement source.", "PROJECT_CLAIM", "Role-level; repo not fetched."),
    ("No LLMPerf number is cited anywhere in the evidence base.", "INFERENCE", "Exclusion boundary.")],
  limits=["Repo and caveat docs not fetched; role scoped to screening decision."],
  ver={"@FULL": ("VERIFIED", "Caveat-exhibit role recorded; no measurement use made."),
        "caveat scope": ("VERIFIED", "Caveat scope bounded to harness-confound teaching; no overclaim.")}),
"D121": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Accuracy-side harness standard: same name + different harness = different number.",
  entity=("lm-eval-harness", "EleutherAI lm-evaluation-harness", "PRODUCT", "EleutherAI"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["ad-hoc-eval-to-standard-harness"],
  inherit=None, caveat="Repo not fetched; harness-role facts at established level.",
  claims=[
    ("lm-evaluation-harness standardizes accuracy-side evaluation tasks, making harness identity part of every reported number.", "PROJECT_CLAIM", "Role-level; the same-name-different-harness rule is its durable lesson."),
    ("Capstone accuracy citations without harness pins inherit this record's incomparability warning.", "INFERENCE", "Methodological adoption.")],
  limits=["Repo and task configs not consumed."],
  ver={"@FULL": ("VERIFIED", "Harness-standard role recorded; repo audit outstanding.")}),
"D122": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Multi-metric transparency-first harness; reproducibility anchor.",
  entity=("helm-2022", "HELM (Stanford CRFM holistic evaluation)", "PRODUCT", "Stanford CRFM"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["single-metric-to-holistic"],
  inherit=None, caveat="Repo not fetched; HELM paper (2211.09110) not separately bound.",
  claims=[
    ("HELM evaluates models across scenarios with multi-metric transparency-first reporting, the reproducibility anchor for broad evaluation claims.", "PROJECT_CLAIM", "Role-level; paper 2211.09110 noted per summary."),
    ("Scenario x metric x adaptation transparency is the reporting standard the Special demands of vendor benchmark tables.", "INFERENCE", "Standard adoption.")],
  limits=["HELM repo and paper body not consumed."],
  ver={"@FULL": ("VERIFIED", "Transparency-standard role recorded; repo/paper audit outstanding.")}),
"D123": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="DeepSeek-V4.1-Flash technical report: CED 8B/16B, pure CSA2, FP4-KV in training, 890B/tok, SWA replay, Engram, OPD; eval appendix with scaffolds.",
  entity=("deepseek-v41-report", "DeepSeek-V4.1-Flash technical report (2026)", "PAPER", "DeepSeek-AI"),
  artifact="PAPER", lineage="CORE", branches=["capstone-2026-v41", "attention-kv", "precision-quantization", "decoding-acceleration"], transitions=["v4-to-v41"],
  inherit=None, caveat="First-party report: architecture facts strong; evaluation figures scaffold-bound (appendix harnesses must be named per citation).",
  claims=[
    ("V4.1-Flash is a 552B-backbone multimodal MoE (1M context) with a Causal Encoder-Decoder activating 16B/decode-token but 8B/prefill-token, combining cross-layer KV reuse in CSA2 with FP4 KV caching for 890 bytes/token global KV (1/4 of V4-Flash) plus SWA Bounded Replay for 1/8 persistent footprint.", "AUTHOR_CLAIM", "Report abstract consumed (2609.19969, pub 2026-09-17); headline architecture + KV figures."),
    ("The model pretrains on 45T multimodal tokens with FP4-KV in training; the eval appendix carries scaffold-bound performance figures.", "AUTHOR_CLAIM", "Training-scale + appendix-scaffold facts per abstract; harness binding required per figure."),
    ("Streamlined V4 architecture plus efficient extensions (OPD class) position V4.1 as the KV-compression-limit capstone, not a general capability release.", "INFERENCE", "Case-study framing.")],
  limits=["Full-body architecture sections, KV derivations, and eval appendix not consumed; scaffold-bound figures quarantined."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed in full: CED/CSA2/FP4-KV/SWA/Engram/45T/appendix facts extracted; full-body sections outstanding."),
        "scaffold/version binding": ("UNRESOLVED", "Appendix scaffold/version pins not extracted; per-figure binding deferred.")}),
"D124": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="DeepSeek-V4 report: 1.6T/49B Pro + 284B/13B Flash; CSA+HCA; FP4 experts; Muon; 32T/33T; vs V3.2 10% FLOPs/7% KV.",
  entity=("deepseek-v4-report", "DeepSeek-V4 technical report (2026)", "PAPER", "DeepSeek-AI"),
  artifact="PAPER", lineage="CORE", branches=["capstone-2026-v41", "conditional-compute-moe", "attention-kv", "precision-quantization"], transitions=["v32-to-v4"],
  inherit=None, caveat="Preview-version report; Pro-vs-Flash and vs-V3.2 ratios are first-party and context-bound (1M-context setting).",
  claims=[
    ("DeepSeek-V4 previews a 1.6T/49B Pro and 284B/13B Flash with CSA+HCA hybrid attention, manifold-constrained hyper-connections, Muon optimization, and 32T+ token pretraining.", "AUTHOR_CLAIM", "Report abstract consumed (2606.19348, pub 2026-04-26)."),
    ("At 1M context, V4-Pro claims 27% single-token FLOPs and 10% KV cache vs V3.2, the efficiency deltas the V4.1 report later extends.", "VENDOR_CLAIM", "First-party deltas; 1M-context-bound."),
    ("FP4 experts and Muon in V4 ground the precision/optimizer lanes' adoption claims.", "INFERENCE", "Cross-lane linkage.")],
  limits=["Full-body architecture and evaluation sections not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed in full: Pro/Flash specs, CSA+HCA, mHC, Muon, deltas extracted; full body outstanding."),
        "ratio conditions": ("VERIFIED", "27%-FLOPs/10%-KV deltas recorded strictly as 1M-context first-party comparisons.")}),
"D125": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="DeepSeek-V3.2 report: DSA lightning indexer + token selection under MLA, O(Lk); continued training from Terminus; parity + independent long-context signal.",
  entity=("deepseek-v32-report", "DeepSeek-V3.2 report (2025)", "PAPER", "DeepSeek-AI"),
  artifact="PAPER", lineage="CORE", branches=["capstone-2026-v41", "attention-kv"], transitions=["mla-to-dsa"],
  inherit=None, caveat="IMO/IOI gold claims belong to the Speciale high-compute variant, not the base model; comparison claims (GPT-5/Gemini) are vendor-framed.",
  claims=[
    ("V3.2 introduces DeepSeek Sparse Attention: lightning indexer plus fine-grained token selection under MLA with O(Lk) complexity, trained by continuation from V3.1-Terminus with DSA as the only architectural modification.", "AUTHOR_CLAIM", "Report abstract + PDF excerpts consumed (2512.02556, pub 2025-12-02; DSA section verified via search excerpt)."),
    ("V3.2-Exp holds Elo parity with V3.1-Terminus despite sparsity, the parity evidence that de-risks DSA adoption into GLM-5 and V4-line.", "AUTHOR_CLAIM", "Parity finding per report excerpts."),
    (" reasoning/agentic peaks (Speciale IMO/IOI golds, GPT-5 comparisons) are variant- and harness-bound vendor claims, not DSA mechanism facts.", "VENDOR_CLAIM", "Quarantine boundary.")],
  limits=["Full-body DSA formulation and benchmark tables not consumed; indexer warm-up protocol at excerpt level."],
  ver={"@FULL": ("VERIFIED", "Abstract + DSA-section excerpts consumed: indexer/selection/O(Lk)/continuation/parity extracted; full body outstanding.")}),
"D126": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="V3.2-Exp launch + API docs: DSA debut, 50%+ price cut; dated efficiency-to-price transmission event.",
  entity=("deepseek-v32exp-launch", "DeepSeek-V3.2-Exp launch + API docs (DSA debut, 50%+ price cut)", "PRODUCT", "DeepSeek-AI"),
  artifact="PRODUCT", lineage="CORE", branches=["capstone-2026-v41"], transitions=["report-to-launch"],
  inherit=None, caveat="Price-cut figures are dated API-schedule facts, not architecture measurements.",
  claims=[
    ("The V3.2-Exp launch debuts DSA with 50%+ API price cuts, live App/Web/API, and open release (HF weights, GitHub tech report, TileLang/CUDA kernels).", "VENDOR_CLAIM", "Launch facts verified via search excerpts (deepseek.com/en/news/v3-2-exp, API docs news250929)."),
    ("The launch is the dated efficiency-to-price transmission event: DSA compute savings converted to API prices within days.", "INFERENCE", "Economics-lane significance.")],
  limits=["Launch/API pages summarized from search excerpts; full pages not consumed."],
  ver={"@FULL": ("VERIFIED", "Launch facts corroborated across launch page + API docs excerpts; full-page consumption outstanding."),
        "price/artifact identity": ("VERIFIED", "50%+ cut recorded as dated API-schedule fact; artifact identities (HF/GH/kernels) pinned.")}),
"D127": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Qwen3.8-Flash-Next GitHub: Flash-Next (preview, 262K) vs Flash (production API, 1M+tools) BOUND; runtimes; SWE-Pro footnote normalization.",
  entity=("qwen38-github", "QwenLM/Qwen3.8-Flash-Next GitHub (report + README source of truth)", "PRODUCT", "Alibaba Qwen"),
  artifact="MODEL", lineage="CORE", branches=["capstone-2026-v41", "attention-kv", "benchmark-methodology"], transitions=["checkpoint-to-repo-truth"],
  inherit=None, caveat="Repo not fetched; variant-bound facts at summary level with D008/D029 corroboration.",
  claims=[
    ("The repo binds the Flash-Next (preview, 262K context) vs Flash (production API, 1M + tools) variant distinction, preventing cross-variant number mixing.", "PROJECT_CLAIM", "Variant-boundary fact; central to valid Qwen citation."),
    ("SGLang/vLLM/TokenSpeed/KTransformers runtime matrix and SWE-Pro footnote normalization are documented at repo level.", "PROJECT_CLAIM", "Coverage-level; runtime facts consistent with D054/D163.")],
  limits=["Repo not fetched; footnote text and runtime matrix outstanding."],
  ver={"@FULL": ("VERIFIED", "Variant-boundary role recorded; repo body outstanding."),
        "bound/footnote verification": ("UNRESOLVED", "SWE-Pro footnote text not extracted; normalization claim unconfirmed.")}),
"D128": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="GLM-5 report: 744B/40B; ADOPTS DSA (cited); MLA; SimpleGDN; RULER ablations; cross-lab DSA adoption evidence.",
  entity=("glm5-report", "GLM-5 technical report (Z.ai, 2026)", "PAPER", "Z.ai"),
  artifact="PAPER", lineage="CORE", branches=["capstone-2026-v41", "attention-kv"], transitions=["independent-to-dsa-adopter"],
  inherit=None, caveat="First-party report; agentic-coding SOTA claims are benchmark- and harness-bound.",
  claims=[
    ("GLM-5 is a 744B/40B foundation model adopting DSA (cited) with MLA and SimpleGDN, trained with asynchronous RL infrastructure for agentic coding.", "AUTHOR_CLAIM", "Report abstract consumed (2602.15763, pub 2026-02-17)."),
    ("Cross-lab DSA adoption (DeepSeek-originated mechanism in a Z.ai flagship) is independent corroboration of DSA's transferability beyond its home lab.", "INFERENCE", "Adoption significance; the Special's strongest portability datapoint."),
    ("RULER ablations in the report link long-context fidelity measurement to the attention-efficiency claim.", "AUTHOR_CLAIM", "Ablation-role fact per abstract context.")],
  limits=["Full-body DSA-adoption details, RL-infra design, and benchmark tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed in full: 744B/40B, DSA adoption, async RL, coding-SOTA framing extracted; full body outstanding.")}),
"D129": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="zai-org/GLM-5 GitHub: IndexShare, MTP, deployment matrix; IndexPool unresolved.",
  entity=("glm5-github", "zai-org/GLM-5 GitHub (IndexShare, MTP, deployment matrix)", "PRODUCT", "Z.ai"),
  artifact="MODEL", lineage="CORE", branches=["capstone-2026-v41", "decoding-acceleration"], transitions=["report-to-deployment-matrix"],
  inherit=None, caveat="Repo not fetched; IndexPool identity unresolved; MTP gains are repo-reported.",
  claims=[
    ("The GLM-5 repo documents IndexShare (2.9x FLOPs at 1M), MTP acceptance gains (+20%), and the SGLang/vLLM/KTransformers/Ascend deployment matrix.", "PROJECT_CLAIM", "Repo-reported figures; deployment-matrix role corroborated by D052/D054."),
    ("IndexPool remains unresolved and is cited for no fact.", "INFERENCE", "Boundary statement.")],
  limits=["Repo not fetched; IndexShare/MTP figures unconfirmed beyond repo reporting."],
  ver={"@FULL": ("VERIFIED", "Deployment-matrix role recorded; repo body outstanding."),
        "IndexPool resolution": ("UNRESOLVED", "IndexPool identity unresolved; Sol judgment whether to pursue.")}),
"D130": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="zai-org/GLM-5.3-Flash card: first-party checkpoint identity (lineage tag, MIT, fp8, glm5_next, BF16 sibling).",
  entity=("glm53-flash-card", "zai-org/GLM-5.3-Flash model card (Hugging Face)", "PRODUCT", "Z.ai"),
  artifact="MODEL", lineage="CORE", branches=["capstone-2026-v41"], transitions=["report-to-checkpoint"],
  inherit=None, caveat="Card identity facts only; upgrades/benchmarks on the card are secondary facts, not cited.",
  claims=[
    ("The card pins checkpoint identity: 2602.15763 lineage tag, MIT license, fp8 variant with glm5_next architecture tag and BF16 sibling.", "PROJECT_CLAIM", "Identity-level; lineage tag corroborates D128 descent."),
    ("Card-hosted upgrade/benchmark language is treated as secondary and cited for no fact.", "INFERENCE", "Boundary statement.")],
  limits=["Card page not fetched; identity facts scoped to summary."],
  ver={"@FULL": ("VERIFIED", "Checkpoint-identity role recorded; card body outstanding.")}),
"D131": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Z.ai dev docs: GLM-5.3-Flash overview; -3.01x attention / -4.44x KV vs GLM-5.3; relative ratios, vendor-quarantined.",
  entity=("zai-glm53-docs", "Z.ai developer docs: GLM-5.3-Flash overview", "ORGANIZATION", "Z.ai"),
  artifact="PRODUCT", lineage="CORE", branches=["capstone-2026-v41"], transitions=["checkpoint-to-docs"],
  inherit=None, caveat="Attention/KV ratios are vendor-relative to GLM-5.3 under vendor measurement; not absolute facts.",
  claims=[
    ("Z.ai docs state -3.01x attention compute and -4.44x KV vs GLM-5.3 for GLM-5.3-Flash.", "VENDOR_CLAIM", "Relative-ratio framing; baseline named."),
    ("Docs-level ratios complement the HF transformers doc (D083: 3.0x/4.4x) as the same vendor-relative measurement seen from two surfaces.", "INFERENCE", "Cross-surface consistency note.")],
  limits=["Docs page not fetched; measurement conditions outstanding."],
  ver={"@FULL": ("VERIFIED", "Relative-ratio facts recorded with baseline; page body outstanding."),
        "ratio quarantine": ("VERIFIED", "Ratios carried strictly as vendor-relative; no absolute reading made.")}),
"D132": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="KDA kernel implementation (FLA) + vLLM path: open kernel + vLLM impl = deployability proof beyond paper.",
  entity=("kda-fla-impl", "KDA kernel implementation (FLA) + vLLM path", "PRODUCT", "fla-org/Moonshot AI"),
  artifact="FRAMEWORK", lineage="CORE", branches=["capstone-2026-v41", "attention-kv", "inference-serving"], transitions=["paper-kernel-to-open-kernel"],
  inherit=None, caveat="Repo not fetched; numerics/perf outstanding as flagged.",
  claims=[
    ("The FLA KDA kernel plus vLLM path constitutes deployability proof for Kimi Linear beyond the paper: third-party executable implementation.", "PROJECT_CLAIM", "Release-level; consistent with D027's open-source claims."),
    ("Kernel numerics and serving performance remain outstanding and are cited for no fact.", "INFERENCE", "Boundary statement.")],
  limits=["Kernel code, numerics, and perf numbers not consumed."],
  ver={"@FULL": ("VERIFIED", "Deployability-proof role recorded at release level; code audit outstanding."),
        "numerics/perf at Evidence": ("UNRESOLVED", "Numerics/perf unconsumed; no performance fact cited.")}),
"D133": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Experts-choose-tokens with capacity guarantees; third point vs top-k vs aux-loss-free.",
  entity=("expert-choice-2022", "Mixture-of-Experts with Expert Choice Routing (Zhou et al., 2022)", "PAPER", "Google"),
  artifact="PAPER", lineage="CORE", branches=["conditional-compute-moe"], transitions=["token-choice-to-expert-choice"],
  inherit=None, caveat=None,
  claims=[
    ("Expert Choice routing lets experts select their top-k tokens instead of tokens selecting experts, giving each expert fixed capacity with variable per-token expert counts.", "PRIMARY_FACT", "Headline mechanism; abstract consumed (2202.09368)."),
    ("Expert-choice forms the third routing point alongside top-k (load-balance loss) and aux-loss-free schemes in the Special's routing taxonomy.", "INFERENCE", "Taxonomic placement.")],
  limits=["Full-body pretraining-speedup analysis not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2202.09368): expert-choice mechanism confirmed; full body outstanding.")}),
"D134": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Block-sparse MoE GEMMs; compute twin to DeepEP communication twin.",
  entity=("megablocks-2022", "MegaBlocks: Efficient Sparse Training with Mixture-of-Experts (Gale et al., 2022)", "PAPER", "Stanford/NVIDIA"),
  artifact="PAPER", lineage="CORE", branches=["conditional-compute-moe", "inference-serving"], transitions=["padded-moe-to-block-sparse"],
  inherit=None, caveat=None,
  claims=[
    ("MegaBlocks reformulates MoE as block-sparse operations with dedicated GPU kernels, never dropping tokens and reaching 40% end-to-end training speedups over Tutel (2.4x over Megatron-LM DNNs).", "PRIMARY_FACT", "Headline mechanism + figures; abstract consumed (2211.15841)."),
    ("MegaBlocks is the compute twin to DeepEP's communication twin (D064).", "INFERENCE", "Twin framing.")],
  limits=["Full-body kernel design and speedup tables not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2211.15841): block-sparse MoE + figures confirmed; full body outstanding.")}),
"D135": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="1.58-bit matched-precision claim at 3B; industrial deployment still open.",
  entity=("bitnet-b158-2024", "The Era of 1-bit LLMs: All Large Language Models are in 1.58 Bits (Ma et al., 2024)", "PAPER", "Microsoft Research"),
  artifact="PAPER", lineage="CORE", branches=["precision-quantization"], transitions=["binary-to-ternary"],
  inherit=None, caveat="Matched-precision claim at 3B scale under the paper's training recipe; industrial deployment open (cf. D047).",
  claims=[
    ("BitNet b1.58 uses ternary {-1,0,1} weights, matching FP16/BF16 perplexity and end-task performance at 3B with major latency/memory/throughput/energy advantages.", "PRIMARY_FACT", "Headline claim; abstract consumed (2402.17764)."),
    ("The paper defines a 1.58-bit scaling law and recipe, the native-low-bit counterpart to PTQ-fitted sub-4-bit practice.", "AUTHOR_CLAIM", "Recipe significance.")],
  limits=["Full-body scaling-law derivations not consumed; deployment status per D047 limitation."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2402.17764): ternary matched-precision claim confirmed; full body outstanding."),
        "deployment status": ("UNRESOLVED", "Industrial deployment beyond research open; consistent with D047.")}),
"D136": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Block-32 + E8M0 chassis; MXFP4 = E2M1/4.25 bits; format authority behind V4-line FP4 claims.",
  entity=("ocp-mx-spec", "OCP Microscaling (MX) Specification v1.0", "ORGANIZATION", "Open Compute Project"),
  artifact="OTHER", lineage="CORE", branches=["precision-quantization"], transitions=["vendor-format-to-open-standard"],
  inherit=None, caveat="Spec page not fetched; format facts at established level with D137 corroboration.",
  claims=[
    ("The OCP MX v1.0 spec standardizes block-32 microscaling with E8M0 shared scales; MXFP4 denotes E2M1 elements at 4.25 effective bits.", "PROJECT_CLAIM", "Format facts; corroborated by D137 paper and D163 deployment."),
    ("The spec is the format authority behind all V4-line MXFP4/MXFP8 serving claims.", "INFERENCE", "Authority-chain statement.")],
  limits=["Spec PDF not fetched; element/format details at established level."],
  ver={"@FULL": ("VERIFIED", "Format-authority role corroborated via D137 + D163; spec body outstanding.")}),
"D137": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="MX conversion/dot-product semantics; native-low-bit (defined) vs PTQ (fitted) evidence class.",
  entity=("mx-paper-2023", "Microscaling Data Formats for Deep Learning (Rouhani et al., 2023)", "PAPER", "Microsoft"),
  artifact="PAPER", lineage="CORE", branches=["precision-quantization"], transitions=["fp8-paper-to-mx-paper"],
  inherit=None, caveat=None,
  claims=[
    ("The MX paper evaluates block-scaled narrow formats as drop-in FP32 replacements for inference and training, including sub-8-bit generative-LM training with minimal accuracy loss.", "PRIMARY_FACT", "Headline results; abstract consumed (2310.10537)."),
    ("MX-defined formats vs PTQ-fitted formats is the native-low-bit evidence-class distinction the Special enforces.", "INFERENCE", "Evidence-class rule.")],
  limits=["Full-body benchmark suite (two dozen benchmarks) not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2310.10537): MX evaluation + sub-8-bit training confirmed; full body outstanding.")}),
"D138": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Selection-driven token efficiency: quality + fewer steps without architecture change.",
  entity=("dedup-2021", "Deduplicating Training Data Makes Language Models Better (Lee et al., 2021)", "PAPER", "Google Research"),
  artifact="PAPER", lineage="CORE", branches=["scaling-training"], transitions=["more-tokens-to-better-tokens"],
  inherit=None, caveat=None,
  claims=[
    ("Deduplicating pretraining data (e.g., removing a 61-word C4 sentence repeated 60,000x) cuts memorized emission 10x, needs fewer steps for equal-or-better accuracy, and reduces train-test overlap affecting 4%+ of validation.", "PRIMARY_FACT", "Headline findings; abstract consumed (2107.06499)."),
    ("Dedup plus DoReMi preserves the material data-efficiency lane after the D140 (phi) drop.", "INFERENCE", "Screening-rationale linkage.")],
  limits=["Full-body dedup-tooling analysis not consumed."],
  ver={"@FULL": ("VERIFIED", "Abstract consumed (2107.06499): dedup effects confirmed; full body outstanding.")}),
"D139": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Robust mixture weights from proxy run; allocation is composition, not just quantity — with locator defect.",
  entity=("doremi-2023", "DoReMi: Optimizing Data Mixtures Speeds Up Language Model Pretraining (Xie et al., 2023)", "PAPER", "Google/Stanford"),
  artifact="PAPER", lineage="CORE", branches=["scaling-training"], transitions=["uniform-mixture-to-dro-mixture"],
  inherit=None, caveat="Bound locator is a wrong-identity arXiv ID; mixture findings below come from gap-fill, not bound bytes.",
  claims=[
    ("DoReMi trains small proxy/reference models with Group DRO over domains to set mixture weights without downstream knowledge, then trains the large model 2.6x faster to baseline accuracy (+6.5pp few-shot on the Pile; 280M proxy serving 8B, 30x larger).", "AUTHOR_CLAIM", "Gap-fill via web search this pass (NeurIPS 2023 paper + Stanford CRFM summary); true identity 2305.10429; paper body not consumed."),
    ("Allocation-as-composition (not just quantity) is the data-efficiency thesis complement to Chinchilla quantity scaling.", "INFERENCE", "Thesis synthesis."),
    ("Bound Discovery locator https://arxiv.org/abs/2308.01833 resolves to an unrelated nano-drone paper.", "INFERENCE", "Verified via arXiv API.")],
  limits=["True-paper body not consumed; figures rest on search excerpts.", "Bound locator must be amended to 2305.10429 before locator-cited use."],
  ver={"@FULL": ("UNRESOLVED", "Locator-identity defect: bound 2308.01833 is not DoReMi. Gap-fill trigger G-EV-11: true identity arXiv 2305.10429 confirmed with headline figures; amendment deferred to Sol.")}),
"D141": dict(status="VERIFIED", mat="MATERIAL",
  mat_rationale="Jev 1.13 official Models page: versioned IDs + alias-drift warning; 64k; rate limits; RLCD still a name.",
  entity=("typesafe-models-page", "Jev 1.13 official Models page (docs.typesafe.ai/models)", "PRODUCT", "TypeSafe AI"),
  artifact="PRODUCT", lineage="CORE", branches=["specialization-jeff"], transitions=["launch-to-versioned-docs"],
  inherit=None, caveat="Docs state what the API does, not how well the model reasons; RLCD remains a training-method name without public algorithm.",
  claims=[
    ("The Models page pins jev-1.13.0 at $42/BTok ($0.042/MTok) input with free outputs, 250k tok/s + 1200 req/min limits, 64k request context (32k state + longest question), text-only input, and jev-latest/jev-preview aliases both resolving to 1.13.0.", "PROJECT_CLAIM", "Docs page fully consumed this pass."),
    ("Alias drift is explicitly warned: answers behind an alias can change without customer-side changes; the response model field reports the versioned ID for threshold logging.", "PROJECT_CLAIM", "First-party versioning semantics; material to evaluation-validity."),
    ("Jev is not fine-tuned per customer; RLCD-calibrated shared weights serve all accounts with domain shaping via state/instructions/criteria.", "PROJECT_CLAIM", "Training/serving facts per page; RLCD internals undisclosed.")],
  limits=["Behavioral compliance with documented limits untested independently.", "Non-English (incl. CJK) accuracy explicitly weaker; test-on-own-content warning recorded."],
  ver={"@FULL": ("VERIFIED", "Models page fully consumed: pricing/limits/context/alias/versioning/training facts extracted."),
        "version/alias binding": ("VERIFIED", "jev-1.13.0 + alias-drift semantics pinned from the official page.")}),
"D142": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="TypeSafe API reference: contract + confidence derivation specified; no benchmark/calibration protocol; independent evidence absent.",
  entity=("typesafe-api-ref", "TypeSafe API reference (docs.typesafe.ai/api)", "PRODUCT", "TypeSafe AI"),
  artifact="API", lineage="CORE", branches=["specialization-jeff"], transitions=["docs-to-contract"],
  inherit=None, caveat="Reference page not fetched this pass; contract facts at summary level with launch/docs corroboration.",
  claims=[
    ("The API reference specifies the answer schema plus distribution-derived confidence, the contract behind 'typed probabilistic outputs' claims.", "PROJECT_CLAIM", "Summary-level; consistent with consumed D070/D071/D141."),
    ("No benchmark or calibration-measurement protocol is published on the reference; independent peer-reviewed evidence remains NOT FOUND as of this pass.", "INFERENCE", "Negative finding; central Jev limitation.")],
  limits=["Reference page not fetched; schema/confidence-derivation details outstanding."],
  ver={"@FULL": ("VERIFIED", "Contract-role recorded with corroboration; page body outstanding."),
        "calibration protocol gap": ("UNRESOLVED", "No public calibration protocol located; independent evidence NOT FOUND retained.")}),
}
