from pathlib import Path

FIDELITY = Path("scripts/survey_reader_fidelity_v2.py")
TESTS = Path("tests/test_survey_reader_fidelity_v2.py")


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly one match, found {count}")
    return text.replace(old, new, 1)


fidelity = FIDELITY.read_text(encoding="utf-8")
helper_anchor = '''def _final_package_id(architecture: dict[str, Any]) -> str | None:\n'''
helper = '''def _architecture_allows_narrative_layout_exception(architecture: dict[str, Any]) -> bool:\n    """Return the explicit Architecture-owned opt-out for normal two-column narrative.\n\n    The Special house style is the default. A nonstandard narrative column mode is\n    allowed only when the Human-reviewed Architecture carries a machine-readable\n    publication extension. The visual reviewer must still record the matching\n    evidence marker; the extension alone does not make a layout pass.\n    """\n    publication_extensions = architecture.get("publication_extensions", {})\n    if not isinstance(publication_extensions, dict):\n        return False\n    longform_layout = publication_extensions.get("longform_layout", {})\n    if not isinstance(longform_layout, dict):\n        return False\n    return longform_layout.get("allow_nonstandard_narrative_columns") is True\n\n\n'''
fidelity = replace_once(fidelity, helper_anchor, helper + helper_anchor, "insert Architecture layout helper")

old_visual = '''    if review_kind == "VISUAL":\n        mixed_layout = _check_row(checks, "LONGFORM_MIXED_LAYOUT")\n        _require_evidence(\n            mixed_layout,\n            {\n                "reader-layout:balanced-two-column-narrative",\n                "reader-layout:wide-surfaces-full-width",\n                "reader-layout:references-one-column",\n            },\n            "LONGFORM_MIXED_LAYOUT",\n        )\n        return\n'''
new_visual = '''    if review_kind == "VISUAL":\n        mixed_layout = _check_row(checks, "LONGFORM_MIXED_LAYOUT")\n        _require_evidence(\n            mixed_layout,\n            {\n                "reader-layout:wide-surfaces-full-width",\n                "reader-layout:references-one-column",\n            },\n            "LONGFORM_MIXED_LAYOUT",\n        )\n        evidence = set(mixed_layout.get("evidence_locations", []))\n        normal_narrative = "reader-layout:balanced-two-column-narrative"\n        architecture_exception = "reader-layout:architecture-approved-narrative-exception"\n        if normal_narrative not in evidence:\n            if not _architecture_allows_narrative_layout_exception(architecture):\n                raise ValueError(\n                    "LONGFORM_MIXED_LAYOUT requires reader-layout:balanced-two-column-narrative "\n                    "unless the approved Architecture explicitly allows nonstandard narrative columns"\n                )\n            if architecture_exception not in evidence:\n                raise ValueError(\n                    "LONGFORM_MIXED_LAYOUT Architecture exception requires "\n                    "reader-layout:architecture-approved-narrative-exception evidence"\n                )\n        return\n'''
fidelity = replace_once(fidelity, old_visual, new_visual, "replace visual layout validation")
FIDELITY.write_text(fidelity, encoding="utf-8")


tests = TESTS.read_text(encoding="utf-8")
old_signature = '''    def _architecture(target_pages: int | float = 18, *, array_order_reversed: bool = False) -> dict[str, object]:\n'''
new_signature = '''    def _architecture(\n        target_pages: int | float = 18,\n        *,\n        array_order_reversed: bool = False,\n        allow_narrative_layout_exception: bool = False,\n    ) -> dict[str, object]:\n'''
tests = replace_once(tests, old_signature, new_signature, "expand Architecture fixture signature")

old_return = '''        return {\n            "page_plan": {"target_pages": target_pages, "max_pages": 24},\n            "packages": packages,\n        }\n'''
new_return = '''        publication_extensions: dict[str, object] = {}\n        if allow_narrative_layout_exception:\n            publication_extensions["longform_layout"] = {\n                "allow_nonstandard_narrative_columns": True\n            }\n        return {\n            "page_plan": {"target_pages": target_pages, "max_pages": 24},\n            "packages": packages,\n            "publication_extensions": publication_extensions,\n        }\n'''
tests = replace_once(tests, old_return, new_return, "add Architecture layout extension fixture")

old_test = '''    def test_longform_visual_review_requires_explicit_mixed_layout_evidence(self) -> None:\n        profile = {"publication_profile": "LONGFORM_SPECIAL"}\n        checks = [\n            {\n                "check_id": "LONGFORM_MIXED_LAYOUT",\n                "status": "PASS",\n                "detail": "The exact PDF was reviewed against the Special mixed-layout policy.",\n                "evidence_locations": [\n                    "reader-layout:balanced-two-column-narrative",\n                    "reader-layout:wide-surfaces-full-width",\n                    "reader-layout:references-one-column",\n                ],\n            }\n        ]\n        fidelity.validate_review_depth(\n            profile,\n            self._architecture(target_pages=18),\n            self._manuscript(),\n            13,\n            checks,\n            "VISUAL",\n        )\n\n        checks[0]["evidence_locations"].remove("reader-layout:balanced-two-column-narrative")\n        with self.assertRaisesRegex(ValueError, "balanced-two-column-narrative"):\n            fidelity.validate_review_depth(\n                profile,\n                self._architecture(target_pages=18),\n                self._manuscript(),\n                13,\n                checks,\n                "VISUAL",\n            )\n'''
new_test = '''    def test_longform_visual_review_requires_explicit_mixed_layout_evidence(self) -> None:\n        profile = {"publication_profile": "LONGFORM_SPECIAL"}\n        checks = [\n            {\n                "check_id": "LONGFORM_MIXED_LAYOUT",\n                "status": "PASS",\n                "detail": "The exact PDF was reviewed against the Special mixed-layout policy.",\n                "evidence_locations": [\n                    "reader-layout:balanced-two-column-narrative",\n                    "reader-layout:wide-surfaces-full-width",\n                    "reader-layout:references-one-column",\n                ],\n            }\n        ]\n        fidelity.validate_review_depth(\n            profile,\n            self._architecture(target_pages=18),\n            self._manuscript(),\n            13,\n            checks,\n            "VISUAL",\n        )\n\n        checks[0]["evidence_locations"].remove("reader-layout:balanced-two-column-narrative")\n        with self.assertRaisesRegex(ValueError, "balanced-two-column-narrative"):\n            fidelity.validate_review_depth(\n                profile,\n                self._architecture(target_pages=18),\n                self._manuscript(),\n                13,\n                checks,\n                "VISUAL",\n            )\n\n        # A visual marker cannot self-authorize an exception: the approved\n        # Architecture must carry the machine-readable publication extension.\n        checks[0]["evidence_locations"].append(\n            "reader-layout:architecture-approved-narrative-exception"\n        )\n        with self.assertRaisesRegex(ValueError, "balanced-two-column-narrative"):\n            fidelity.validate_review_depth(\n                profile,\n                self._architecture(target_pages=18),\n                self._manuscript(),\n                13,\n                checks,\n                "VISUAL",\n            )\n\n        fidelity.validate_review_depth(\n            profile,\n            self._architecture(\n                target_pages=18,\n                allow_narrative_layout_exception=True,\n            ),\n            self._manuscript(),\n            13,\n            checks,\n            "VISUAL",\n        )\n\n        # The narrative exception is deliberately narrow; it cannot bypass the\n        # stable full-width wide-surface or one-column References checks.\n        checks[0]["evidence_locations"].remove("reader-layout:wide-surfaces-full-width")\n        with self.assertRaisesRegex(ValueError, "wide-surfaces-full-width"):\n            fidelity.validate_review_depth(\n                profile,\n                self._architecture(\n                    target_pages=18,\n                    allow_narrative_layout_exception=True,\n                ),\n                self._manuscript(),\n                13,\n                checks,\n                "VISUAL",\n            )\n'''
tests = replace_once(tests, old_test, new_test, "expand mixed-layout exception regression")
TESTS.write_text(tests, encoding="utf-8")
