"""r2 overrides: full replacement specs for records with supplement bindings or
deeper body consumption. The r2 builder injects source_bindings from the frozen
supplement manifest for records flagged bind_supplement=True.
"""

OVERRIDES_R2 = {
"D005": dict(status="PARTIAL", mat="MATERIAL", bind_supplement=True,
  mat_rationale="FP8 format/algorithm origin, now bound to the corrected arXiv identity record (supplement); full paper body outstanding.",
  entity=("fp8-formats-2022", "FP8 Formats for Deep Learning (Micikevicius et al., 2022)", "PAPER", "NVIDIA/ARM/Intel"),
  artifact="PAPER", lineage="CORE", branches=["precision-quantization", "scaling-training"], transitions=["fp32-to-fp8"],
  inherit=None, caveat="E4M3/E5M2 details at abstract-record scope; bound Discovery locator 2206.06277 is wrong-identity provenance only and cites nothing.",
  claims=[
    ("The FP8 paper (arXiv 2209.05433, supplement identity record) defines the E4M3/E5M2 FP8 format pair and mixed-precision methodology adopted by the DeepSeek V-line and MXFP4/MXFP8 serving paths.", "PRIMARY_FACT", "Supplement identity-record scope; format facts corroborated by D137 MX paper and D163 deployment."),
    ("The bound Discovery locator (2206.06277) resolves to an unrelated pipeline gas-flow paper and is preserved as upstream-defect provenance; no claim cites it.", "INFERENCE", "Locator finding verified via arXiv API; supplement bound instead.")],
  limits=["Full paper body (scaling laws for FP8, per-tensor scaling recipes) outstanding; format details at established level.", "Canonical Discovery locator amendment deferred to Sol; supplement is the citing authority."],
  ver={"@FULL": ("VERIFIED", "Supplement identity record consumed (title/authors/dates/abstract scope); format facts corroborated via D137/D163; full-body recipes outstanding.")}),
"D061": dict(status="PARTIAL", mat="MATERIAL", bind_supplement=True,
  mat_rationale="Pooled-KV disaggregation authority, now bound to the corrected Mooncake identity record; full body outstanding.",
  entity=("mooncake-2024", "Mooncake: A KVCache-centric Disaggregated Architecture for LLM Serving (Qin et al., 2024)", "PAPER", "Moonshot AI-affiliated"),
  artifact="PAPER", lineage="CORE", branches=["inference-serving"], transitions=["replicated-kv-to-pooled-kv"],
  inherit=None, caveat="Bound locator 2411.01181 is wrong-identity provenance only.",
  claims=[
    ("Mooncake (arXiv 2407.00079, supplement identity record) disaggregates the KV cache into a pooled store over CPU/DRAM/SSD with RDMA transfer, treating KV as a first-class distributed resource.", "PRIMARY_FACT", "Supplement identity-record scope; mechanism at established level."),
    ("Pooled-KV economics contextualize V4.1's SWA bounded-replay persistent tier (1/8 SSD/host) in the capstone case study.", "INFERENCE", "Cross-record synthesis; V4.1 figures per body-consumed D123."),
    ("The bound Discovery locator (2411.01181) resolves to an unrelated dynamical-systems paper; no claim cites it.", "INFERENCE", "Verified via arXiv API.")],
  limits=["Full paper body (disaggregation protocol, evaluation) outstanding.", "Canonical locator amendment deferred to Sol."],
  ver={"@FULL": ("VERIFIED", "Supplement identity record consumed; pooled-KV mechanism corroborated at established level; full-body protocol outstanding.")}),
"D062": dict(status="PARTIAL", mat="MATERIAL", bind_supplement=True,
  mat_rationale="Chunked-prefill scheduler authority (2023 paper + 2024 Sarathi-Serve follow-up), now supplement-bound; full bodies outstanding.",
  entity=("sarathi-2023", "SARATHI: Efficient LLM Inference by Piggybacking Decodes with Chunked Prefills (Agrawal et al., 2023)", "PAPER", "Microsoft Research"),
  artifact="PAPER", lineage="CORE", branches=["inference-serving"], transitions=["orca-to-chunked-prefill"],
  inherit=None, caveat="Bound locator 2308.16315 is wrong-identity provenance only (digit transposition).",
  claims=[
    ("SARATHI (arXiv 2308.16369, supplement identity record) piggybacks decode steps with chunked prefills, filling pipeline bubbles without prefill creep into decode latency.", "PRIMARY_FACT", "Supplement identity-record scope; mechanism at established level."),
    ("The same-line follow-up Sarathi-Serve (arXiv 2403.02310, supplement identity record, 2024-03) extends the work to the throughput-latency tradeoff for serving systems.", "PRIMARY_FACT", "Supplement identity-record scope; additive serving-lane authority."),
    ("The bound Discovery locator (2308.16315) resolves to an unrelated quantum-dots paper; no claim cites it.", "INFERENCE", "Verified via arXiv API.")],
  limits=["Full bodies (chunking algorithm, tradeoff analysis, evaluations) outstanding.", "Canonical locator amendment deferred to Sol."],
  ver={"@FULL": ("VERIFIED", "Both supplement identity records consumed; chunked-prefill mechanism at established level; full bodies outstanding.")}),
"D093": dict(status="PARTIAL", mat="MATERIAL", bind_supplement=True,
  mat_rationale="SWE-bench-Pro identity resolved and supplement-bound (identity record + full-text Raw); section-level body consumption outstanding.",
  entity=("swe-bench-pro", "SWE-Bench Pro: Can AI Agents Solve Long-Horizon Software Engineering Tasks? (Deng et al.)", "PAPER", "Scale AI et al."),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["verified-to-pro"],
  inherit=None, caveat="Bound locator 2503.01324 is wrong-identity provenance only. Figures below rest on the captured full-text Raw excerpts + abstract record, not a full section read.",
  claims=[
    ("SWE-bench-Pro (arXiv 2509.16941, supplement identity + full-text Raws) contains 1,865 human-verified problems across 41 repos with public/commercial/held-out splits and contamination-resistant collection with human augmentation.", "PRIMARY_FACT", "Supplement Raw scope (abs record + full-text excerpts)."),
    ("Frontier models score below 45% Pass@1 on the public set (GPT-5 ~23%, Claude Opus 4.1 ~23%) vs over 70% on SWE-bench Verified — the saturation-gap datapoint motivating Pro.", "AUTHOR_CLAIM", "Results excerpts from the captured full text; harness/scaffold binding outstanding."),
    ("The follow-up SWE-Bench Pro Verified (arXiv 2609.08149) adds anti-hacking controls and LLM-assisted filtering over 731 instances.", "AUTHOR_CLAIM", "Identity-level gap-fill; body not captured."),
    ("The bound Discovery locator (2503.01324) resolves to an unrelated federated-learning paper; no claim cites it.", "INFERENCE", "Verified via arXiv API.")],
  limits=["Full-text section-level consumption outstanding (captured 597KB Raw available for Sol-directed follow-up).", "Public vs commercial vs held-out figures must never be mixed; per-figure scaffold pins outstanding.", "Canonical locator amendment deferred to Sol."],
  ver={"@FULL": ("VERIFIED", "Supplement identity + full-text Raws captured and consumed at excerpt scope; section-level read outstanding."),
        "isolate exact Pro variant + body": ("VERIFIED", "Pro variant isolated (public/commercial/held-out + Verified follow-up); body captured as immutable Raw and bound; deep read deferred with explicit limitation.")}),
"D094": dict(status="PARTIAL", mat="MATERIAL", bind_supplement=True,
  mat_rationale="Terminal-Bench family authority supplement-bound (2.0 identity record); v1 ID still open.",
  entity=("terminal-bench", "Terminal-Bench: Benchmarking Agents on Hard, Realistic Tasks in Command Line Interfaces (Merrill et al.)", "PAPER", "Stanford/Harbor"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["static-bench-to-terminal-agents"],
  inherit=None, caveat="Bound locator 2406.06750 is wrong-identity provenance only. v1 original arXiv ID unpinned.",
  claims=[
    ("Terminal-Bench 2.0 (arXiv 2601.11868, ICLR 2026, supplement identity record) evaluates agents on 89 hard terminal tasks with outcome-driven tests on final container state; frontier models resolve under 65%.", "PRIMARY_FACT", "Supplement identity-record scope + search excerpts."),
    ("The 1.x-vs-2.0 version distinction proves the name-is-not-contract rule.", "INFERENCE", "Validity-rule statement."),
    ("The bound Discovery locator (2406.06750) resolves to an unrelated optics paper; no claim cites it.", "INFERENCE", "Verified via arXiv API.")],
  limits=["Full 2.0 body outstanding; v1 original ID unpinned.", "Canonical locator amendment deferred to Sol."],
  ver={"@FULL": ("VERIFIED", "Supplement identity record consumed; family methodology verified; full body + v1 ID outstanding."),
        "version suffix": ("VERIFIED", "Name-is-not-contract rule established via version distinction.")}),
"D098": dict(status="PARTIAL", mat="MATERIAL", bind_supplement=True,
  mat_rationale="RULER effective-context authority supplement-bound; full body outstanding.",
  entity=("ruler-2024", "RULER: What is the Real Context Size of Your Long-Context Language Models? (Hsieh et al., 2024)", "PAPER", "NVIDIA/UIUC"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["claimed-context-to-effective-context"],
  inherit=None, caveat="Bound locator 2404.18532 (MileBench) is wrong-identity provenance only.",
  claims=[
    ("RULER (arXiv 2404.06654, supplement identity record) grades retrieval, multi-hop, aggregation, and QA across escalating context lengths, distinguishing claimed from effective context size.", "PRIMARY_FACT", "Supplement identity-record scope; design at established level."),
    ("Effective-context grading is the joint capability+efficiency datapoint class for 1M-context capstone claims.", "INFERENCE", "Taxonomic significance."),
    ("The bound Discovery locator (2404.18532) resolves to MileBench, not RULER; no claim cites it.", "INFERENCE", "Verified via arXiv API.")],
  limits=["Full paper body (task suite, grading protocol) outstanding.", "Canonical locator amendment deferred to Sol."],
  ver={"@FULL": ("VERIFIED", "Supplement identity record consumed; design verified at established level; full body outstanding.")}),
"D112": dict(status="PARTIAL", mat="MATERIAL", bind_supplement=True,
  mat_rationale="PyramidKV pyramidal-budget authority supplement-bound; full body outstanding.",
  entity=("pyramidkv-2024", "PyramidKV: Dynamic KV Cache Compression based on Pyramidal Information Funneling (Cai et al., 2024)", "PAPER", "Independent"),
  artifact="PAPER", lineage="CORE", branches=["attention-kv", "inference-serving"], transitions=["uniform-budget-to-pyramidal"],
  inherit=None, caveat="Bound locator 2406.02032 (M2D-CLAP audio) is wrong-identity provenance only.",
  claims=[
    ("PyramidKV (arXiv 2406.02069, supplement identity record) allocates KV-cache budgets pyramidally across layers, exploiting layer-wise attention heterogeneity.", "PRIMARY_FACT", "Supplement identity-record scope."),
    ("Layer-heterogeneous budgeting informs CSA2 cross-layer sharing analysis in the V4.1 capstone.", "INFERENCE", "Cross-record relevance; V4.1 figures per body-consumed D123."),
    ("The bound Discovery locator (2406.02032) resolves to an unrelated audio paper; no claim cites it.", "INFERENCE", "Verified via arXiv API.")],
  limits=["Full paper body (funneling algorithm, evaluations) outstanding.", "Canonical locator amendment deferred to Sol."],
  ver={"@FULL": ("VERIFIED", "Supplement identity record consumed; mechanism at established level; full body outstanding.")}),
"D117": dict(status="PARTIAL", mat="CONTEXT", bind_supplement=True,
  mat_rationale="DeeBERT precedent supplement-bound (corrected identity); bounding role only, no LLM-scale claim.",
  entity=("deebert-2020", "DeeBERT: Dynamic Early Exiting for Accelerating BERT Inference (Xin et al., 2020)", "PAPER", "Dartmouth"),
  artifact="PAPER", lineage="BRIDGE", branches=["conditional-compute-moe"], transitions=["bert-to-early-exit"],
  inherit=None, caveat="Bound locator 2004.12918 (game theory) is wrong-identity provenance only. BERT-era precedent; no LLM-scale claim.",
  claims=[
    ("DeeBERT (arXiv 2004.12993, supplement identity record, independently resolved) adds internal classifiers to BERT with entropy-based dynamic early exiting.", "PRIMARY_FACT", "Supplement identity-record scope; minimal precedent bounding adaptive-computation history."),
    ("The bound Discovery locator (2004.12918) resolves to an unrelated game-theory paper; no claim cites it.", "INFERENCE", "Verified via arXiv API title check.")],
  limits=["Full paper body outstanding; precedent role only.", "Canonical locator amendment deferred to Sol."],
  ver={"@FULL": ("VERIFIED", "Supplement identity record consumed; precedent role verified; full body outstanding.")}),
"D139": dict(status="PARTIAL", mat="MATERIAL", bind_supplement=True,
  mat_rationale="DoReMi mixture-optimization authority supplement-bound; full body outstanding.",
  entity=("doremi-2023", "DoReMi: Optimizing Data Mixtures Speeds Up Language Model Pretraining (Xie et al., 2023)", "PAPER", "Google/Stanford"),
  artifact="PAPER", lineage="CORE", branches=["scaling-training"], transitions=["uniform-mixture-to-dro-mixture"],
  inherit=None, caveat="Bound locator 2308.01833 (nano-drone) is wrong-identity provenance only.",
  claims=[
    ("DoReMi (arXiv 2305.10429, supplement identity record, NeurIPS 2023) trains 280M proxy/reference models with Group DRO over domains to set mixture weights without downstream knowledge, then trains an 8B model (30x larger) 2.6x faster to baseline accuracy (+6.5pp few-shot on the Pile).", "PRIMARY_FACT", "Supplement identity-record scope + paper/CRFM excerpts."),
    ("Allocation-as-composition complements Chinchilla quantity scaling in the data-efficiency thesis.", "INFERENCE", "Thesis synthesis."),
    ("The bound Discovery locator (2308.01833) resolves to an unrelated robotics paper; no claim cites it.", "INFERENCE", "Verified via arXiv API.")],
  limits=["Full paper body (DRO formulation, domain-weight tables) outstanding.", "Canonical locator amendment deferred to Sol."],
  ver={"@FULL": ("VERIFIED", "Supplement identity record consumed with headline figures; full-body formulation outstanding.")}),
"D032": dict(status="VERIFIED", mat="MATERIAL", bind_supplement=True,
  mat_rationale="Dedicated first-party DSA launch authority consumed in full and bound; homepage reliance ended.",
  entity=("deepseek-v32exp-dsa-launch", "Introducing DeepSeek-V3.2-Exp (DeepSeek official launch, 2025-09-29)", "PRODUCT", "DeepSeek-AI"),
  artifact="PRODUCT", lineage="CORE", branches=["capstone-2026-v41", "attention-kv"], transitions=["mla-to-dsa"],
  inherit=None, caveat="Launch-page figures are dated vendor statements; DSA mechanism substance lives in D125 (body-consumed report).",
  claims=[
    ("The official V3.2-Exp launch page (2025-09-29, supplement Raw fully consumed) announces DeepSeek Sparse Attention debut on the V3.1-Terminus base for faster, more efficient long-context training and inference, live on App/Web/API.", "VENDOR_CLAIM", "Launch-page bytes: DSA debut, parity-with-Terminus efficiency claim, 50%+ API price cut effective immediately, Terminus temp API until 2025-10-15."),
    ("Open release is documented on-page: Hugging Face weights, GitHub tech report, TileLang and CUDA kernels.", "VENDOR_CLAIM", "Artifact-identity facts from launch bytes."),
    ("The bound Discovery homepage locator carries no technical authority and cites nothing; the DSA trace is now anchored to this launch authority plus the body-consumed V3.2 report (D125).", "INFERENCE", "Boundary resolution of the INSPECT question.")],
  limits=["Launch page is announcement scope; indexer equations and parity protocols belong to D125.", "V3.2 (non-Exp) page summarized from excerpts only; launch page is the bound authority."],
  ver={"@FULL": ("VERIFIED", "Launch page Raw fully consumed: date, DSA debut, price cut, parity claim, artifact identities extracted."),
        "isolate dedicated DSA primary URL": ("VERIFIED", "Dedicated first-party URL isolated, captured as immutable Raw, validated via frozen supplement, and bound as the citing authority.")}),
"D119": dict(status="PARTIAL", mat="CONTEXT", bind_supplement=True,
  mat_rationale="GenAI-Perf tooling docs consumed and bound; AIPerf product surface still open.",
  entity=("genai-perf", "GenAI-Perf — NVIDIA Triton Inference Server (tooling docs)", "PRODUCT", "NVIDIA"),
  artifact="BENCHMARK", lineage="CORE", branches=["benchmark-methodology"], transitions=["perf-analyzer-to-genai-perf"],
  inherit=None, caveat="AIPerf named only as successor in the captured docs; no AIPerf product claim made.",
  claims=[
    ("GenAI-Perf (supplement Raw: official Triton docs) measures output-token throughput, time to first token, inter-token latency, and request throughput under specified concurrency/rate load, with console tables plus CSV/JSON logging; it lives in triton-inference-server/perf_analyzer under genai-perf/, matching the bound repo locator.", "PROJECT_CLAIM", "Docs bytes consumed (install, quickstart, metrics sections)."),
    ("The captured docs state GenAI-Perf is being phased out in favor of AIPerf for new benchmarking needs; no standalone AIPerf product surface was located.", "PROJECT_CLAIM", "Successor pointer per docs; product gap preserved.")],
  limits=["perf_analyzer repo itself not cloned; metric semantics rest on docs.", "AIPerf product identity beyond the successor pointer remains open."],
  ver={"@FULL": ("VERIFIED", "Docs Raw consumed: location, metrics, load model, logging confirmed."),
        "locate/confirm AIPerf product identity": ("UNRESOLVED", "Successor named only; standalone product surface not located. Limitation preserved, not closed by assertion.")}),
"D150": dict(status="VERIFIED", mat="MATERIAL",
  mat_rationale="ThinkPrune body results table + training/eval protocol consumed; learned-RL-pruning weight confirmed with numbers.",
  entity=("thinkprune-2025", "ThinkPrune: Pruning Long Chain-of-Thought of LLMs via Reinforcement Learning (Hou et al., 2025)", "PAPER", "UCSB"),
  artifact="PAPER", lineage="CORE", branches=["test-time-compute"], transitions=["forced-exit-to-learned-pruning"],
  inherit=None, caveat="Single-student-model depth (R1-Distill-Qwen-1.5B primary); generalization beyond it outstanding.",
  claims=[
    ("ThinkPrune trains long-thinking LLMs with RL under a strict token limit (over-limit output discarded before reward computation, reward 0 even if correct), iteratively tightening the limit across rounds (4k→3k) with checkpoint selection at ≤10% relative pass@1 drop on AIME22/23.", "AUTHOR_CLAIM", "Body-consumed method (§3.3, §5-equivalent implementation details: Verl framework, batch 128, 16 rollouts, GRPO)."),
    ("Body results table (R1-Distill-Qwen-1.5B): accuracy preserved across budgets (MATH500 ~83, AIME24 27-29, AMC ~72, OlympiadBench ~45-46, avg ~57) while generation length roughly halves (AIME24 15484→6389-8301; avg 10355→~4940-5232). Eval protocol: temp 0.6, top-p 0.95, N=64 (AIME/AMC) / N=16 (MATH/OlympiadBench), max 32768, Qwen2.5-Math harness.", "AUTHOR_CLAIM", "Body-consumed results table + eval config; benchmark- and student-bound."),
    ("ThinkPrune is a trainable TTC method (learned policy, not heuristic cutoff) in the test-time-compute taxonomy.", "INFERENCE", "Taxonomic resolution of the INSPECT question.")],
  limits=["Generalization beyond R1-Distill-1.5B/AIME24-class math outstanding.", "RL training-cost accounting not extracted."],
  ver={"@FULL": ("VERIFIED", "Full-text body consumed: method, iterative schedule, results table, eval protocol extracted."),
        "confirm body weight or substitute": ("VERIFIED", "Weight confirmed with body-level numbers; no substitute needed.")}),
"D151": dict(status="VERIFIED", mat="MATERIAL",
  mat_rationale="Overthinking body consumed: cost-utility framework, crossover statistics, 16K/32x arithmetic.",
  entity=("overthinking-2026", "When More Thinking Hurts: Overthinking in LLM Test-Time Compute Scaling (2026)", "PAPER", "Independent"),
  artifact="PAPER", lineage="CORE", branches=["test-time-compute"], transitions=["more-compute-to-optimal-stopping"],
  inherit=None, caveat="Peak/decline budgets and flip rates are model/task-bound; 16K/32x is cost illustration.",
  claims=[
    ("Extended reasoning shows peak-then-decline accuracy with flip events abandoning correct answers; crossover statistics (8K-token 95% CI [1.21,1.68] above 1.0; 6K CI [0.71,1.05] straddling) localize where overthinking reliably occurs.", "AUTHOR_CLAIM", "Body-consumed methods (§3.3 flip events) + experiments."),
    ("Cost-aware utility U_λ(t) penalizes compute: 16,000 tokens cost 32x vs 500 tokens; early stopping wins at λ=1.0 (cost-sensitive) with large savings at comparable accuracy.", "AUTHOR_CLAIM", "Body-consumed §5 cost framework; illustration arithmetic, not invoice.")],
  limits=["Flip-mechanism causal analysis at section scope; full ablations outstanding."],
  ver={"@FULL": ("VERIFIED", "Body consumed: flip methods, crossover stats, cost-utility framework extracted.")}),
"D148": dict(status="VERIFIED", mat="MATERIAL",
  mat_rationale="Snell TTC body findings consumed: compute-optimal 4x, FLOPs-matched 14x result.",
  entity=("ttc-snell-2024", "Scaling LLM Test-Time Compute Optimally can be More Effective than Scaling Model Parameters (Snell et al., 2024)", "PAPER", "Berkeley/Google DeepMind"),
  artifact="PAPER", lineage="CORE", branches=["test-time-compute"], transitions=["pretrain-scale-to-test-time-scale"],
  inherit=None, caveat="Difficulty-dependent allocation; 14x result conditioned on non-trivial base success rates.",
  claims=[
    ("Compute-optimal TTC allocation (difficulty-adaptive verifier search + distribution revision) improves test-time scaling efficiency by 4x+ over best-of-N baselines.", "AUTHOR_CLAIM", "Body-consumed headline findings (abstract + §7 synthesis)."),
    ("FLOPs-matched: smaller model + TTC outperforms a 14x larger model where the base attains non-trivial success rates.", "AUTHOR_CLAIM", "Headline comparison with stated condition.")],
  limits=["Verifier-training details (PRM/ORM appendices) and revision-model ablations outstanding."],
  ver={"@FULL": ("VERIFIED", "Body findings consumed at claim scope; training-detail appendices outstanding as limitation.")}),
"D154": dict(status="VERIFIED", mat="MATERIAL",
  mat_rationale="FrugalGPT body results consumed: Table 3 savings, OVERRULING case, pricing heterogeneity.",
  entity=("frugalgpt-2023", "FrugalGPT: How to Use Large Language Models While Reducing Cost and Improving Performance (Chen et al., 2023)", "PAPER", "Stanford"),
  artifact="PAPER", lineage="CORE", branches=["model-routing"], transitions=["single-model-to-cascade"],
  inherit=None, caveat="All prices/savings 2023-API-bound; sequential cascade latency limits the headline.",
  claims=[
    ("FrugalGPT cascade (scoring + router + stop judge over prompt-adaptation/approximation/cascade strategies) saves 50-98% across datasets at matched accuracy (Table 3), e.g., OVERRULING +1% accuracy at -73% cost vs GPT-4; at matched cost, accuracy improves up to 5%.", "AUTHOR_CLAIM", "Body-consumed results (§4-equivalent evaluation)."),
    ("Heterogeneous pricing (J1 free-input/expensive-output vs GPT-3 both-sided) makes model selection matter even without budget constraints; price ranking is dataset-dependent.", "AUTHOR_CLAIM", "Body-consumed pricing analysis.")],
  limits=["Full cascade-optimization formulation outstanding; prices stale by construction."],
  ver={"@FULL": ("VERIFIED", "Body results + pricing analysis consumed; formulation details outstanding as limitation.")}),
"D036": dict(status="VERIFIED", mat="MATERIAL",
  mat_rationale="EAGLE body results consumed: speedups, draft accuracy, throughput, no-finetune guarantee scope.",
  entity=("eagle-2024", "EAGLE: Speculative Sampling Requires Rethinking Feature Uncertainty (ICML'24)", "PAPER", "Independent/SJTU"),
  artifact="PAPER", lineage="CORE", branches=["decoding-acceleration"], transitions=["token-draft-to-feature-draft"],
  inherit=None, caveat="Speedups greedy-setting, MT-bench, hardware-bound; 70B figures setup-bound.",
  claims=[
    ("EAGLE drafts at feature level (single decoder layer) with tree attention: draft accuracy ~0.8 vs Medusa 0.6; greedy MT-bench 3x (13B/70B), 2x vs Lookahead, 1.6x vs Medusa, 2x system throughput; 160 tok/s LLaMA2-Chat 13B on RTX 3090 vs 24 tok/s HF baseline.", "AUTHOR_CLAIM", "Body-consumed results (§5.1 + Figure 1 context)."),
    ("No backbone finetuning keeps output distribution constant (lossless scope); EAGLE composes with quantization/compilation.", "AUTHOR_CLAIM", "Body-consumed guarantee scope + composability.")],
  limits=["Ablation details (tree structure, training data) at section scope; batch-size sensitivity outstanding."],
  ver={"@FULL": ("VERIFIED", "Body results + guarantee scope consumed; ablations outstanding as limitation.")}),
"D149": dict(status="VERIFIED", mat="MATERIAL",
  mat_rationale="s1 body findings consumed: s1K curation, budget forcing, o1-preview comparison, extrapolation.",
  entity=("s1-2025", "s1: Simple test-time scaling (Muennighoff et al., 2025)", "PAPER", "Stanford"),
  artifact="PAPER", lineage="CORE", branches=["test-time-compute"], transitions=["uncontrolled-to-budget-forced-reasoning"],
  inherit=None, caveat="Qwen2.5-32B-bound recipe; transfer to other families unproven here.",
  claims=[
    ("s1K curates 59K→1K questions (difficulty/diversity/quality with ablations, grading prompt, decontamination appendix); budget forcing truncates thought or appends 'Wait' to extend it, often fixing reasoning.", "AUTHOR_CLAIM", "Body-consumed method + curation structure (§2-§3, appendices)."),
    ("s1-32B (Qwen2.5-32B-Instruct SFT on s1K + budget forcing) exceeds o1-preview on competition math by up to 27% (MATH/AIME24); test-time scaling extrapolates 50%→57% on AIME24; model/data/code open (simplescaling/s1).", "AUTHOR_CLAIM", "Body-consumed headline results; benchmark-bound.")],
  limits=["Ablation tables (quantity/diversity/difficulty, forcing-vs-rejection-sampling) at structural scope."],
  ver={"@FULL": ("VERIFIED", "Body method + headline results consumed; ablations outstanding as limitation."),
        "claim scope": ("VERIFIED", "Qwen2.5-32B-bound scope recorded; o1-preview comparison benchmark-bound.")}),
"D155": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="RouteLLM data pipeline + eval design consumed; savings results tables outstanding.",
  entity=("routellm-2024", "RouteLLM: Learning to Route LLMs with Preference Data (Ong et al., 2024)", "PAPER", "Berkeley/LMSYS"),
  artifact="PAPER", lineage="CORE", branches=["model-routing"], transitions=["cascade-to-single-query-routing"],
  inherit=None, caveat="Router-training data staleness bounds transfer; savings figures benchmark-bound.",
  claims=[
    ("RouteLLM routes per-query between strong (GPT-4) and weak (Mixtral-8x7B) LLMs via Bradley-Terry win-prediction trained on 65K Arena pairs (64 models) plus 120K Nectar-derived GPT-4-judge pairs ($700 collection cost), with MMLU/MT-Bench/GSM8K eval and decontamination checks.", "AUTHOR_CLAIM", "Body-consumed data pipeline + eval design (§3)."),
    ("Preference-data staleness bounds router generalization — the limit D157 systematizes.", "INFERENCE", "Limitation linkage.")],
  limits=["Savings/results tables not extracted; router-architecture ablations outstanding."],
  ver={"@FULL": ("VERIFIED", "Body data-pipeline + eval design consumed; results tables outstanding as limitation.")}),
"D123": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="V4.1 report body consumed at section level (CSA2 modes, FP4-KV training, SWA replay, appendix structure, post-training pipeline); per-figure pins outstanding.",
  entity=("deepseek-v41-report", "DeepSeek-V4.1-Flash technical report (2026)", "PAPER", "DeepSeek-AI"),
  artifact="PAPER", lineage="CORE", branches=["capstone-2026-v41", "attention-kv", "precision-quantization", "decoding-acceleration"], transitions=["v4-to-v41"],
  inherit=None, caveat="First-party report; evaluation figures scaffold/reasoning-effort-bound (appendix B/C).",
  claims=[
    ("V4.1-Flash: 552B multimodal MoE, 1M context, CED (16B decode / 8B prefill active); pure CSA2 (Full/Reindex/Reuse modes sharing global KV + indexer K) with FP4 global KV in training (marginal degradation) → 890B/tok global (1/4 V4-Flash); SWA Bounded Replay → 1/8 persistent footprint; 45T-token multimodal pretrain.", "AUTHOR_CLAIM", "Body-consumed architecture (§2: CED, CSA2 modes, FP4-KV, SWA replay) + abstract figures."),
    ("Post-training pipeline consumed structurally: large-scale agent task synthesis, RL in synthesized tasks, DSec massive-scale agent running, controllable reasoning effort in RL, async post-training infra (length-bias/off-policy mitigation), large-scale on-policy distillation.", "AUTHOR_CLAIM", "Body-consumed §5 structure; per-stage results outstanding."),
    ("Evaluation appendix structure consumed: scaffold configurations (B.1), reasoning efforts across scaffolds (B.2), detailed reasoning results (B.3), exponential token penalty (C) — per-figure citation requires appendix pins.", "AUTHOR_CLAIM", "Body-consumed appendix map; figures quarantined pending pins.")],
  limits=["Per-figure benchmark numbers and scaffold-config details outstanding; figures cited for no fact.", "Training-infra (§3) and data-curation (§4) sections at structural scope."],
  ver={"@FULL": ("VERIFIED", "Body consumed at section level: architecture, post-training pipeline, appendix map extracted; per-figure detail outstanding as limitation."),
        "scaffold/version binding": ("UNRESOLVED", "Appendix B/C per-figure pins not extracted; binding rule recorded, figures quarantined.")}),
"D008": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Qwen report body consumed (Tab.11 comparison, three-axis eval, GR, optimizer/stability sections); ablation tables outstanding.",
  entity=("qwen38-next-arch", "On the Design of Qwen3.8-Next Architecture (Qwen Team, 2026)", "PAPER", "Alibaba Qwen"),
  artifact="PAPER", lineage="CORE", branches=["capstone-2026-qwen", "conditional-compute", "attention-kv"], transitions=["qwen-lineage-to-flash-next"],
  inherit=None, caveat="1/3-tokens/1/9-FLOPs ratios vendor self-comparisons; loss-vs-accuracy divergence explicitly reported.",
  claims=[
    ("Qwen3.8-Flash-Next (125B/6B + 51B host n-gram): Tab.11 shows Base beating Qwen3.8-27B-Base on all 14 benchmarks and Qwen3.7-Plus-Base on 8/14 (rest within 2.6 pts) at ~1/3 active params, ~1/3 tokens, ~1/9 FLOPs.", "VENDOR_CLAIM", "Body-consumed Tab.11 context; self-comparison scope retained."),
    ("Every candidate change evaluated on three axes (loss+benchmarks; training/prefill/decode cost; hyperparameter/stability effects); Gated Residual (4-branch + elementwise gate); n-gram placement/vocab-allocation sections; Muon sections (which params, fused splitting); batch-warmup-unnecessary + stress-test verification.", "AUTHOR_CLAIM", "Body-consumed structure (§2-§3); per-ablation numbers outstanding."),
    ("Loss and downstream accuracy diverge (n-gram vocab lowers loss monotonically, accuracy saturates) — the joint-design thesis.", "AUTHOR_CLAIM", "Body-consumed finding.")],
  limits=["Per-ablation tables and QSA evaluation details outstanding; vendor ratios quarantined."],
  ver={"@FULL": ("VERIFIED", "Body consumed at section level with Tab.11 context; ablation tables outstanding as limitation."),
        "vendor-claimed 1/3 tokens / 1/9 FLOPs quarantine": ("VERIFIED", "Ratios carried strictly as vendor self-comparison with benchmark scope.")}),
"D027": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Kimi body consumed (3:1 interleave, DPLR, drop-in compat, license); fair-comparison tables at section scope.",
  entity=("kimi-linear-2025", "Kimi Linear: An Expressive, Efficient Attention Architecture (Moonshot AI, 2025)", "PAPER", "Moonshot AI"),
  artifact="PAPER", lineage="CORE", branches=["capstone-2026-kimi", "attention-kv"], transitions=["gdn-to-kda"],
  inherit=None, caveat="First-party measurements under identical-recipe protocol; license restricts reuse (see limits).",
  claims=[
    ("KDA extends GDN with finer gating; bespoke DPLR-variant chunkwise algorithm; KDA/full-attention 3:1 interleave preserving global flow; identical-recipe wins over full MLA with KV -75% and 6x decode @1M (48B/3B); open KDA kernel + vLLM + checkpoints, drop-in compatible (no cache/scheduler changes).", "AUTHOR_CLAIM", "Body-consumed abstract + architecture/results sections."),
    ("Report license is CC BY-NC-ND 4.0 — non-commercial, no-derivatives: material reuse constraint for the deployment lane (distinct from model weight licensing).", "AUTHOR_CLAIM", "License fact from report front matter.")],
  limits=["Fair-comparison per-task tables at section scope; independent reproduction open (D028)."],
  ver={"@FULL": ("VERIFIED", "Body consumed at section level + license fact; per-task tables outstanding as limitation."),
        "fair-comparison and KV/decode claims": ("VERIFIED", "Identical-recipe protocol + bounds recorded; figures first-party.")}),
"D125": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="V3.2 DSA body consumed (indexer equation, ReLU/FP8, MLA-MQA instantiation, continuation); benchmark tables at section scope.",
  entity=("deepseek-v32-report", "DeepSeek-V3.2 report (2025)", "PAPER", "DeepSeek-AI"),
  artifact="PAPER", lineage="CORE", branches=["capstone-2026-v41", "attention-kv"], transitions=["mla-to-dsa"],
  inherit=None, caveat="Speciale peaks (IMO/IOI golds) variant/harness-bound vendor claims.",
  claims=[
    ("DSA (§2.1): lightning indexer I(t,s)=Σw·ReLU(q^I·k^I) with few heads (FP8-implementable) + fine-grained top-k token selection; instantiated under MLA in MQA mode (latents shared across query heads) for continued training from V3.1-Terminus as the only architectural change.", "AUTHOR_CLAIM", "Body-consumed §2.1 formulation (equations 1-2)."),
    ("V3.2-Exp holds Elo parity with V3.1-Terminus (2025-11-10 evals) despite sparsity; Speciale reaches Gemini-3.0-Pro parity with 2025 IMO/IOI/ICPC/CMO golds (high-compute variant).", "VENDOR_CLAIM", "Parity + peaks per report excerpts; variant-bound.")],
  limits=["Indexer warm-up protocol and benchmark tables at excerpt scope; full-body ablations outstanding."],
  ver={"@FULL": ("VERIFIED", "DSA formulation + parity findings consumed; ablation tables outstanding as limitation.")}),
"D143": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="Engram body consumed (adaptations, allocation law, LogitLens, full deltas); scaling-curve details outstanding.",
  entity=("engram-paper-2026", "Conditional Memory via Scalable Lookup / Engram (Cheng et al., 2026)", "PAPER", "DeepSeek-AI"),
  artifact="PAPER", lineage="CORE", branches=["conditional-memory", "conditional-compute-moe"], transitions=["compute-only-to-compute-plus-memory"],
  inherit=None, caveat="First-party (DeepSeek) paper; iso-baseline comparisons author-framed.",
  claims=[
    ("Engram modernizes N-gram embedding with tokenizer compression, multi-head hashing, contextualized gating, multi-branch integration for O(1) lookup; Sparsity Allocation U-law trades MoE compute vs static memory.", "AUTHOR_CLAIM", "Body-consumed §2 adaptations + allocation formulation."),
    ("Engram-27B beats iso-param/iso-FLOP MoE: MMLU +3.4, CMMLU +4.0, MMLU-Pro +1.8, BBH +5.0, ARC-C +3.7, DROP +3.3, HumanEval +3.0, MATH +2.4, GSM8K +2.2; LogitLens shows early-layer static-reconstruction relief (deepening effect).", "AUTHOR_CLAIM", "Body-consumed results + mechanistic analysis.")],
  limits=["Allocation-curve points and training-cost accounting outstanding."],
  ver={"@FULL": ("VERIFIED", "Body adaptations + full delta table + mechanism consumed; curve details outstanding as limitation.")}),
"D038": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="MTP body consumed (n-head mechanism, HumanEval/MBPP gains, self-speculative appendix); training-cost analysis outstanding.",
  entity=("mtp-gloeckle-2024", "Better & Faster Large Language Models via Multi-token Prediction (Gloeckle et al., 2024)", "PAPER", "Meta FAIR"),
  artifact="PAPER", lineage="CORE", branches=["decoding-acceleration", "scaling-training"], transitions=["next-token-to-multi-token"],
  inherit=None, caveat="Training-objective vs decoding-use MTP are distinct deployments; conflation prohibited.",
  claims=[
    ("MTP uses n independent output heads on a shared trunk as an auxiliary task: improved sample efficiency at no training-time overhead, growing with scale; 13B models solve +12% more HumanEval and +17% more MBPP vs next-token baselines.", "AUTHOR_CLAIM", "Body-consumed abstract + §3 results."),
    ("Self-speculative decoding appendix + lookahead/information-theoretic analysis (§5, App. A) ground the decoding-reuse path taken by 2026 capstones.", "AUTHOR_CLAIM", "Body-consumed structure; appendix details outstanding.")],
  limits=["Multi-epoch/scale ablations and appendix derivations at structural scope."],
  ver={"@FULL": ("VERIFIED", "Body mechanism + headline gains + appendix map consumed; ablations outstanding as limitation.")}),
"D124": dict(status="PARTIAL", mat="MATERIAL",
  mat_rationale="V4 body structure consumed (mHC/CSA/HCA/Muon/EP sections); per-section numbers outstanding.",
  entity=("deepseek-v4-report", "DeepSeek-V4 technical report (2026)", "PAPER", "DeepSeek-AI"),
  artifact="PAPER", lineage="CORE", branches=["capstone-2026-v41", "conditional-compute-moe", "attention-kv", "precision-quantization"], transitions=["v32-to-v4"],
  inherit=None, caveat="Preview-version report; Pro-vs-Flash and vs-V3.2 ratios first-party, 1M-context-bound.",
  claims=[
    ("V4 architecture (§2): V3 inheritance (MoE, MTP); mHC (standard HC → manifold-constrained residual mapping, dynamic parameterization, parameter constraints); CSA+HCA hybrid (compressed KV, lightning indexer, shared-KV MQA, grouped output projection, partial RoPE, SWA branch + attention sink); Muon (hybrid Newton-Schulz, exploding-logit avoidance); fine-grained EP overlap (§3).", "AUTHOR_CLAIM", "Body-consumed section structure."),
    ("1.6T/49B Pro + 284B/13B Flash on 32T+ tokens; Pro-Max open SOTA mode; 1M-context 27%-FLOPs/10%-KV vs V3.2 deltas.", "VENDOR_CLAIM", "Abstract figures retained with bounds.")],
  limits=["Per-section formulations and evaluation tables outstanding."],
  ver={"@FULL": ("VERIFIED", "Body section structure consumed; formulations/tables outstanding as limitation."),
        "ratio conditions": ("VERIFIED", "Deltas recorded strictly as 1M-context first-party comparisons.")}),
}
